//!! generated by clutz.
// Generated from third_party/closure/goog/labs/useragent/browser.js
declare namespace ಠ_ಠ.clutz.goog.labs.userAgent.browser {
  function getVersion ( ) : string ;
  function isAndroidBrowser ( ) : boolean ;
  function isChrome ( ) : boolean ;
  function isCoast ( ) : boolean ;
  function isEdge ( ) : boolean ;
  function isEdgeChromium ( ) : boolean ;
  function isFirefox ( ) : boolean ;
  function isIE ( ) : boolean ;
  function isIosWebview ( ) : boolean ;
  function isOpera ( ) : boolean ;
  function isOperaChromium ( ) : boolean ;
  function isSafari ( ) : boolean ;
  /**
   * For more information, see:
   * http://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html
   */
  function isSilk ( ) : boolean ;
  function isVersionOrHigher (version : string | number ) : boolean ;
}
// Generated from third_party/closure/goog/labs/useragent/browser.js
declare module 'goog:goog.labs.userAgent.browser' {
  import browser = ಠ_ಠ.clutz.goog.labs.userAgent.browser;
  export = browser;
  const __clutz_actual_path: 'google3/third_party/closure/goog/labs/useragent/browser';
}
declare module 'google3/third_party/closure/goog/labs/useragent/browser' {
  import browser = ಠ_ಠ.clutz.goog.labs.userAgent.browser;
  export = browser;
  const __clutz_actual_namespace: 'goog.labs.userAgent.browser';
}
