//!! generated by clutz.
// Generated from third_party/closure/goog/labs/useragent/platform.js
declare namespace ಠ_ಠ.clutz.goog.labs.userAgent.platform {
  /**
   * The version of the platform. We only determine the version for Windows,
   * Mac, and Chrome OS. It doesn't make much sense on Linux. For Windows, we only
   * look at the NT version. Non-NT-based versions (e.g. 95, 98, etc.) are given
   * version 0.0.
   */
  function getVersion ( ) : string ;
  function isAndroid ( ) : boolean ;
  function isChromeOS ( ) : boolean ;
  function isChromecast ( ) : boolean ;
  function isIos ( ) : boolean ;
  function isIpad ( ) : boolean ;
  function isIphone ( ) : boolean ;
  function isIpod ( ) : boolean ;
  function isKaiOS ( ) : boolean ;
  /**
   * Note: ChromeOS is not considered to be Linux as it does not report itself
   * as Linux in the user agent string.
   */
  function isLinux ( ) : boolean ;
  function isMacintosh ( ) : boolean ;
  function isVersionOrHigher (version : string | number ) : boolean ;
  function isWindows ( ) : boolean ;
}
// Generated from third_party/closure/goog/labs/useragent/platform.js
declare module 'goog:goog.labs.userAgent.platform' {
  import platform = ಠ_ಠ.clutz.goog.labs.userAgent.platform;
  export = platform;
  const __clutz_actual_path: 'google3/third_party/closure/goog/labs/useragent/platform';
}
declare module 'google3/third_party/closure/goog/labs/useragent/platform' {
  import platform = ಠ_ಠ.clutz.goog.labs.userAgent.platform;
  export = platform;
  const __clutz_actual_namespace: 'goog.labs.userAgent.platform';
}
