//!! generated by clutz.
// Generated from third_party/closure/goog/labs/useragent/util.js
declare namespace ಠ_ಠ.clutz.goog.labs.userAgent.util {
  /**
   * Parses the user agent into tuples for each section.
   */
  function extractVersionTuples (userAgent : string ) : string [] [] ;
  function getUserAgent ( ) : string ;
  function matchUserAgent (str : string ) : boolean ;
  function matchUserAgentIgnoreCase (str : string ) : boolean ;
  /**
   * Applications may override browser detection on the built in
   * navigator.userAgent object by setting this string. Set to null to use the
   * browser object instead.
   * @param opt_userAgent The User-Agent override.
   */
  function setUserAgent (opt_userAgent ? : string | null ) : void ;
}
// Generated from third_party/closure/goog/labs/useragent/util.js
declare module 'goog:goog.labs.userAgent.util' {
  import util = ಠ_ಠ.clutz.goog.labs.userAgent.util;
  export = util;
  const __clutz_actual_path: 'google3/third_party/closure/goog/labs/useragent/util';
}
declare module 'google3/third_party/closure/goog/labs/useragent/util' {
  import util = ಠ_ಠ.clutz.goog.labs.userAgent.util;
  export = util;
  const __clutz_actual_namespace: 'goog.labs.userAgent.util';
}
