load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

package(default_visibility = ["//visibility:public"])

closure_js_library(
    name = "flags",
    srcs = ["flags.js"],
    lenient = True,
)

closure_js_library(
    name = "flags_oss",
    srcs = ["flags_oss.js"],
    lenient = True,
)
