//!! generated by clutz.
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for AutoCompleteValues.
   */
  /**
   * ARIA state values for AutoCompleteValues.
   */
  enum AutoCompleteValues {
    BOTH = 'both' ,
    INLINE = 'inline' ,
    LIST = 'list' ,
    NONE = 'none' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.AutoCompleteValues' {
  import AutoCompleteValues = ಠ_ಠ.clutz.goog.a11y.aria.AutoCompleteValues;
  export default AutoCompleteValues;
  const __clutz_actual_path: 'google3/third_party/closure/goog/a11y/aria/attributes';
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  import AutoCompleteValues = ಠ_ಠ.clutz.goog.a11y.aria.AutoCompleteValues;
  export { AutoCompleteValues };
  const __clutz_strip_property: 'AutoCompleteValues';
  const __clutz_actual_namespace: 'goog.a11y.aria.AutoCompleteValues';
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for CheckedValues.
   */
  /**
   * ARIA state values for CheckedValues.
   */
  enum CheckedValues {
    FALSE = 'false' ,
    MIXED = 'mixed' ,
    TRUE = 'true' ,
    UNDEFINED = 'undefined' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.CheckedValues' {
  import CheckedValues = ಠ_ಠ.clutz.goog.a11y.aria.CheckedValues;
  export default CheckedValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for DropEffectValues.
   */
  /**
   * ARIA state values for DropEffectValues.
   */
  enum DropEffectValues {
    COPY = 'copy' ,
    EXECUTE = 'execute' ,
    LINK = 'link' ,
    MOVE = 'move' ,
    NONE = 'none' ,
    POPUP = 'popup' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.DropEffectValues' {
  import DropEffectValues = ಠ_ಠ.clutz.goog.a11y.aria.DropEffectValues;
  export default DropEffectValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for ExpandedValues.
   */
  /**
   * ARIA state values for ExpandedValues.
   */
  enum ExpandedValues {
    FALSE = 'false' ,
    TRUE = 'true' ,
    UNDEFINED = 'undefined' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.ExpandedValues' {
  import ExpandedValues = ಠ_ಠ.clutz.goog.a11y.aria.ExpandedValues;
  export default ExpandedValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for GrabbedValues.
   */
  /**
   * ARIA state values for GrabbedValues.
   */
  enum GrabbedValues {
    FALSE = 'false' ,
    TRUE = 'true' ,
    UNDEFINED = 'undefined' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.GrabbedValues' {
  import GrabbedValues = ಠ_ಠ.clutz.goog.a11y.aria.GrabbedValues;
  export default GrabbedValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for InvalidValues.
   */
  /**
   * ARIA state values for InvalidValues.
   */
  enum InvalidValues {
    FALSE = 'false' ,
    GRAMMAR = 'grammar' ,
    SPELLING = 'spelling' ,
    TRUE = 'true' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.InvalidValues' {
  import InvalidValues = ಠ_ಠ.clutz.goog.a11y.aria.InvalidValues;
  export default InvalidValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for LivePriority.
   */
  /**
   * ARIA state values for LivePriority.
   */
  enum LivePriority {
    ASSERTIVE = 'assertive' ,
    OFF = 'off' ,
    POLITE = 'polite' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.LivePriority' {
  import LivePriority = ಠ_ಠ.clutz.goog.a11y.aria.LivePriority;
  export default LivePriority;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for OrientationValues.
   */
  /**
   * ARIA state values for OrientationValues.
   */
  enum OrientationValues {
    HORIZONTAL = 'horizontal' ,
    VERTICAL = 'vertical' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.OrientationValues' {
  import OrientationValues = ಠ_ಠ.clutz.goog.a11y.aria.OrientationValues;
  export default OrientationValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for PressedValues.
   */
  /**
   * ARIA state values for PressedValues.
   */
  enum PressedValues {
    FALSE = 'false' ,
    MIXED = 'mixed' ,
    TRUE = 'true' ,
    UNDEFINED = 'undefined' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.PressedValues' {
  import PressedValues = ಠ_ಠ.clutz.goog.a11y.aria.PressedValues;
  export default PressedValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for RelevantValues.
   */
  /**
   * ARIA state values for RelevantValues.
   */
  enum RelevantValues {
    ADDITIONS = 'additions' ,
    ALL = 'all' ,
    REMOVALS = 'removals' ,
    TEXT = 'text' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.RelevantValues' {
  import RelevantValues = ಠ_ಠ.clutz.goog.a11y.aria.RelevantValues;
  export default RelevantValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for SelectedValues.
   */
  /**
   * ARIA state values for SelectedValues.
   */
  enum SelectedValues {
    FALSE = 'false' ,
    TRUE = 'true' ,
    UNDEFINED = 'undefined' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.SelectedValues' {
  import SelectedValues = ಠ_ಠ.clutz.goog.a11y.aria.SelectedValues;
  export default SelectedValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA state values for SortValues.
   */
  /**
   * ARIA state values for SortValues.
   */
  enum SortValues {
    ASCENDING = 'ascending' ,
    DESCENDING = 'descending' ,
    NONE = 'none' ,
    OTHER = 'other' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.SortValues' {
  import SortValues = ಠ_ಠ.clutz.goog.a11y.aria.SortValues;
  export default SortValues;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA states and properties.
   */
  /**
   * ARIA states and properties.
   */
  enum State {
    ACTIVEDESCENDANT = 'activedescendant' ,
    ATOMIC = 'atomic' ,
    AUTOCOMPLETE = 'autocomplete' ,
    BUSY = 'busy' ,
    CHECKED = 'checked' ,
    COLINDEX = 'colindex' ,
    CONTROLS = 'controls' ,
    DESCRIBEDBY = 'describedby' ,
    DISABLED = 'disabled' ,
    DROPEFFECT = 'dropeffect' ,
    EXPANDED = 'expanded' ,
    FLOWTO = 'flowto' ,
    GRABBED = 'grabbed' ,
    HASPOPUP = 'haspopup' ,
    HIDDEN = 'hidden' ,
    INVALID = 'invalid' ,
    LABEL = 'label' ,
    LABELLEDBY = 'labelledby' ,
    LEVEL = 'level' ,
    LIVE = 'live' ,
    MULTILINE = 'multiline' ,
    MULTISELECTABLE = 'multiselectable' ,
    ORIENTATION = 'orientation' ,
    OWNS = 'owns' ,
    POSINSET = 'posinset' ,
    PRESSED = 'pressed' ,
    READONLY = 'readonly' ,
    RELEVANT = 'relevant' ,
    REQUIRED = 'required' ,
    ROWINDEX = 'rowindex' ,
    SELECTED = 'selected' ,
    SETSIZE = 'setsize' ,
    SORT = 'sort' ,
    VALUEMAX = 'valuemax' ,
    VALUEMIN = 'valuemin' ,
    VALUENOW = 'valuenow' ,
    VALUETEXT = 'valuetext' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/attributes.js
declare module 'goog:goog.a11y.aria.State' {
  import State = ಠ_ಠ.clutz.goog.a11y.aria.State;
  export default State;
}
declare module 'google3/third_party/closure/goog/a11y/aria/attributes' {
  export {};
  const __clutz_multiple_provides: true;
}
