//!! generated by clutz.
// Generated from third_party/closure/goog/a11y/aria/datatables.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria.datatables {
  /**
   * A method that creates a map that contains mapping between an ARIA state and
   * the default value for it. Note that not all ARIA states have default values.
   */
  function getDefaultValuesMap ( ) : { [ /* warning: coerced from (goog.a11y.aria.State|string) */ key: string ]: string | boolean | number } ;
}
// Generated from third_party/closure/goog/a11y/aria/datatables.js
declare module 'goog:goog.a11y.aria.datatables' {
  import datatables = ಠ_ಠ.clutz.goog.a11y.aria.datatables;
  export = datatables;
  const __clutz_actual_path: 'google3/third_party/closure/goog/a11y/aria/datatables';
}
declare module 'google3/third_party/closure/goog/a11y/aria/datatables' {
  import datatables = ಠ_ಠ.clutz.goog.a11y.aria.datatables;
  export = datatables;
  const __clutz_actual_namespace: 'goog.a11y.aria.datatables';
}
