//!! generated by clutz.
// Generated from third_party/closure/goog/a11y/aria/roles.js
declare namespace ಠ_ಠ.clutz.goog.a11y.aria {
  /**
   * ARIA role values.
   */
  /**
   * ARIA role values.
   */
  enum Role {
    ALERT = 'alert' ,
    ALERTDIALOG = 'alertdialog' ,
    APPLICATION = 'application' ,
    ARTICLE = 'article' ,
    BANNER = 'banner' ,
    BUTTON = 'button' ,
    CHECKBOX = 'checkbox' ,
    COLUMNHEADER = 'columnheader' ,
    COMBOBOX = 'combobox' ,
    COMPLEMENTARY = 'complementary' ,
    CONTENTINFO = 'contentinfo' ,
    DEFINITION = 'definition' ,
    DIALOG = 'dialog' ,
    DIRECTORY = 'directory' ,
    DOCUMENT = 'document' ,
    FORM = 'form' ,
    GRID = 'grid' ,
    GRIDCELL = 'gridcell' ,
    GROUP = 'group' ,
    HEADING = 'heading' ,
    IMG = 'img' ,
    LINK = 'link' ,
    LIST = 'list' ,
    LISTBOX = 'listbox' ,
    LISTITEM = 'listitem' ,
    LOG = 'log' ,
    MAIN = 'main' ,
    MARQUEE = 'marquee' ,
    MATH = 'math' ,
    MENU = 'menu' ,
    MENUBAR = 'menubar' ,
    MENU_ITEM = 'menuitem' ,
    MENU_ITEM_CHECKBOX = 'menuitemcheckbox' ,
    MENU_ITEM_RADIO = 'menuitemradio' ,
    NAVIGATION = 'navigation' ,
    NOTE = 'note' ,
    OPTION = 'option' ,
    PRESENTATION = 'presentation' ,
    PROGRESSBAR = 'progressbar' ,
    RADIO = 'radio' ,
    RADIOGROUP = 'radiogroup' ,
    REGION = 'region' ,
    ROW = 'row' ,
    ROWGROUP = 'rowgroup' ,
    ROWHEADER = 'rowheader' ,
    SCROLLBAR = 'scrollbar' ,
    SEARCH = 'search' ,
    SEPARATOR = 'separator' ,
    SLIDER = 'slider' ,
    SPINBUTTON = 'spinbutton' ,
    STATUS = 'status' ,
    TAB = 'tab' ,
    TAB_LIST = 'tablist' ,
    TAB_PANEL = 'tabpanel' ,
    TEXTBOX = 'textbox' ,
    TEXTINFO = 'textinfo' ,
    TIMER = 'timer' ,
    TOOLBAR = 'toolbar' ,
    TOOLTIP = 'tooltip' ,
    TREE = 'tree' ,
    TREEGRID = 'treegrid' ,
    TREEITEM = 'treeitem' ,
  }
}
// Generated from third_party/closure/goog/a11y/aria/roles.js
declare module 'goog:goog.a11y.aria.Role' {
  import Role = ಠ_ಠ.clutz.goog.a11y.aria.Role;
  export default Role;
  const __clutz_actual_path: 'google3/third_party/closure/goog/a11y/aria/roles';
}
declare module 'google3/third_party/closure/goog/a11y/aria/roles' {
  import Role = ಠ_ಠ.clutz.goog.a11y.aria.Role;
  export { Role };
  const __clutz_strip_property: 'Role';
  const __clutz_actual_namespace: 'goog.a11y.aria.Role';
}
