/**
 * @license
 * Copyright The Closure Library Authors.
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTOGENERATED. DO NOT EDIT.
// clang-format off

goog.provide('goog.html.safeUrlTestVectors');
goog.setTestOnly('goog.html.safeUrlTestVectors');

goog.html.safeUrlTestVectors.BASE_VECTORS = [
      {input: '', expected: '', safe: true},
      {input: 'http://example.com/', expected: 'http://example.com/', safe: true},
      {input: 'https://example.com', expected: 'https://example.com', safe: true},
      {input: 'mailto:foo@example.com', expected: 'mailto:foo@example.com', safe: true},
      {input: 'ftp://example.com', expected: 'ftp://example.com', safe: true},
      {input: 'ftp://username@example.com', expected: 'ftp://username@example.com', safe: true},
      {input: 'ftp://username:password@example.com', expected: 'ftp://username:password@example.com', safe: true},
      {input: 'HTtp://example.com/', expected: 'HTtp://example.com/', safe: true},
      {input: 'https://example.com/path?foo\x3Dbar#baz', expected: 'https://example.com/path?foo\x3Dbar#baz', safe: true},
      {input: 'https://example.com:123/path?foo\x3Dbar\x26abc\x3Ddef#baz', expected: 'https://example.com:123/path?foo\x3Dbar\x26abc\x3Ddef#baz', safe: true},
      {input: '//example.com/path', expected: '//example.com/path', safe: true},
      {input: '/path', expected: '/path', safe: true},
      {input: '/path?foo\x3Dbar#baz', expected: '/path?foo\x3Dbar#baz', safe: true},
      {input: 'path', expected: 'path', safe: true},
      {input: 'path?foo\x3Dbar#baz', expected: 'path?foo\x3Dbar#baz', safe: true},
      {input: 'p//ath', expected: 'p//ath', safe: true},
      {input: 'p//ath?foo\x3Dbar#baz', expected: 'p//ath?foo\x3Dbar#baz', safe: true},
      {input: '#baz', expected: '#baz', safe: true},
      {input: '?:', expected: '?:', safe: true},
      {input: 'javascript:evil();', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'javascript:evil();//\u000Ahttp://good.com/', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:blah', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'not-data:image/png;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: ' data:image/png;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/png;base64,z\x3D ', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:ximage/png', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:ximage/png;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/pngx;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:audio/whatever;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:audio/;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/whatever;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/png;base64,', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/png;base64,abc\x3D!', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/png;base64,$$', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/png;base64,\u0000', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/mp4;baze64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/mp4;,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:text/html,sdfsdfsdfsfsdfs;base64,anything', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:image/svg+xml;base64,abc', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'tel:+1234567890', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'sms:+1234567890', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'callto:+1234567890', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'wtai://wp/mc;+1234567890', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'rtsp://example.org/', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'market://details?id\x3Dapp', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'geo:37.7,42.0', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'skype:chat?jid\x3Dfoo', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'whatsapp://send?text\x3DHello', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'ssh://cloud.google.com', expected: 'about:invalid#zClosurez', safe: false},
      {input: ':', expected: 'about:invalid#zClosurez', safe: false},
      {input: '\\:', expected: 'about:invalid#zClosurez', safe: false},
      {input: ':/:', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'path\u000A:', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'java\u0000script:evil();', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'http://www.f\u0000\u0000.com', expected: 'http://www.f\u0000\u0000.com', safe: true},
      {input: 'data:image/png;base64,abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/\x3D', expected: 'data:image/png;base64,abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/\x3D', safe: true},
      {input: 'dATa:iMage/pNg;bASe64,abc\x3D\x3D\x3D', expected: 'dATa:iMage/pNg;bASe64,abc\x3D\x3D\x3D', safe: true},
      {input: 'data:image/webp;base64,abc\x3D\x3D\x3D', expected: 'data:image/webp;base64,abc\x3D\x3D\x3D', safe: true},
      {input: 'data:audio/ogg;base64,abc', expected: 'data:audio/ogg;base64,abc', safe: true},
      {input: 'data:audio/L16;base64,abc', expected: 'data:audio/L16;base64,abc', safe: true},
      {input: 'data:audio/x-matroska;base64,z\x3D', expected: 'data:audio/x-matroska;base64,z\x3D', safe: true},
      {input: 'data:video/mpeg;base64,abc', expected: 'data:video/mpeg;base64,abc', safe: true},
      {input: 'data:video/ogg;base64,z\x3D', expected: 'data:video/ogg;base64,z\x3D', safe: true},
      {input: 'data:video/mp4;base64,z\x3D', expected: 'data:video/mp4;base64,z\x3D', safe: true},
      {input: 'data:video/webm;base64,z\x3D', expected: 'data:video/webm;base64,z\x3D', safe: true},
      {input: 'data:video/x-matroska;base64,z\x3D', expected: 'data:video/x-matroska;base64,z\x3D', safe: true},
      {input: 'data:video/webm;base64   ,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/webm;foo\x3Dbar;base64,z\x3D', expected: 'data:video/webm;foo\x3Dbar;base64,z\x3D', safe: true},
      {input: 'data:video/webm;foo\x3D\"bar\";base64,z\x3D', expected: 'data:video/webm;foo\x3D\"bar\";base64,z\x3D', safe: true},
      {input: 'data:video/webm;codecs\x3D\"vp8,opus\";base64,z\x3D', expected: 'data:video/webm;codecs\x3D\"vp8,opus\";base64,z\x3D', safe: true},
      {input: 'data:video/webm;codecs\x3D\"vp8, opus\";base64,z\x3D', expected: 'data:video/webm;codecs\x3D\"vp8, opus\";base64,z\x3D', safe: true},
      {input: 'data:video/webm;codecs\x3Dvp8,opus;base64,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/webm;base64;with_subtype\x3Dfoo,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/webm;foo\x3Dbase64;with_subtype\x3Dfoo,z\x3D', expected: 'about:invalid#zClosurez', safe: false},
      {input: 'data:video/webm;base64\x3Dsomething;with_subtype\x3Dfoo,z\x3D', expected: 'about:invalid#zClosurez', safe: false}
];

goog.html.safeUrlTestVectors.TEL_VECTORS = [
    {input: 'tEl:+1(23)129-29192A.ABC#;eXt\x3D29', expected: 'tEl:+1(23)129-29192A.ABC#;eXt\x3D29', safe: true},
    {input: 'tEL:123;randmomparam\x3D123', expected: 'tEL:123;randmomparam\x3D123', safe: true},
    {input: ':', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'tell:', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'not-tel:+1', expected: 'about:invalid#zClosurez', safe: false},
    {input: ' tel:+1', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'javascript:evil()', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'tel:+1234567890', expected: 'tel:+1234567890', safe: true}
];

goog.html.safeUrlTestVectors.SMS_VECTORS = [
    {input: 'sms:+1234567890', expected: 'sms:+1234567890', safe: true},
    {input: 'sms:?body\x3Dmessage', expected: 'sms:?body\x3Dmessage', safe: true},
    {input: 'sms:?body\x3DHello, World!', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'sms:?body\x3Da\x26body\x3Db', expected: 'about:invalid#zClosurez', safe: false}
];

goog.html.safeUrlTestVectors.SSH_VECTORS = [
    {input: 'ssh://cloud.google.com', expected: 'ssh://cloud.google.com', safe: true},
    {input: '', expected: 'about:invalid#zClosurez', safe: false},
    {input: ':', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'ssh:cloud.google.com', expected: 'about:invalid#zClosurez', safe: false},
    {input: ' ssh://cloud.google.com', expected: 'about:invalid#zClosurez', safe: false},
    {input: 'javascript:evil()', expected: 'about:invalid#zClosurez', safe: false}
];
