//!! generated by clutz.
// Generated from third_party/closure/goog/html/safestylesheet.js
declare namespace ಠ_ಠ.clutz.goog.html {
  export import SafeStyleSheet = ಠ_ಠ.clutz.module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ;
}
// Generated from third_party/closure/goog/html/safestylesheet.js
declare module 'goog:goog.html.SafeStyleSheet' {
  import SafeStyleSheet = ಠ_ಠ.clutz.goog.html.SafeStyleSheet;
  export default SafeStyleSheet;
  const __clutz_actual_path: 'google3/third_party/closure/goog/html/safestylesheet';
}
declare module 'google3/third_party/closure/goog/html/safestylesheet' {
  import SafeStyleSheet = ಠ_ಠ.clutz.goog.html.SafeStyleSheet;
  export { SafeStyleSheet };
  const __clutz_strip_property: 'SafeStyleSheet';
  const __clutz_actual_namespace: 'goog.html.SafeStyleSheet';
}
// Generated from third_party/closure/goog/html/safestylesheet.js
declare namespace ಠ_ಠ.clutz {
  /**
   * A string-like object which represents a CSS style sheet and that carries the
   * security type contract that its value, as a string, will not cause untrusted
   * script execution (XSS) when evaluated as CSS in a browser.
   *
   * Instances of this type must be created via the factory method
   * `SafeStyleSheet.fromConstant` and not by invoking its constructor. The
   * constructor intentionally takes an extra parameter that cannot be constructed
   * outside of this file and the type is immutable; hence only a default instance
   * corresponding to the empty string can be obtained via constructor invocation.
   *
   * A SafeStyleSheet's string representation can safely be interpolated as the
   * content of a style element within HTML. The SafeStyleSheet string should
   * not be escaped before interpolation.
   *
   * Values of this type must be composable, i.e. for any two values
   * `styleSheet1` and `styleSheet2` of this type,
   * `SafeStyleSheet.unwrap(styleSheet1) + SafeStyleSheet.unwrap(styleSheet2)`
   * must itself be a value that satisfies the SafeStyleSheet type constraint.
   * This requirement implies that for any value `styleSheet` of this type,
   * `SafeStyleSheet.unwrap(styleSheet1)` must end in
   * "beginning of rule" context.
   *
   * A SafeStyleSheet can be constructed via security-reviewed unchecked
   * conversions. In this case producers of SafeStyleSheet must ensure themselves
   * that the SafeStyleSheet does not contain unsafe script. Note in particular
   * that `&lt;` is dangerous, even when inside CSS strings, and so should
   * always be forbidden or CSS-escaped in user controlled input. For example, if
   * `&lt;/style&gt;&lt;script&gt;evil&lt;/script&gt;"` were interpolated
   * inside a CSS string, it would break out of the context of the original
   * style element and `evil` would execute. Also note that within an HTML
   * style (raw text) element, HTML character references, such as
   * `&amp;lt;`, are not allowed. See
   * http://www.w3.org/TR/html5/scripting-1.html#restrictions-for-contents-of-script-elements
   * (similar considerations apply to the style element).
   */
  class module$contents$goog$html$SafeStyleSheet_SafeStyleSheet implements ಠ_ಠ.clutz.goog.string.TypedString {
    private noStructuralTyping_module$contents$goog$html$SafeStyleSheet_SafeStyleSheet : any;
    /**
     * A string-like object which represents a CSS style sheet and that carries the
     * security type contract that its value, as a string, will not cause untrusted
     * script execution (XSS) when evaluated as CSS in a browser.
     *
     * Instances of this type must be created via the factory method
     * `SafeStyleSheet.fromConstant` and not by invoking its constructor. The
     * constructor intentionally takes an extra parameter that cannot be constructed
     * outside of this file and the type is immutable; hence only a default instance
     * corresponding to the empty string can be obtained via constructor invocation.
     *
     * A SafeStyleSheet's string representation can safely be interpolated as the
     * content of a style element within HTML. The SafeStyleSheet string should
     * not be escaped before interpolation.
     *
     * Values of this type must be composable, i.e. for any two values
     * `styleSheet1` and `styleSheet2` of this type,
     * `SafeStyleSheet.unwrap(styleSheet1) + SafeStyleSheet.unwrap(styleSheet2)`
     * must itself be a value that satisfies the SafeStyleSheet type constraint.
     * This requirement implies that for any value `styleSheet` of this type,
     * `SafeStyleSheet.unwrap(styleSheet1)` must end in
     * "beginning of rule" context.
     *
     * A SafeStyleSheet can be constructed via security-reviewed unchecked
     * conversions. In this case producers of SafeStyleSheet must ensure themselves
     * that the SafeStyleSheet does not contain unsafe script. Note in particular
     * that `&lt;` is dangerous, even when inside CSS strings, and so should
     * always be forbidden or CSS-escaped in user controlled input. For example, if
     * `&lt;/style&gt;&lt;script&gt;evil&lt;/script&gt;"` were interpolated
     * inside a CSS string, it would break out of the context of the original
     * style element and `evil` would execute. Also note that within an HTML
     * style (raw text) element, HTML character references, such as
     * `&amp;lt;`, are not allowed. See
     * http://www.w3.org/TR/html5/scripting-1.html#restrictions-for-contents-of-script-elements
     * (similar considerations apply to the style element).
     */
    constructor (value : string , token : GlobalObject ) ;
    implementsGoogStringTypedString : boolean ;
    /**
     * Returns this SafeStyleSheet's value as a string.
     *
     * IMPORTANT: In code where it is security relevant that an object's type is
     * indeed `SafeStyleSheet`, use `SafeStyleSheet.unwrap`
     * instead of this method. If in doubt, assume that it's security relevant. In
     * particular, note that goog.html functions which return a goog.html type do
     * not guarantee the returned instance is of the right type. For example:
     *
     * <pre>
     * var fakeSafeHtml = new String('fake');
     * fakeSafeHtml.__proto__ = goog.html.SafeHtml.prototype;
     * var newSafeHtml = goog.html.SafeHtml.htmlEscape(fakeSafeHtml);
     * // newSafeHtml is just an alias for fakeSafeHtml, it's passed through by
     * // goog.html.SafeHtml.htmlEscape() as fakeSafeHtml
     * // instanceof goog.html.SafeHtml.
     * </pre>
     */
    getTypedStringValue ( ) : any ;
    /**
     * Returns a debug string-representation of this value.
     *
     * To obtain the actual string value wrapped in a SafeStyleSheet, use
     * `SafeStyleSheet.unwrap`.
     */
    toString ( ) : any ;
    /**
     * A SafeStyleSheet instance corresponding to the empty string.
     */
    static EMPTY : module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ;
    /**
     * Creates a new SafeStyleSheet object by concatenating values.
     * @param var_args Values to concatenate.
     */
    static concat ( ...var_args : ( module$contents$goog$html$SafeStyleSheet_SafeStyleSheet | module$contents$goog$html$SafeStyleSheet_SafeStyleSheet [] ) [] ) : module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ;
    /**
     * Creates a style sheet consisting of one selector and one style definition.
     * Use {@link SafeStyleSheet.concat} to create longer style sheets.
     * This function doesn't support @import, @media and similar constructs.
     * @param selector CSS selector, e.g. '#id' or 'tag .class, #id'. We support CSS3 selectors: https://w3.org/TR/css3-selectors/#selectors.
     * @param style Style definition associated with the selector.
     */
    static createRule (selector : string , style : ಠ_ಠ.clutz.goog.html.SafeStyle.PropertyMap | ಠ_ಠ.clutz.goog.html.SafeStyle ) : module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ;
    /**
     * Creates a SafeStyleSheet object from a compile-time constant string.
     *
     * `styleSheet` must not have any &lt; characters in it, so that
     * the syntactic structure of the surrounding HTML is not affected.
     * @param styleSheet A compile-time-constant string from which to create a SafeStyleSheet.
     */
    static fromConstant (styleSheet : ಠ_ಠ.clutz.goog.string.Const ) : module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ;
    /**
     * Performs a runtime check that the provided object is indeed a
     * SafeStyleSheet object, and returns its value.
     * @param safeStyleSheet The object to extract from.
     */
    static unwrap (safeStyleSheet : module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ) : string ;
  }
}
// Generated from third_party/closure/goog/html/safestylesheet.js
declare namespace ಠ_ಠ.clutz {
  export import module$exports$goog$html$SafeStyleSheet = ಠ_ಠ.clutz.module$contents$goog$html$SafeStyleSheet_SafeStyleSheet ;
}
