//!! generated by clutz.
// Generated from third_party/closure/goog/html/trustedtypes.js
declare namespace ಠ_ಠ.clutz.goog.html.trustedtypes {
}
// Generated from third_party/closure/goog/html/trustedtypes.js
declare module 'goog:goog.html.trustedtypes' {
  import trustedtypes = ಠ_ಠ.clutz.goog.html.trustedtypes;
  export = trustedtypes;
  const __clutz_actual_path: 'google3/third_party/closure/goog/html/trustedtypes';
}
declare module 'google3/third_party/closure/goog/html/trustedtypes' {
  import trustedtypes = ಠ_ಠ.clutz.goog.html.trustedtypes;
  export = trustedtypes;
  const __clutz_actual_namespace: 'goog.html.trustedtypes';
}
