//!! generated by clutz.
// Generated from third_party/closure/goog/html/uncheckedconversions.js
declare namespace ಠ_ಠ.clutz.goog.html.uncheckedconversions {
  /**
   * Performs an "unchecked conversion" to SafeHtml from a plain string that is
   * known to satisfy the SafeHtml type contract.
   *
   * IMPORTANT: Uses of this method must be carefully security-reviewed to ensure
   * that the value of `html` satisfies the SafeHtml type contract in all
   * possible program states.
   * @param justification A constant string explaining why this use of this method is safe. May include a security review ticket number.
   * @param html A string that is claimed to adhere to the SafeHtml contract.
   * @param opt_dir The optional directionality of the SafeHtml to be constructed. A null or undefined value signifies an unknown directionality.
   */
  function safeHtmlFromStringKnownToSatisfyTypeContract (justification : ಠ_ಠ.clutz.goog.string.Const , html : string , opt_dir ? : ಠ_ಠ.clutz.goog.i18n.bidi.Dir | null ) : ಠ_ಠ.clutz.goog.html.SafeHtml ;
  /**
   * Performs an "unchecked conversion" to SafeScript from a plain string that is
   * known to satisfy the SafeScript type contract.
   *
   * IMPORTANT: Uses of this method must be carefully security-reviewed to ensure
   * that the value of `script` satisfies the SafeScript type contract in
   * all possible program states.
   * @param justification A constant string explaining why this use of this method is safe. May include a security review ticket number.
   * @param script The string to wrap as a SafeScript.
   */
  function safeScriptFromStringKnownToSatisfyTypeContract (justification : ಠ_ಠ.clutz.goog.string.Const , script : string ) : ಠ_ಠ.clutz.goog.html.SafeScript ;
  /**
   * Performs an "unchecked conversion" to SafeStyle from a plain string that is
   * known to satisfy the SafeStyle type contract.
   *
   * IMPORTANT: Uses of this method must be carefully security-reviewed to ensure
   * that the value of `style` satisfies the SafeStyle type contract in all
   * possible program states.
   * @param justification A constant string explaining why this use of this method is safe. May include a security review ticket number.
   * @param style The string to wrap as a SafeStyle.
   */
  function safeStyleFromStringKnownToSatisfyTypeContract (justification : ಠ_ಠ.clutz.goog.string.Const , style : string ) : ಠ_ಠ.clutz.goog.html.SafeStyle ;
  /**
   * Performs an "unchecked conversion" to SafeStyleSheet from a plain string
   * that is known to satisfy the SafeStyleSheet type contract.
   *
   * IMPORTANT: Uses of this method must be carefully security-reviewed to ensure
   * that the value of `styleSheet` satisfies the SafeStyleSheet type
   * contract in all possible program states.
   * @param justification A constant string explaining why this use of this method is safe. May include a security review ticket number.
   * @param styleSheet The string to wrap as a SafeStyleSheet.
   */
  function safeStyleSheetFromStringKnownToSatisfyTypeContract (justification : ಠ_ಠ.clutz.goog.string.Const , styleSheet : string ) : ಠ_ಠ.clutz.goog.html.SafeStyleSheet ;
  /**
   * Performs an "unchecked conversion" to SafeUrl from a plain string that is
   * known to satisfy the SafeUrl type contract.
   *
   * IMPORTANT: Uses of this method must be carefully security-reviewed to ensure
   * that the value of `url` satisfies the SafeUrl type contract in all
   * possible program states.
   * @param justification A constant string explaining why this use of this method is safe. May include a security review ticket number.
   * @param url The string to wrap as a SafeUrl.
   */
  function safeUrlFromStringKnownToSatisfyTypeContract (justification : ಠ_ಠ.clutz.goog.string.Const , url : string ) : ಠ_ಠ.clutz.goog.html.SafeUrl ;
  /**
   * Performs an "unchecked conversion" to TrustedResourceUrl from a plain string
   * that is known to satisfy the TrustedResourceUrl type contract.
   *
   * IMPORTANT: Uses of this method must be carefully security-reviewed to ensure
   * that the value of `url` satisfies the TrustedResourceUrl type contract
   * in all possible program states.
   * @param justification A constant string explaining why this use of this method is safe. May include a security review ticket number.
   * @param url The string to wrap as a TrustedResourceUrl.
   */
  function trustedResourceUrlFromStringKnownToSatisfyTypeContract (justification : ಠ_ಠ.clutz.goog.string.Const , url : string ) : ಠ_ಠ.clutz.goog.html.TrustedResourceUrl ;
}
// Generated from third_party/closure/goog/html/uncheckedconversions.js
declare module 'goog:goog.html.uncheckedconversions' {
  import uncheckedconversions = ಠ_ಠ.clutz.goog.html.uncheckedconversions;
  export = uncheckedconversions;
  const __clutz_actual_path: 'google3/third_party/closure/goog/html/uncheckedconversions';
}
declare module 'google3/third_party/closure/goog/html/uncheckedconversions' {
  import uncheckedconversions = ಠ_ಠ.clutz.goog.html.uncheckedconversions;
  export = uncheckedconversions;
  const __clutz_actual_namespace: 'goog.html.uncheckedconversions';
}
