//!! generated by clutz.
// Generated from third_party/closure/goog/dom/asserts.js
declare namespace ಠ_ಠ.clutz.goog.dom.asserts {
  /**
   * Asserts that a given object is a HTMLAnchorElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not of type Location nor a subtype
   * of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlAnchorElement instead.
   */
  function assertIsHTMLAnchorElement (o : GlobalObject | null ) : HTMLAnchorElement ;
  /**
   * Asserts that a given object is a HTMLAudioElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlAudioElement instead.
   */
  function assertIsHTMLAudioElement (o : GlobalObject | null ) : HTMLAudioElement ;
  /**
   * Asserts that a given object is a HTMLButtonElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlButtonElement instead.
   */
  function assertIsHTMLButtonElement (o : GlobalObject | null ) : HTMLButtonElement ;
  /**
   * Asserts that a given object is a HTMLCanvasElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlCanvasElement instead.
   */
  function assertIsHTMLCanvasElement (o : GlobalObject | null ) : HTMLCanvasElement ;
  /**
   * Asserts that a given object is a HTMLEmbedElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlEmbedElement instead.
   */
  function assertIsHTMLEmbedElement (o : GlobalObject | null ) : HTMLEmbedElement ;
  /**
   * Asserts that a given object is a HTMLFormElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlFormElement instead.
   */
  function assertIsHTMLFormElement (o : GlobalObject | null ) : HTMLFormElement ;
  /**
   * Asserts that a given object is a HTMLFrameElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlFrameElement instead.
   */
  function assertIsHTMLFrameElement (o : GlobalObject | null ) : HTMLFrameElement ;
  /**
   * Asserts that a given object is a HTMLIFrameElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlIFrameElement instead.
   */
  function assertIsHTMLIFrameElement (o : GlobalObject | null ) : HTMLIFrameElement ;
  /**
   * Asserts that a given object is a HTMLImageElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlImageElement instead.
   */
  function assertIsHTMLImageElement (o : GlobalObject | null ) : HTMLImageElement ;
  /**
   * Asserts that a given object is a HTMLInputElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlInputElement instead.
   */
  function assertIsHTMLInputElement (o : GlobalObject | null ) : HTMLInputElement ;
  /**
   * Asserts that a given object is a HTMLLinkElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlLinkElement instead.
   */
  function assertIsHTMLLinkElement (o : GlobalObject | null ) : HTMLLinkElement ;
  /**
   * Asserts that a given object is a HTMLObjectElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlObjectElement instead.
   */
  function assertIsHTMLObjectElement (o : GlobalObject | null ) : HTMLObjectElement ;
  /**
   * Asserts that a given object is a HTMLScriptElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlScriptElement instead.
   */
  function assertIsHTMLScriptElement (o : GlobalObject | null ) : HTMLScriptElement ;
  /**
   * Asserts that a given object is a HTMLTextAreaElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlTextAreaElement instead.
   */
  function assertIsHTMLTextAreaElement (o : GlobalObject | null ) : HTMLTextAreaElement ;
  /**
   * Asserts that a given object is a HTMLVideoElement.
   *
   * To permit this assertion to pass in the context of tests where elements might
   * be mocked, also accepts objects that are not a subtype of Element.
   * @param o The object whose type to assert.
   * @deprecated Use goog.asserts.dom.assertIsHtmlVideoElement instead.
   */
  function assertIsHTMLVideoElement (o : GlobalObject | null ) : HTMLVideoElement ;
  /**
   * Asserts that a given object is a Location.
   *
   * To permit this assertion to pass in the context of tests where DOM APIs might
   * be mocked, also accepts any other type except for subtypes of {!Element}.
   * This is to ensure that, for instance, HTMLLinkElement is not being used in
   * place of a Location, since this could result in security bugs due to stronger
   * contracts required for assignments to the href property of the latter.
   * @param o The object whose type to assert.
   */
  function assertIsLocation (o : GlobalObject | null ) : Location ;
}
// Generated from third_party/closure/goog/dom/asserts.js
declare module 'goog:goog.dom.asserts' {
  import asserts = ಠ_ಠ.clutz.goog.dom.asserts;
  export = asserts;
  const __clutz_actual_path: 'google3/third_party/closure/goog/dom/asserts';
}
declare module 'google3/third_party/closure/goog/dom/asserts' {
  import asserts = ಠ_ಠ.clutz.goog.dom.asserts;
  export = asserts;
  const __clutz_actual_namespace: 'goog.dom.asserts';
}
