//!! generated by clutz.
// Generated from third_party/closure/goog/dom/inputtype.js
declare namespace ಠ_ಠ.clutz.goog.dom {
  /**
   * Enum of all input types (for INPUT, BUTTON, SELECT and TEXTAREA elements)
   * specified by the W3C HTML4.01 and HTML5 specifications.
   */
  /**
   * Enum of all input types (for INPUT, BUTTON, SELECT and TEXTAREA elements)
   * specified by the W3C HTML4.01 and HTML5 specifications.
   */
  enum InputType {
    BUTTON = 'button' ,
    CHECKBOX = 'checkbox' ,
    COLOR = 'color' ,
    DATE = 'date' ,
    DATETIME = 'datetime' ,
    DATETIME_LOCAL = 'datetime-local' ,
    EMAIL = 'email' ,
    FILE = 'file' ,
    HIDDEN = 'hidden' ,
    IMAGE = 'image' ,
    MENU = 'menu' ,
    MONTH = 'month' ,
    NUMBER = 'number' ,
    PASSWORD = 'password' ,
    RADIO = 'radio' ,
    RANGE = 'range' ,
    RESET = 'reset' ,
    SEARCH = 'search' ,
    SELECT_MULTIPLE = 'select-multiple' ,
    SELECT_ONE = 'select-one' ,
    SUBMIT = 'submit' ,
    TEL = 'tel' ,
    TEXT = 'text' ,
    TEXTAREA = 'textarea' ,
    TIME = 'time' ,
    URL = 'url' ,
    WEEK = 'week' ,
  }
}
// Generated from third_party/closure/goog/dom/inputtype.js
declare module 'goog:goog.dom.InputType' {
  import InputType = ಠ_ಠ.clutz.goog.dom.InputType;
  export default InputType;
  const __clutz_actual_path: 'google3/third_party/closure/goog/dom/inputtype';
}
declare module 'google3/third_party/closure/goog/dom/inputtype' {
  import InputType = ಠ_ಠ.clutz.goog.dom.InputType;
  export { InputType };
  const __clutz_strip_property: 'InputType';
  const __clutz_actual_namespace: 'goog.dom.InputType';
}
