//!! generated by clutz.
// Generated from third_party/closure/goog/dom/vendor.js
declare namespace ಠ_ಠ.clutz.goog.dom.vendor {
  function getPrefixedEventType (eventType : string ) : string ;
  function getPrefixedPropertyName (propertyName : string , opt_object ? : GlobalObject ) : string | null ;
  /**
   * Returns the JS vendor prefix used in CSS properties. Different vendors
   * use different methods of changing the case of the property names.
   */
  function getVendorJsPrefix ( ) : string | null ;
  /**
   * Returns the vendor prefix used in CSS properties.
   */
  function getVendorPrefix ( ) : string | null ;
}
// Generated from third_party/closure/goog/dom/vendor.js
declare module 'goog:goog.dom.vendor' {
  import vendor = ಠ_ಠ.clutz.goog.dom.vendor;
  export = vendor;
  const __clutz_actual_path: 'google3/third_party/closure/goog/dom/vendor';
}
declare module 'google3/third_party/closure/goog/dom/vendor' {
  import vendor = ಠ_ಠ.clutz.goog.dom.vendor;
  export = vendor;
  const __clutz_actual_namespace: 'goog.dom.vendor';
}
