// Copyright 2017 The Closure Library Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an AS-IS BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file has been auto-generated by MakeJsDeps, please do not edit.

goog.addDependency('debug_loader_integration_tests/testdata/googmodule.js', ['test.js.GoogModule'], [], {'module': 'goog'});
goog.addDependency('debug_loader_integration_tests/testdata/googmoduledln.js', ['test.js.GoogModuleDLN'], [], {'module': 'goog'});
goog.addDependency('debug_loader_integration_tests/testdata/googmodulerequiresgoogmodule.js', ['test.js.GoogModuleRequiresGoogModule'], ['test.js.GoogModule'], {'module': 'goog'});
goog.addDependency('debug_loader_integration_tests/testdata/googmodulerequiresprovide.js', ['test.js.GoogModuleRequiresProvide'], ['test.js.Provide'], {'module': 'goog'});
goog.addDependency('debug_loader_integration_tests/testdata/provide.js', ['test.js.Provide'], []);
goog.addDependency('debug_loader_integration_tests/testdata/providerequiresprovide.js', ['test.js.ProvideRequiresProvide'], ['test.js.Provide']);
goog.addDependency('debug_loader_integration_tests/testdata/providrequiresgoogmoduledln.js', ['test.js.ProvideRequiresGoogModuleDLN'], ['test.js.GoogModuleDLN']);
goog.addDependency('debug_loader_integration_tests/testdata/providrequiresgoogmoduleget.js', ['test.js.ProvideRequiresGoogModuleGet'], ['test.js.GoogModule']);
goog.addDependency('debug_loader_integration_tests/testdata/testutils.js', [], []);