(function(){var l,n=this;
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==q(a)}function aa(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function ba(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var da="closure_uid_"+(1E9*Math.random()>>>0),ea=0;function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return u.apply(null,arguments)}var x=Date.now||function(){return+new Date};
function y(a,b){function c(){}c.prototype=b.prototype;a.fa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ya=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var ha;function z(){0!=ia&&(this[da]||(this[da]=++ea));this.W=this.W;this.ua=this.ua}var ia=0;z.prototype.W=!1;var ja;function A(a,b){this.type=a;this.b=this.target=b;this.c=!1;this.da=!0}A.prototype.stopPropagation=function(){this.c=!0};A.prototype.preventDefault=function(){this.da=!1};var ka="closure_listenable_"+(1E6*Math.random()|0),la=0;function ma(a,b,c,d,e){this.r=a;this.a=null;this.src=b;this.type=c;this.D=!!d;this.F=e;this.T=++la;this.w=this.C=!1}function na(a){a.w=!0;a.r=null;a.a=null;a.src=null;a.F=null};function B(a,b){this.width=a;this.height=b}B.prototype.clone=function(){return new B(this.width,this.height)};B.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};B.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};B.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function oa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var pa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function qa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<pa.length;f++)c=pa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function ra(a){ra[" "](a);return a}ra[" "]=function(){};function sa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ta=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function ua(a){if(!va.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(wa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(za,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Aa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ba,"&#0;"));return a}var wa=/&/g,xa=/</g,ya=/>/g,za=/"/g,Aa=/'/g,Ba=/\x00/g,va=/[\x00&<>"']/;
function Ca(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function Da(a,b){return a<b?-1:a>b?1:0};var C=Array.prototype,Ea=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},D=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Fa=C.filter?function(a,b,c){return C.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e};function Ga(a,b){var c;a:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]}function Ha(a,b){var c=Ea(a,b),d;(d=0<=c)&&C.splice.call(a,c,1);return d}function Ia(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Ja(a,b,c){return 2>=arguments.length?C.slice.call(a,b):C.slice.call(a,b,c)};var Ka={};
function La(a,b,c,d){var e=document.createElement("li"),f=document.createElement("a");f.href=b+a.b.href;f.textContent=a.getKey();a.b.interface&&f.classList.add("interface");var g=a.v();if(g){var h=document.createElement("input");h.type="checkbox";h.id=d+a.getKey();e.appendChild(h);d=document.createElement("label");d.setAttribute("for",h.id);d.appendChild(f);a.b.href===c&&d.classList.add("current");e.appendChild(d);var k=document.createElement("ul");k.classList.add("nav-tree");e.appendChild(k);g.forEach(function(a){k.appendChild(La(a,
b,c,h.id+"."))})}else a.b.href===c&&f.classList.add("current"),e.appendChild(f);return e}function Ma(a){if(a=a.v())a.sort(function(a,c){return a.getKey()<c.getKey()?-1:a.getKey()>c.getKey()?1:0}),a.forEach(Ma)}
function Na(a){var b=a.v();b&&(b.forEach(Na),b.filter(function(a){return null===a.b}).forEach(function(b){a.removeChild(b);var d=Oa(b);d&&d.forEach(function(d){var f=b.getKey()+"."+d.getKey();d.d=f;Pa(a,d)})}),b.filter(function(a){return a.b&&!a.b.namespace&&!a.b.types&&(a.a?a.a.length:0)}).forEach(function(b){var d=Oa(b);d&&d.forEach(function(d){var f=b.getKey()+"."+d.getKey();d.d=f;Pa(a,d)})}))}function E(a,b){this.d=a;this.b=b;this.a=this.c=null}E.prototype.getKey=function(){return this.d};
E.prototype.K=function(a){this.b=a};function Pa(a,b){a.a||(a.a=[]);b.c=a;a.a.push(b)}E.prototype.v=function(){return this.a};E.prototype.removeChild=function(a){a.c=null;Ha(this.a,a)};function Oa(a){var b=a.a;a.a&&(a.a.forEach(function(a){a.c=null}),a.a=null);return b}function Qa(a,b){return a.a?Ga(a.a,function(a){return a.d===b}):null}
Ka.S=function(a,b){var c=new E("",null);a.forEach(function(a){if(b){var e;a.types?(e=Ka.S(a.types,!1),e.d=a.name,e.K(a)):e=new E(a.name,a);Pa(c,e)}else{var f=c;a.name.split(/\./).forEach(function(a){var b=Qa(f,a);b||(b=new E(a,null),Pa(f,b));f=b});f.K(a)}});Na(c);Ma(c);return c};Ka.R=function(a,b,c){var d=Ra;d&&!sa(d,"/")&&(d+="/");a=Ka.S(a,c);var e=document.createElement("ul");a.v()&&a.v().forEach(function(a){e.appendChild(La(a,d,b,c?".nav-module:":".nav:"))});return e};function Sa(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]}function Ta(a,b){var c;a.classList?c=a.classList.contains(b):(c=Sa(a),c=0<=Ea(c,b));return c}function Ua(a,b){a.classList?a.classList.add(b):Ta(a,b)||(a.className+=0<a.className.length?" "+b:b)}function Va(a,b){if(a.classList)D(b,function(b){Ua(a,b)});else{var c={};D(Sa(a),function(a){c[a]=!0});D(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function Wa(a,b){a.classList?a.classList.remove(b):Ta(a,b)&&(a.className=Fa(Sa(a),function(a){return a!=b}).join(" "))}function Xa(a){var b=["ac-active","active"];a.classList?D(b,function(b){Wa(a,b)}):a.className=Fa(Sa(a),function(a){return!(0<=Ea(b,a))}).join(" ")};function Ya(a){this.src=a;this.a={};this.b=0}Ya.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Za(a,b,d,e);-1<g?(b=a[g],c||(b.C=!1)):(b=new ma(b,this.src,f,!!d,e),b.C=c,a.push(b));return b};Ya.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Za(e,b,c,d);return-1<b?(na(e[b]),C.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function $a(a,b){var c=b.type;if(!(c in a.a))return!1;var d=Ha(a.a[c],b);d&&(na(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d}function ab(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Za(a,c,d,e));return-1<b?a[b]:null}function Za(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.w&&f.r==b&&f.D==!!c&&f.F==d)return e}return-1};var bb;a:{var cb=n.navigator;if(cb){var db=cb.userAgent;if(db){bb=db;break a}}bb=""}function F(a){return-1!=bb.indexOf(a)};function eb(){return F("Opera")||F("OPR")}function fb(){return F("Edge")||F("Trident")||F("MSIE")}function gb(){return(F("Chrome")||F("CriOS"))&&!eb()&&!fb()};function G(){return F("Edge")};function H(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}H.prototype.clone=function(){return new H(this.x,this.y)};function hb(a,b){return new H(a.x-b.x,a.y-b.y)}H.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};H.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};H.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function I(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=I.prototype;l.clone=function(){return new I(this.top,this.right,this.bottom,this.left)};l.contains=function(a){return this&&a?a instanceof I?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function ib(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}l=ib.prototype;l.clone=function(){return new ib(this.left,this.top,this.width,this.height)};l.contains=function(a){return a instanceof ib?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
l.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function jb(a){this.a=a||[]}function kb(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=c[e],g=a.toLowerCase(),h=String(f).toLowerCase(),k=0;if(-1!=h.indexOf(g))k=parseInt((h.indexOf(g)/4).toString(),10);else for(var m=g.split(""),p=-1,v=10,w=0,ca;ca=m[w];w++)ca=h.indexOf(ca),ca>p?(p=ca-p-1,p>v-5&&(p=v-5),k+=p,p=ca):(k+=v,v+=5);k<6*g.length&&d.push({ta:f,ea:k,index:e})}d.sort(function(a,b){var c=a.ea-b.ea;return 0!=c?c:a.index-b.index});a=[];for(w=0;w<b&&w<d.length;w++)a.push(d[w].ta);return a};function J(){}J.a=function(){return J.b?J.b:J.b=new J};J.prototype.a=0;var lb=eb(),K=fb(),L=F("Gecko")&&!(-1!=bb.toLowerCase().indexOf("webkit")&&!G())&&!(F("Trident")||F("MSIE"))&&!G(),M=-1!=bb.toLowerCase().indexOf("webkit")&&!G(),mb=F("Macintosh");function nb(){var a=bb;if(L)return/rv\:([^\);]+)(\)|;)/.exec(a);if(K&&G())return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(M)return/WebKit\/(\S+)/.exec(a)}function ob(){var a=n.document;return a?a.documentMode:void 0}
var pb=function(){if(lb&&n.opera){var a=n.opera.version;return"function"==q(a)?a():a}var a="",b=nb();b&&(a=b?b[1]:"");return K&&!G()&&(b=ob(),b>parseFloat(a))?String(b):a}(),qb={};
function N(a){var b;if(!(b=qb[a])){b=0;for(var c=ta(String(pb)).split("."),d=ta(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=/(\d*)(\D*)/g,m=/(\d*)(\D*)/g;do{var p=k.exec(g)||["","",""],v=m.exec(h)||["","",""];if(0==p[0].length&&0==v[0].length)break;b=Da(0==p[1].length?0:parseInt(p[1],10),0==v[1].length?0:parseInt(v[1],10))||Da(0==p[2].length,0==v[2].length)||Da(p[2],v[2])}while(0==b)}b=qb[a]=0<=b}return b}
function O(a){return K&&(G()||rb>=a)}var sb=n.document,tb=ob(),rb=!sb||!K||!tb&&G()?void 0:tb||("CSS1Compat"==sb.compatMode?parseInt(pb,10):5);var ub=!K||O(9),vb=!L&&!K||K&&O(9)||L&&N("1.9.1");K&&N("9");function P(a){return a?new wb(Q(a)):ja||(ja=new wb)}function xb(a){var b=document;return t(a)?b.getElementById(a):a}function yb(a,b){oa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in zb?a.setAttribute(zb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var zb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Ab(a){var b=Bb(a);a=Cb(a);return K&&N("10")&&a.pageYOffset!=b.scrollTop?new H(b.scrollLeft,b.scrollTop):new H(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}
function Bb(a){return M||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Cb(a){return a.parentWindow||a.defaultView}function Db(a,b,c){function d(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!aa(f)||ba(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ba(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==q(f)){g="function"==typeof f.item;break a}}g=!1}D(g?Ia(f):f,d)}}}
function Eb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Fb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function wb(a){this.a=a||n.document||document}
wb.prototype.b=function(a,b,c){var d=this.a,e=arguments,f=e[0],g=e[1];if(!ub&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ua(g.name),'"');if(g.type){f.push(' type="',ua(g.type),'"');var h={};qa(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=d.createElement(f);g&&(t(g)?f.className=g:r(g)?f.className=g.join(" "):yb(f,g));2<e.length&&Db(d,f,e);return f};function Gb(a){return"CSS1Compat"==a.a.compatMode}wb.prototype.d=Eb;
wb.prototype.v=function(a){return vb&&void 0!=a.children?a.children:Fa(a.childNodes,function(a){return 1==a.nodeType})};wb.prototype.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Hb(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function Ib(a,b,c){r(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(ha||(ha={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=ha,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Jb(a,b){var c="";b&&(c=b.id);Ib(a,"activedescendant",c)};function Kb(a){var b=0,c=0;if(Lb(a))b=a.selectionStart,c=-1;else if(K){var d=Mb(a),e=d[0],d=d[1];if(e.inRange(d)){e.setEndPoint("EndToStart",d);if("textarea"==a.type){d.duplicate();b=a=e.text;for(c=!1;!c;)0==e.compareEndPoints("StartToEnd",e)?c=!0:(e.moveEnd("character",-1),e.text==a?b+="\r\n":c=!0);e=[b.length,-1];return e}b=e.text.length;c=-1}}return[b,c]}
function Mb(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function Nb(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function Lb(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};var Ob=!K||O(9),Pb=K&&!N("9");!M||N("528");L&&N("1.9b")||K&&N("8")||lb&&N("9.5")||M&&N("528");L&&!N("8")||K&&N("9");function R(a,b){A.call(this,a?a.type:"");this.b=this.target=null;this.f=this.a=this.screenY=this.screenX=this.clientY=this.clientX=0;this.i=this.g=this.d=this.j=!1;this.h=this.state=null;if(a){var c=this.type=a.type,d=null;if("touchstart"==c||"touchmove"==c)d=a.targetTouches[0];else if("touchend"==c||"touchcancel"==c)d=a.changedTouches[0];this.target=null===d?a.target||a.srcElement:d.target;this.b=b;var e=a.relatedTarget;if(e&&L)try{ra(e.nodeName)}catch(f){}null===d?(this.clientX=void 0!==a.clientX?
a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.a=a.keyCode||0;this.f=a.charCode||("keypress"==c?a.keyCode:0);this.j=a.ctrlKey;this.d=a.altKey;this.g=a.shiftKey;this.i=a.metaKey;this.state=a.state;this.h=a;a.defaultPrevented&&this.preventDefault()}}y(R,A);
R.prototype.stopPropagation=function(){R.fa.stopPropagation.call(this);this.h.stopPropagation?this.h.stopPropagation():this.h.cancelBubble=!0};R.prototype.preventDefault=function(){R.fa.preventDefault.call(this);var a=this.h;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Pb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Qb="closure_lm_"+(1E6*Math.random()|0),Rb={},Sb=0;function S(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)S(a,b[f],c,d,e);return null}c=Tb(c);if(a&&a[ka])a=a.d(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=Ub(a);g||(a[Qb]=g=new Ya(a));c=g.add(b,c,!1,d,e);c.a||(d=Vb(),c.a=d,d.src=a,d.r=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Wb(b.toString()),d),Sb++);a=c}return a}
function Vb(){var a=Xb,b=Ob?function(c){return a.call(b.src,b.r,c)}:function(c){c=a.call(b.src,b.r,c);if(!c)return c};return b}function Yb(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Yb(a,b[f],c,d,e);else c=Tb(c),a&&a[ka]?a.h(b,c,d,e):a&&(a=Ub(a))&&(b=ab(a,b,c,!!d,e))&&T(b)}
function T(a){if("number"==typeof a||!a||a.w)return!1;var b=a.src;if(b&&b[ka])return $a(b.u,a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.D):b.detachEvent&&b.detachEvent(Wb(c),d);Sb--;(c=Ub(b))?($a(c,a),0==c.b&&(c.src=null,b[Qb]=null)):na(a);return!0}function Wb(a){return a in Rb?Rb[a]:Rb[a]="on"+a}function Zb(a,b,c,d){var e=!0;if(a=Ub(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.D==c&&!f.w&&(f=$b(f,d),e=e&&!1!==f)}return e}
function $b(a,b){var c=a.r,d=a.F||a.src;a.C&&T(a);return c.call(d,b)}
function Xb(a,b){if(a.w)return!0;if(!Ob){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new R(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;!c.c&&0<=h;h--){c.b=e[h];var k=Zb(e[h],f,!0,c),d=d&&k}for(h=0;!c.c&&h<e.length;h++)c.b=e[h],k=Zb(e[h],
f,!1,c),d=d&&k}return d}return $b(a,new R(b,this))}function Ub(a){a=a[Qb];return a instanceof Ya?a:null}var ac="__closure_events_fn_"+(1E9*Math.random()>>>0);function Tb(a){if("function"==q(a))return a;a[ac]||(a[ac]=function(b){return a.handleEvent(b)});return a[ac]};function bc(a){z.call(this);this.b=a;this.a={}}y(bc,z);var cc=[];bc.prototype.d=function(a,b,c,d){r(b)||(b&&(cc[0]=b.toString()),b=cc);for(var e=0;e<b.length;e++){var f=S(a,b[e],c||this.handleEvent,d||!1,this.b||this);if(!f)break;this.a[f.T]=f}return this};
bc.prototype.h=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.h(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.b||this,c=Tb(c),d=!!d,b=a&&a[ka]?ab(a.u,String(b),c,d,e):a?(a=Ub(a))?ab(a,b,c,d,e):null:null,b&&(T(b),delete this.a[b.T]);return this};bc.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function U(){z.call(this);this.u=new Ya(this);this.qa=this;this.I=null}y(U,z);U.prototype[ka]=!0;U.prototype.addEventListener=function(a,b,c,d){S(this,a,b,c,d)};U.prototype.removeEventListener=function(a,b,c,d){Yb(this,a,b,c,d)};
function V(a,b){var c,d=a.I;if(d)for(c=[];d;d=d.I)c.push(d);var d=a.qa,e=b,f=e.type||e;if(t(e))e=new A(e,d);else if(e instanceof A)e.target=e.target||d;else{var g=e,e=new A(f,d);qa(e,g)}var g=!0,h;if(c)for(var k=c.length-1;!e.c&&0<=k;k--)h=e.b=c[k],g=dc(h,f,!0,e)&&g;e.c||(h=e.b=d,g=dc(h,f,!0,e)&&g,e.c||(g=dc(h,f,!1,e)&&g));if(c)for(k=0;!e.c&&k<c.length;k++)h=e.b=c[k],g=dc(h,f,!1,e)&&g;return g}U.prototype.d=function(a,b,c,d){return this.u.add(String(a),b,!1,c,d)};
U.prototype.h=function(a,b,c,d){return this.u.remove(String(a),b,c,d)};function dc(a,b,c,d){b=a.u.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.w&&g.D==c){var h=g.r,k=g.F||g.src;g.C&&$a(a.u,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.da};function ec(a,b,c,d,e){if(!(K||M&&N("525")))return!0;if(mb&&e)return fc(a);if(e&&!d)return!1;"number"==typeof b&&(b=gc(b));if(!c&&(17==b||18==b||mb&&91==b))return!1;if(M&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(K&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!M}return fc(a)}
function fc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||M&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function gc(a){if(L)a=hc(a);else if(mb&&M)a:switch(a){case 93:a=91;break a}return a}
function hc(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function ic(a,b){U.call(this);a&&jc(this,a,b)}y(ic,U);l=ic.prototype;l.A=null;l.G=null;l.N=null;l.H=null;l.l=-1;l.o=-1;l.L=!1;
var kc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},lc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},mc=K||M&&N("525"),nc=mb&&L;
ic.prototype.a=function(a){M&&(17==this.l&&!a.j||18==this.l&&!a.d||mb&&91==this.l&&!a.i)&&(this.o=this.l=-1);-1==this.l&&(a.j&&17!=a.a?this.l=17:a.d&&18!=a.a?this.l=18:a.i&&91!=a.a&&(this.l=91));mc&&!ec(a.a,this.l,a.g,a.j,a.d)?this.handleEvent(a):(this.o=gc(a.a),nc&&(this.L=a.d))};ic.prototype.b=function(a){this.o=this.l=-1;this.L=a.d};
ic.prototype.handleEvent=function(a){var b=a.h,c,d,e=b.altKey;K&&"keypress"==a.type?(c=this.o,d=13!=c&&27!=c?b.keyCode:0):M&&"keypress"==a.type?(c=this.o,d=0<=b.charCode&&63232>b.charCode&&fc(c)?b.charCode:0):lb?(c=this.o,d=fc(c)?b.keyCode:0):(c=b.keyCode||this.o,d=b.charCode||0,nc&&(e=this.L),mb&&63==d&&224==c&&(c=191));var f=c=gc(c),g=b.keyIdentifier;c?63232<=c&&c in kc?f=kc[c]:25==c&&a.g&&(f=9):g&&g in lc&&(f=lc[g]);this.l=f;a=new oc(f,d,0,b);a.d=e;V(this,a)};
function jc(a,b,c){a.H&&pc(a);a.A=b;a.G=S(a.A,"keypress",a,c);a.N=S(a.A,"keydown",a.a,c,a);a.H=S(a.A,"keyup",a.b,c,a)}function pc(a){a.G&&(T(a.G),T(a.N),T(a.H),a.G=null,a.N=null,a.H=null);a.A=null;a.l=-1;a.o=-1}function oc(a,b,c,d){R.call(this,d);this.type="key";this.a=a;this.f=b}y(oc,R);function W(a,b){var c=Q(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function X(a,b){return W(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function qc(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}K&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function rc(a){if(K&&!O(8))return a.offsetParent;var b=Q(a),c=X(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=X(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function sc(a){for(var b=new I(0,Infinity,Infinity,0),c=P(a),d=c.a.body,e=c.a.documentElement,f=Bb(c.a);a=rc(a);)if(!(K&&0==a.clientWidth||M&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=X(a,"overflow")){var g=Y(a),h=new H(a.clientLeft,a.clientTop);g.x+=h.x;g.y+=h.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(Cb(c.a)||
window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new B(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}function Y(a){var b=Q(a),c=new H(0,0),d;d=b?Q(b):document;d=!K||O(9)||Gb(P(d))?d.documentElement:d.body;if(a==d)return c;a=qc(a);b=P(b);b=Ab(b.a);c.x=a.left+b.x;c.y=a.top+b.y;return c}function tc(a){"number"==typeof a&&(a=a+"px");return a}
function uc(a){var b=vc;if("none"!=X(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function vc(a){var b=a.offsetWidth,c=a.offsetHeight,d=M&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=qc(a),new B(a.right-a.left,a.bottom-a.top)):new B(b,c)}var wc=L?"MozUserSelect":M?"WebkitUserSelect":null;
function xc(a){var b=a.getElementsByTagName("*");if(wc){var c="none";a.style[wc]=c;if(b){a=0;for(var d;d=b[a];a++)d.style[wc]=c}}else if(K||lb)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function yc(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e}
function zc(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?yc(a,c):0}var Ac={thin:2,medium:4,thick:6};function Bc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in Ac?Ac[c]:yc(a,c)}
function Cc(a){if(K&&!O(9)){var b=Bc(a,"borderLeft"),c=Bc(a,"borderRight"),d=Bc(a,"borderTop");a=Bc(a,"borderBottom");return new I(d,c,a,b)}b=W(a,"borderLeftWidth");c=W(a,"borderRightWidth");d=W(a,"borderTopWidth");a=W(a,"borderBottomWidth");return new I(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function Dc(a,b){return(b&4&&"rtl"==X(a,"direction")?b^2:b)&-5};function Ec(a,b){U.call(this);this.c=a||1;this.b=b||n;this.g=u(this.k,this);this.i=x()}y(Ec,U);Ec.prototype.f=!1;Ec.prototype.a=null;Ec.prototype.k=function(){if(this.f){var a=x()-this.i;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.g,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),V(this,Fc),this.f&&(this.a=this.b.setTimeout(this.g,this.c),this.i=x()))}};var Fc="tick";function Gc(a,b,c){U.call(this);this.n=a;this.B=c;this.c=b;S(b,[Hc,Ic,Jc,Kc],this.handleEvent,!1,this);this.i=null;this.b=[];this.f=-1;this.a=0;this.g=this.k=null;this.J={}}y(Gc,U);Gc.prototype.s=10;var Hc="hilite",Ic="select",Kc="dismiss",Jc="canceldismiss";l=Gc.prototype;
l.handleEvent=function(a){var b=this.n;if(a.target==this.c)switch(a.type){case Hc:this.q(a.t);break;case Ic:var c=!1;if("number"==typeof a.t){a=a.t;var d=this.b[Lc(this,a)],c=!!d&&b.M&&b.M(d);d&&!c&&this.f!=a&&this.q(a)}c||Mc(this);break;case Jc:Nc(this);break;case Kc:Oc(this)}};function Pc(a){for(var b=a.a+a.b.length-1,c=a.f,d=0;d<a.b.length;d++){if(c>=a.a&&c<b)c++;else if(-1==c)c=a.a;else break;if(a.q(c))break}}
l.q=function(a){var b=Lc(this,a),c=this.b[b];return c&&this.n.M&&this.n.M(c)?!1:(this.f=a,this.c.q(a),-1!=b)};
function Mc(a){var b=Lc(a,a.f);if(-1!=b){var c=a.b[b],d=a.B;if(d.e){var e=c.toString();if(d.c){var f=Qc(d,d.e.value,Kb(d.e)[0]),g=Rc(d,d.e.value);d.I.test(e)||(e=e.replace(/[\s\xa0]+$/,"")+d.n);0==f||/^[\s\xa0]*$/.test(g[f-1])||(e=" "+e);f==g.length-1&&(e+=" ");if(e!=g[f]){g[f]=e;e=d.e;(L||K&&N("9"))&&e.blur();e.value=g.join("");for(var h=0,k=0;k<=f;k++)h+=g[k].length;e.focus();f=h;g=d.e;e=f;Lb(g)?g.selectionStart=e:K&&(h=Mb(g),k=h[0],k.inRange(h[1])&&(e=Nb(g,e),k.collapse(!0),k.move("character",
e),k.select()));g=d.e;Lb(g)?g.selectionEnd=f:K&&(h=Mb(g),e=h[1],h[0].inRange(e)&&(f=Nb(g,f),g=Nb(g,Kb(g)[0]),e.collapse(!0),e.moveEnd("character",f-g),e.select()))}}else d.K(e);d.Q=!0}a.m();V(a,{type:"update",t:c,index:b});return!0}a.m();V(a,{type:"update",t:null,index:null});return!1}l.m=function(){this.f=-1;this.i=null;this.a+=this.b.length;this.b=[];window.clearTimeout(this.g);this.g=null;this.c.m();V(this,"suggestionsupdate");V(this,Kc)};
function Oc(a){a.g||(a.g=window.setTimeout(u(a.m,a),100))}l.V=function(){return this.g?(window.clearTimeout(this.g),this.g=null,!0):!1};function Nc(a){a.V()||window.setTimeout(u(a.V,a),10)}l.oa=function(a,b,c){this.i==a&&this.P(b,c)};
l.P=function(a,b){var c="object"==q(b)&&b,d=(c?c.za():b)?Lc(this,this.f):-1;this.a+=this.b.length;this.b=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.a+f,data:a[f]});f=null;if(this.k){var f=this.J,g;g=this.k;g=g[da]||(g[da]=++ea);f=f[g]||this.k}this.c.ra=f;this.c.P(e,this.i,this.k);f=!0;c&&void 0!==c.ha()&&(f=c.ha());this.f=-1;(f||0<=d)&&0!=e.length&&this.i&&(0<=d?this.q(this.a+d):Pc(this));V(this,"suggestionsupdate")};function Lc(a,b){var c=b-a.a;return 0>c||c>=a.b.length?-1:c}l.update=function(a){this.B.update(a)};function Sc(a,b,c,d){U.call(this);this.n=a||document.body;this.g=P(this.n);this.va=!a;this.b=null;this.s="";this.c=[];this.f=[];this.B=this.k=-1;this.j=!1;this.className="ac-renderer";this.sa="ac-highlighted";this.i=b||null;this.xa=null!=d?d:!0;this.wa=!!c}y(Sc,U);l=Sc.prototype;l.P=function(a,b,c){this.s=b;this.c=a;this.k=-1;this.B=x();this.a=c;this.f=[];Tc(this)};l.m=function(){this.a&&Jb(this.a,null);this.j&&(this.j=!1,this.a&&Ib(this.a,"haspopup",!1),this.b.style.display="none")};
function Uc(a){a.j||(a.j=!0,a.a&&(Hb(a.a,"combobox"),Ib(a.a,"autocomplete","list"),Ib(a.a,"haspopup",!0)),a.b.style.display="")}
function Vc(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.f.length?a.f[b]:void 0;if(V(a,{type:"rowhilite",Ca:d,t:c?c.data:null})&&(0<=a.k&&Xa(a.f[a.k]),a.k=b,d)){Va(d,["ac-active","active"]);a.a&&Jb(a.a,d);var c=a.b,e,f=Y(d);e=Y(c);var g=Cc(c),h=f.x-e.x-g.left,f=f.y-e.y-g.top,k=c.clientWidth-d.offsetWidth,d=c.clientHeight-d.offsetHeight,m=c.scrollLeft,p=c.scrollTop;if(c==document.body||c==document.documentElement)m=e.x+g.left,p=e.y+g.top,K&&!O(10)&&(m+=g.left,p+=g.top);m+=Math.min(h,Math.max(h-
k,0));p+=Math.min(f,Math.max(f-d,0));e=new H(m,p);c.scrollLeft=e.x;c.scrollTop=e.y}}l.q=function(a){if(-1==a)Vc(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){Vc(this,b);break}};function Wc(a){if(!a.b){var b=a.g.b("DIV",{style:"display:none"});a.b=b;Va(b,ta(a.className).split(" "));Hb(b,"listbox");b.id=":"+(J.a().a++).toString(36);a.n.appendChild(b);S(b,"click",a.ka,!1,a);S(b,"mousedown",a.ma,!1,a);S(b,"mouseover",a.na,!1,a)}}
function Tc(a){Wc(a);a.ga&&(a.b.style.minWidth=a.ga.clientWidth+"px");a.f.length=0;a.g.d(a.b);a.i&&a.i.Aa||D(a.c,function(a){var c=a;a=this.s;var d=this.g.b("DIV",{className:"ac-row",id:":"+(J.a().a++).toString(36)});Hb(d,"option");if(!this.i||!this.i.Ba)if(c=c.data.toString(),"textContent"in d)d.textContent=c;else if(3==d.nodeType)d.data=c;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=c}else Eb(d),d.appendChild(Q(d).createTextNode(String(c)));
a&&this.xa&&(this.J=!1,Xc(this,d,a));Ua(d,"ac-row");this.f.push(d);this.b.appendChild(d)},a);0==a.c.length?a.m():(Uc(a),Yc(a),xc(a.b))}
function Yc(a){if(a.a&&a.va){var b=a.ra||a.a,c;c=a.wa?3:1;a=a.b;var d=c^1,e,f;if(e=a.offsetParent){var g="HTML"==e.tagName||"BODY"==e.tagName;g&&"static"==X(e,"position")||(f=Y(e),g||(g=(g="rtl"==X(e,"direction"))&&L?-e.scrollLeft:!g||K&&N("8")||"visible"==X(e,"overflowX")?e.scrollLeft:e.scrollWidth-e.clientWidth-e.scrollLeft,f=hb(f,new H(g,e.scrollTop))))}e=f||new H;f=Y(b);g=uc(b);f=new ib(f.x,f.y,g.width,g.height);if(g=sc(b)){var h=new ib(g.left,g.top,g.right-g.left,g.bottom-g.top),g=Math.max(f.left,
h.left),k=Math.min(f.left+f.width,h.left+h.width);if(g<=k){var m=Math.max(f.top,h.top),h=Math.min(f.top+f.height,h.top+h.height);m<=h&&(f.left=g,f.top=m,f.width=k-g,f.height=h-m)}}g=P(b);m=P(a);if(g.a!=m.a){var k=g.a.body,m=Cb(m.a),h=new H(0,0),p;p=(p=Q(k))?Cb(p):window;var v=k;do{var w;p==m?w=Y(v):(w=qc(v),w=new H(w.left,w.top));h.x+=w.x;h.y+=w.y}while(p&&p!=m&&p!=p.parent&&(v=p.frameElement)&&(p=p.parent));k=hb(h,Y(k));!K||O(9)||Gb(g)||(k=hb(k,Ab(g.a)));f.left+=k.x;f.top+=k.y}b=Dc(b,c);c=new H(b&
2?f.left+f.width:f.left,b&1?f.top+f.height:f.top);c=hb(c,e);if(b=sc(a))b.top-=e.y,b.right-=e.x,b.bottom-=e.y,b.left-=e.x;c=c.clone();f=Dc(a,d);d=uc(a);e=d.clone();c=c.clone();e=e.clone();0!=f&&(f&2&&(c.x-=e.width+0),f&1&&(c.y-=e.height+0));b?(f=c,g=e,k=65,m=0,65==(k&65)&&(f.x<b.left||f.x>=b.right)&&(k&=-2),132==(k&132)&&(f.y<b.top||f.y>=b.bottom)&&(k&=-5),f.x<b.left&&k&1&&(f.x=b.left,m|=1),k&16&&(h=f.x,f.x<b.left&&(f.x=b.left,m|=4),f.x+g.width>b.right&&(g.width=Math.min(b.right-f.x,h+g.width-b.left),
g.width=Math.max(g.width,0),m|=4)),f.x+g.width>b.right&&k&1&&(f.x=Math.max(b.right-g.width,b.left),m|=1),k&2&&(m=m|(f.x<b.left?16:0)|(f.x+g.width>b.right?32:0)),f.y<b.top&&k&4&&(f.y=b.top,m|=2),k&32&&(h=f.y,f.y<b.top&&(f.y=b.top,m|=8),f.y+g.height>b.bottom&&(g.height=Math.min(b.bottom-f.y,h+g.height-b.top),g.height=Math.max(g.height,0),m|=8)),f.y+g.height>b.bottom&&k&4&&(f.y=Math.max(b.bottom-g.height,b.top),m|=2),k&8&&(m=m|(f.y<b.top?64:0)|(f.y+g.height>b.bottom?128:0)),f=m):f=256;b=new ib(0,0,0,
0);b.left=c.x;b.top=c.y;b.width=e.width;b.height=e.height;f&496||(e=new H(b.left,b.top),e instanceof H?(c=e.x,e=e.y):(c=e,e=void 0),a.style.left=tc(c),a.style.top=tc(e),e=new B(b.width,b.height),d==e||d&&e&&d.width==e.width&&d.height==e.height||(d=e,c=Gb(P(Q(a))),!K||N("10")||c&&N("8")?(a=a.style,L?a.MozBoxSizing="border-box":M?a.WebkitBoxSizing="border-box":a.boxSizing="border-box",a.width=Math.max(d.width,0)+"px",a.height=Math.max(d.height,0)+"px"):(b=a.style,c?(K?(c=zc(a,"paddingLeft"),e=zc(a,
"paddingRight"),f=zc(a,"paddingTop"),g=zc(a,"paddingBottom"),c=new I(f,e,g,c)):(c=W(a,"paddingLeft"),e=W(a,"paddingRight"),f=W(a,"paddingTop"),g=W(a,"paddingBottom"),c=new I(parseFloat(f),parseFloat(e),parseFloat(g),parseFloat(c))),a=Cc(a),b.pixelWidth=d.width-a.left-c.left-c.right-a.right,b.pixelHeight=d.height-a.top-c.top-c.bottom-a.bottom):(b.pixelWidth=d.width,b.pixelHeight=d.height))))}}
function Xc(a,b,c){if(!a.J)if(3==b.nodeType){var d=null;r(c)&&1<c.length&&(d=Ja(c,1));c=Zc(c);if(0!=c.length){var e=b.nodeValue,f=new RegExp("\\b(?:"+c+")","gi");c=[];for(var g=0,h=f.exec(e),k=0;h;)k++,c.push(e.substring(g,h.index)),c.push(e.substring(h.index,f.lastIndex)),g=f.lastIndex,h=f.exec(e);c.push(e.substring(g));if(1<c.length){for(d=0;1>d;d++)e=2*d,b.nodeValue=c[e],f=a.g.a.createElement("B"),f.className=a.sa,f.appendChild(a.g.a.createTextNode(String(c[e+1]))),f=b.parentNode.insertBefore(f,
b.nextSibling),b.parentNode.insertBefore(a.g.a.createTextNode(""),f.nextSibling),b=f.nextSibling;b.nodeValue=Ja(c,2).join("");a.J=!0}else d&&Xc(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,Xc(a,b,c),b=d}function Zc(a){var b="";if(!a)return b;r(a)&&(a=Fa(a,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));r(a)?b=0<a.length?Ca(a[0]):"":/^\W/.test(a)||(b=Ca(a));return b}function $c(a,b){for(;b&&b!=a.b&&!Ta(b,"ac-row");)b=b.parentNode;return b?Ea(a.f,b):-1}
l.ka=function(a){var b=$c(this,a.target);0<=b&&V(this,{type:Ic,t:this.c[b].id});a.stopPropagation()};l.ma=function(a){a.stopPropagation();a.preventDefault()};l.na=function(a){a=$c(this,a.target);0<=a&&!(300>x()-this.B)&&V(this,{type:Hc,t:this.c[a].id})};var ad=F("iPhone")&&!F("iPod")&&!F("iPad")||F("iPod"),bd=F("iPad");!F("Android")||gb()||F("Firefox")||eb();gb();function cd(a,b,c,d){z.call(this);d=d||150;this.c=null!=c?c:!0;this.h=a||",;";this.n=this.h.substring(0,1);a=this.c?"[\\s"+this.h+"]+":"[\\s]+";this.k=new RegExp("^"+a+"|"+a+"$","g");this.I=new RegExp("\\s*["+this.h+"]$");this.i=b||"";this.s=this.c;this.d=0<d?new Ec(d):null;this.b=new bc(this);this.f=new bc(this);this.j=new ic;this.g=-1}y(cd,z);var dd=(ad||bd)&&!N("533.17.9");l=cd.prototype;l.e=null;l.O="";l.p=!1;l.Q=!1;l.K=function(a){this.e.value=a};
l.ia=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];ba(c)&&1==c.nodeType&&Ib(c,"haspopup",!0);this.b.d(c,"focus",this.U);this.b.d(c,"blur",this.ja);if(!this.e&&(this.f.d(c,"keydown",this.pa),ba(c)&&1==c.nodeType)){var d;a:{var e=Q(c);try{d=e&&e.activeElement;break a}catch(f){}d=null}d==c&&ed(this,c)}}};
function fd(a,b){switch(b.a){case 40:if(a.a.c.j){Pc(a.a);b.preventDefault();return}if(!a.c){a.update(!0);b.preventDefault();return}break;case 38:if(a.a.c.j){a:for(var c=a.a,d=c.f,e=0;e<c.b.length;e++){if(d>c.a)d--;else break;if(c.q(d))break a}b.preventDefault();return}break;case 9:if(!a.a.c.j||b.g)a.a.m();else if(a.update(),Mc(a.a)&&a.s){b.preventDefault();return}break;case 13:if(a.a.c.j){if(a.update(),Mc(a.a)){b.preventDefault();b.stopPropagation();return}}else a.a.m();break;case 27:if(a.a.c.j){a.a.m();
b.preventDefault();b.stopPropagation();return}break;case 229:if(!a.p){a.p||(a.b.d(a.e,"keyup",a.Z),a.b.d(a.e,"keypress",a.Y),a.p=!0);return}}gd(a,b)}function gd(a,b){var c=a.c&&b.f&&-1!=a.h.indexOf(String.fromCharCode(b.f));c&&a.update();c&&Mc(a.a)&&b.preventDefault()}l.la=function(){return!1};l.U=function(a){ed(this,a.target||null)};
function ed(a,b){var c=a.f;oa(c.a,T);c.a={};a.a&&Nc(a.a);b!=a.e&&(a.e=b,a.d&&(c=a.d,c.f=!0,c.a||(c.a=c.b.setTimeout(c.g,c.c),c.i=x()),a.b.d(a.d,Fc,a.ba)),a.O=a.e.value,jc(a.j,a.e),a.b.d(a.j,"key",a.$),a.b.d(a.e,"mousedown",a.aa),K&&a.b.d(a.e,"keypress",a.X))}l.ja=function(){dd?window.setTimeout(u(this.ca,this),0):this.ca()};
l.ca=function(){if(this.e){this.b.h(this.j,"key",this.$);pc(this.j);this.b.h(this.e,"keyup",this.la);this.b.h(this.e,"mousedown",this.aa);K&&this.b.h(this.e,"keypress",this.X);this.p&&hd(this);this.e=null;if(this.d){var a=this.d;a.f=!1;a.a&&(a.b.clearTimeout(a.a),a.a=null);this.b.h(this.d,Fc,this.ba)}this.a&&Oc(this.a)}};l.ba=function(){this.update()};l.pa=function(a){this.U(a)};l.$=function(a){this.g=a.a;this.a&&fd(this,a)};l.Y=function(){this.p&&229!=this.g&&hd(this)};
l.Z=function(a){this.p&&(13==a.a||77==a.a&&a.j)&&hd(this)};l.aa=function(){};function hd(a){a.p&&(a.p=!1,a.b.h(a.e,"keypress",a.Y),a.b.h(a.e,"keyup",a.Z))}l.X=function(a){gd(this,a)};
l.update=function(a){if(this.e&&(a||this.e.value!=this.O)){if(a||!this.Q){var b;a=Kb(this.e)[0];b=this.e.value;a=Rc(this,b)[Qc(this,b,a)];b=this.k?String(a).replace(this.k,""):a;if(this.a&&(this.a.k=this.e,a=this.a,a.i!=b)){a.i=b;var c=a.n;b=a.i;var d=a.s,e=u(a.oa,a),c=c.a,f;f=[];if(""!=b)for(var g=Ca(b),g=new RegExp("(^|\\W+)"+g,"i"),h=0;h<c.length&&f.length<d;h++){var k=c[h];String(k).match(g)&&f.push(k)}0==f.length&&(f=kb(b,d,c));e(b,f);Nc(a)}}this.O=this.e.value}this.Q=!1};
function Qc(a,b,c){a=Rc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}function Rc(a,b){if(!a.c)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,g=!1;f<c.length;f++)a.i&&-1!=a.i.indexOf(c[f])?(g||(d.push(e.join("")),e.length=0),e.push(c[f]),g=!g):g||-1==a.h.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};function id(a,b){var c=new jb(a),d=new Sc,e=new cd(null,null,!1),c=new Gc(c,d,e);e.a=c;e.ia(b);return c};/*
 Copyright 2013 Jason Leyba

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
function jd(){var a=n.TYPES;kd(a);ld(a);md()}var nd=["init"],Z=n;nd[0]in Z||!Z.execScript||Z.execScript("var "+nd[0]);for(var od;nd.length&&(od=nd.shift());)nd.length||void 0===jd?Z[od]?Z=Z[od]:Z=Z[od]={}:Z[od]=jd;var Ra=function(){var a=document.querySelectorAll("script"),b="";Ga(a,function(a){a=a.getAttribute("src");var d=a.length;return"dossier.js"===a.slice(d-10)?(b=a.slice(0,d-10),!0):!1});return b}();
function md(){function a(a){a=Fb(a,function(a){return"TR"===a.nodeName});Ua(a,"hilite")}var b=document.querySelector("article.srcfile table");if(b){if(location.hash){var c=document.querySelector("tr > td a"+location.hash);c&&a(c)}S(window,"hashchange",function(){D(b.querySelectorAll("tr.hilite"),function(a){Wa(a,"hilite")});var c=b.querySelector("tr > td a:target");c&&a(c)})}}
function kd(a){function b(){var a=c[e.value];a&&(window.location.href=Ra+a)}var c={},d=[];a.types&&D(a.types,function(a){pd(d,c,a)});a.modules&&D(a.modules,function(a){pd(d,c,a,!0)});a=document.querySelector("header form");S(a,"submit",function(a){a.preventDefault();a.stopPropagation();b();return!1});var e=a.querySelector("input");a=id(d,e);a.s=20;S(a,"update",b)}
function pd(a,b,c,d,e){var f=c.name;e&&(f=e+(sa(e,")")?" ":".")+f);b[f]=c.href;a.push(f);d&&(f="("+f+")");d&&c.types&&D(c.types,function(c){pd(a,b,c,!1,f)});c.statics&&D(c.statics,function(d){var e=c.href+"#"+d;d=sa(f,")")?f+" "+d:-1===d.indexOf(".")?f+"."+d:f+d.slice(d.lastIndexOf("."));b[d]=e;a.push(d)});c.members&&D(c.members,function(d){b[f+"#"+d]=c.href+"#"+d;a.push(f+"#"+d)})}
function ld(a){var b="";Ra?b=window.location.pathname.split("/").slice(Ra.split("/").length).join("/"):window.location.pathname&&"/"!==window.location.pathname&&(b=window.location.pathname.slice(window.location.pathname.lastIndexOf("/")+1));var c=Ka,d=xb("nav-types-view");d&&a.types&&d.appendChild(c.R(a.types,b,!1));(d=xb("nav-modules-view"))&&a.modules&&d.appendChild(c.R(a.modules,b,!0));window.localStorage&&(c=document.querySelector("nav"),a=c.querySelectorAll('input[type="checkbox"][id]'),D(a,
function(a){var b=window.localStorage.getItem(a.id);a.checked=!t(b)||"closed"===b}),S(c,"change",function(a){window.localStorage.setItem(a.target.id,a.target.checked?"closed":"open")}))};;init();})();
