(function(){'use strict';var k,n=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function p(a){return"array"==aa(a)}function ba(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function ca(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var da="closure_uid_"+(1E9*Math.random()>>>0),ea=0;function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function t(a,b,c){t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return t.apply(null,arguments)}var u=Date.now||function(){return+new Date};
function v(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Da=function(a,c,e){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var ha;function x(){0!=ia&&(this[da]||(this[da]=++ea));this.na=this.na;this.ra=this.ra}var ia=0;x.prototype.na=!1;var ja;function z(a,b){this.type=a;this.f=this.a=b;this.c=!1;this.la=!0}z.prototype.stopPropagation=function(){this.c=!0};z.prototype.preventDefault=function(){this.la=!1};var ka="closure_listenable_"+(1E6*Math.random()|0),la=0;function ma(a,b,c,d,f){this.listener=a;this.a=null;this.src=b;this.type=c;this.M=!!d;this.N=f;this.ba=++la;this.H=this.L=!1}function na(a){a.H=!0;a.listener=null;a.a=null;a.src=null;a.N=null};function A(a,b){this.width=a;this.height=b}A.prototype.clone=function(){return new A(this.width,this.height)};A.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};A.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};A.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function oa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var pa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function qa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<pa.length;e++)c=pa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function ra(a){ra[" "](a);return a}ra[" "]=function(){};function sa(a,b){try{return ra(a[b]),!0}catch(c){}return!1};function ta(a){var b=a.length-1;return 0<=b&&a.indexOf("/",b)==b}var ua=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function va(a){if(!wa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(xa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ya,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(za,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Aa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ba,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ca,"&#0;"));return a}var xa=/&/g,ya=/</g,za=/>/g,Aa=/"/g,Ba=/'/g,Ca=/\x00/g,wa=/[\x00&<>"']/;
function Da(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function Ea(a,b){return a<b?-1:a>b?1:0};function Fa(a){return a[a.length-1]}
var Ga=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},B=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=r(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},Ha=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=r(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var m=g[h];b.call(c,m,h,a)&&(f[e++]=m)}return f};function Ia(a,b){a:{for(var c=a.length,d=r(a)?a.split(""):a,f=0;f<c;f++)if(f in d&&b.call(void 0,d[f],f,a)){b=f;break a}b=-1}return 0>b?null:r(a)?a.charAt(b):a[b]}function Ja(a,b){b=Ga(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}function Ka(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function La(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Ma(a){if(a.classList)return a.classList;a=a.className;return r(a)&&a.match(/\S+/g)||[]}function Na(a,b){a.classList?b=a.classList.contains(b):(a=Ma(a),b=0<=Ga(a,b));return b}function Oa(a,b){a.classList?a.classList.add(b):Na(a,b)||(a.className+=0<a.className.length?" "+b:b)}function Pa(a,b){if(a.classList)B(b,function(b){Oa(a,b)});else{var c={};B(Ma(a),function(a){c[a]=!0});B(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function Qa(a,b){a.classList?a.classList.remove(b):Na(a,b)&&(a.className=Ha(Ma(a),function(a){return a!=b}).join(" "))}function Ra(a){var b=["ac-active","active"];a.classList?B(b,function(b){Qa(a,b)}):a.className=Ha(Ma(a),function(a){return!(0<=Ga(b,a))}).join(" ")};function Sa(a){this.src=a;this.a={};this.b=0}function Ta(a,b,c,d,f){var e=b.toString();b=a.a[e];b||(b=a.a[e]=[],a.b++);var g=Ua(b,c,d,f);-1<g?(a=b[g],a.L=!1):(a=new ma(c,a.src,e,!!d,f),a.L=!1,b.push(a));return a}function Va(a,b){var c=b.type;c in a.a&&Ja(a.a[c],b)&&(na(b),0==a.a[c].length&&(delete a.a[c],a.b--))}function Wa(a,b,c,d,f){a=a.a[b.toString()];b=-1;a&&(b=Ua(a,c,d,f));return-1<b?a[b]:null}
function Ua(a,b,c,d){for(var f=0;f<a.length;++f){var e=a[f];if(!e.H&&e.listener==b&&e.M==!!c&&e.N==d)return f}return-1};var C;a:{var Xa=n.navigator;if(Xa){var Ya=Xa.userAgent;if(Ya){C=Ya;break a}}C=""}function D(a){return-1!=C.indexOf(a)};function E(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}E.prototype.clone=function(){return new E(this.x,this.y)};function Za(a,b){return new E(a.x-b.x,a.y-b.y)}E.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};E.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};E.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function F(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}k=F.prototype;k.clone=function(){return new F(this.top,this.right,this.bottom,this.left)};k.contains=function(a){return this&&a?a instanceof F?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
k.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};k.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};k.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function $a(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}k=$a.prototype;k.clone=function(){return new $a(this.left,this.top,this.width,this.height)};k.contains=function(a){return a instanceof $a?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
k.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};k.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};k.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function ab(a){this.a=a||[]};function G(){}G.a=function(){return G.b?G.b:G.b=new G};G.prototype.a=0;var bb=D("Opera"),H=D("Trident")||D("MSIE"),I=D("Edge"),cb=I||H,J=D("Gecko")&&!(-1!=C.toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge"),K=-1!=C.toLowerCase().indexOf("webkit")&&!D("Edge"),L=D("Macintosh");function db(){var a=n.document;return a?a.documentMode:void 0}var eb;
a:{var fb="",gb=function(){var a=C;if(J)return/rv\:([^\);]+)(\)|;)/.exec(a);if(I)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(K)return/WebKit\/(\S+)/.exec(a);if(bb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gb&&(fb=gb?gb[1]:"");if(H){var hb=db();if(null!=hb&&hb>parseFloat(fb)){eb=String(hb);break a}}eb=fb}var ib={};
function M(a){var b;if(!(b=ib[a])){b=0;for(var c=ua(String(eb)).split("."),d=ua(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",h=d[e]||"",m=/(\d*)(\D*)/g,q=/(\d*)(\D*)/g;do{var y=m.exec(g)||["","",""],w=q.exec(h)||["","",""];if(0==y[0].length&&0==w[0].length)break;b=Ea(0==y[1].length?0:parseInt(y[1],10),0==w[1].length?0:parseInt(w[1],10))||Ea(0==y[2].length,0==w[2].length)||Ea(y[2],w[2])}while(0==b)}b=ib[a]=0<=b}return b}
var jb=n.document,N=jb&&H?db()||("CSS1Compat"==jb.compatMode?parseInt(eb,10):5):void 0;var lb=!H||9<=Number(N),mb=!J&&!H||H&&9<=Number(N)||J&&M("1.9.1");H&&M("9");var nb=H||bb||K;function O(a){return a?new ob(P(a)):ja||(ja=new ob)}function pb(a,b){oa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:qb.hasOwnProperty(d)?a.setAttribute(qb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function rb(a){var b=sb(a);a=tb(a);return H&&M("10")&&a.pageYOffset!=b.scrollTop?new E(b.scrollLeft,b.scrollTop):new E(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}
function sb(a){return a.scrollingElement?a.scrollingElement:!K&&ub(a)?a.documentElement:a.body||a.documentElement}function tb(a){return a.parentWindow||a.defaultView}
function vb(a,b,c){function d(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(!ba(e)||ca(e)&&0<e.nodeType)d(e);else{var g;a:{if(e&&"number"==typeof e.length){if(ca(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if("function"==aa(e)){g="function"==typeof e.item;break a}}g=!1}B(g?Ka(e):e,d)}}}function ub(a){return"CSS1Compat"==a.compatMode}function wb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function xb(a){var b;if(nb&&!(H&&M("9")&&!M("10")&&n.SVGElement&&a instanceof n.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return ca(b)&&1==b.nodeType?b:null}function P(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function yb(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function ob(a){this.a=a||n.document||document}
ob.prototype.b=function(a,b,c){var d=this.a,f=arguments,e=f[0],g=f[1];if(!lb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',va(g.name),'"');if(g.type){e.push(' type="',va(g.type),'"');var h={};qa(h,g);delete h.type;g=h}e.push(">");e=e.join("")}e=d.createElement(e);g&&(r(g)?e.className=g:p(g)?e.className=g.join(" "):pb(e,g));2<f.length&&vb(d,e,f);return e};ob.prototype.f=wb;ob.prototype.G=function(a){return mb&&a.children?a.children:Ha(a.childNodes,function(a){return 1==a.nodeType})};
ob.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function zb(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function Ab(a,b,c){p(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(ha||(ha={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=ha,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Bb(a,b){var c="";b&&(c=b.id);Ab(a,"activedescendant",c)};function Cb(a){var b=0,c=0;if(Db(a))b=a.selectionStart,c=-1;else if(H){var d=Eb(a),f=d[0],d=d[1];if(f.inRange(d)){f.setEndPoint("EndToStart",d);if("textarea"==a.type){d.duplicate();b=a=f.text;for(c=!1;!c;)0==f.compareEndPoints("StartToEnd",f)?c=!0:(f.moveEnd("character",-1),f.text==a?b+="\r\n":c=!0);f=[b.length,-1];return f}b=f.text.length;c=-1}}return[b,c]}
function Eb(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function Fb(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function Db(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};var Gb=!H||9<=Number(N),Hb=H&&!M("9");!K||M("528");J&&M("1.9b")||H&&M("8")||bb&&M("9.5")||K&&M("528");J&&!M("8")||H&&M("9");function Q(a,b){z.call(this,a?a.type:"");this.f=this.a=null;this.g=this.keyCode=this.clientY=this.clientX=0;this.metaKey=this.j=this.b=this.ctrlKey=!1;this.i=this.state=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.a=a.target||a.srcElement;this.f=b;(b=a.relatedTarget)&&J&&sa(b,"nodeName");null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=
void 0!==d.clientY?d.clientY:d.pageY);this.keyCode=a.keyCode||0;this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.b=a.altKey;this.j=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.i=a;a.defaultPrevented&&this.preventDefault()}}v(Q,z);Q.prototype.stopPropagation=function(){Q.ma.stopPropagation.call(this);this.i.stopPropagation?this.i.stopPropagation():this.i.cancelBubble=!0};
Q.prototype.preventDefault=function(){Q.ma.preventDefault.call(this);var a=this.i;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Hb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ib="closure_lm_"+(1E6*Math.random()|0),Jb={},Kb=0;
function R(a,b,c,d,f){if(p(b)){for(var e=0;e<b.length;e++)R(a,b[e],c,d,f);return null}c=Lb(c);if(a&&a[ka])a=a.f(b,c,d,f);else{if(!b)throw Error("Invalid event type");var e=!!d,g=Mb(a);g||(a[Ib]=g=new Sa(a));c=Ta(g,b,c,d,f);if(!c.a){d=Nb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ob(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Kb++}a=c}return a}
function Nb(){var a=Pb,b=Gb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Qb(a,b,c,d,f){if(p(b))for(var e=0;e<b.length;e++)Qb(a,b[e],c,d,f);else c=Lb(c),a&&a[ka]?a.i(b,c,d,f):a&&(a=Mb(a))&&(b=Wa(a,b,c,!!d,f))&&S(b)}
function S(a){if("number"!=typeof a&&a&&!a.H){var b=a.src;if(b&&b[ka])Va(b.w,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.M):b.detachEvent&&b.detachEvent(Ob(c),d);Kb--;(c=Mb(b))?(Va(c,a),0==c.b&&(c.src=null,b[Ib]=null)):na(a)}}}function Ob(a){return a in Jb?Jb[a]:Jb[a]="on"+a}function Rb(a,b,c,d){var f=!0;if(a=Mb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var e=b[a];e&&e.M==c&&!e.H&&(e=Sb(e,d),f=f&&!1!==e)}return f}
function Sb(a,b){var c=a.listener,d=a.N||a.src;a.L&&S(a);return c.call(d,b)}
function Pb(a,b){if(a.H)return!0;if(!Gb){if(!b)a:{b=["window","event"];for(var c=n,d;d=b.shift();)if(null!=c[d])c=c[d];else{b=null;break a}b=c}d=b;b=new Q(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var f=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==d.returnValue)d.returnValue=!0}d=[];for(f=b.f;f;f=f.parentNode)d.push(f);a=a.type;for(f=d.length-1;!b.c&&0<=f;f--){b.f=d[f];var e=Rb(d[f],a,!0,b),c=c&&e}for(f=0;!b.c&&f<d.length;f++)b.f=d[f],e=Rb(d[f],a,!1,b),c=
c&&e}return c}return Sb(a,new Q(b,this))}function Mb(a){a=a[Ib];return a instanceof Sa?a:null}var Tb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Lb(a){if("function"==aa(a))return a;a[Tb]||(a[Tb]=function(b){return a.handleEvent(b)});return a[Tb]};function Ub(a){x.call(this);this.b=a;this.a={}}v(Ub,x);var Vb=[];Ub.prototype.f=function(a,b,c,d){p(b)||(b&&(Vb[0]=b.toString()),b=Vb);for(var f=0;f<b.length;f++){var e=R(a,b[f],c||this.handleEvent,d||!1,this.b||this);if(!e)break;this.a[e.ba]=e}return this};
Ub.prototype.i=function(a,b,c,d,f){if(p(b))for(var e=0;e<b.length;e++)this.i(a,b[e],c,d,f);else c=c||this.handleEvent,f=f||this.b||this,c=Lb(c),d=!!d,b=a&&a[ka]?Wa(a.w,String(b),c,d,f):a?(a=Mb(a))?Wa(a,b,c,d,f):null:null,b&&(S(b),delete this.a[b.ba]);return this};function Wb(a){oa(a.a,function(a,c){this.a.hasOwnProperty(c)&&S(a)},a);a.a={}}Ub.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function T(){x.call(this);this.w=new Sa(this);this.oa=this;this.Y=null}v(T,x);T.prototype[ka]=!0;T.prototype.removeEventListener=function(a,b,c,d){Qb(this,a,b,c,d)};
function U(a,b){var c,d=a.Y;if(d)for(c=[];d;d=d.Y)c.push(d);a=a.oa;d=b.type||b;if(r(b))b=new z(b,a);else if(b instanceof z)b.a=b.a||a;else{var f=b;b=new z(d,a);qa(b,f)}var f=!0,e;if(c)for(var g=c.length-1;!b.c&&0<=g;g--)e=b.f=c[g],f=Xb(e,d,!0,b)&&f;b.c||(e=b.f=a,f=Xb(e,d,!0,b)&&f,b.c||(f=Xb(e,d,!1,b)&&f));if(c)for(g=0;!b.c&&g<c.length;g++)e=b.f=c[g],f=Xb(e,d,!1,b)&&f;return f}T.prototype.f=function(a,b,c,d){return Ta(this.w,String(a),b,c,d)};
T.prototype.i=function(a,b,c,d){var f;f=this.w;a=String(a).toString();if(a in f.a){var e=f.a[a];b=Ua(e,b,c,d);-1<b?(na(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete f.a[a],f.b--),f=!0):f=!1}else f=!1;return f};function Xb(a,b,c,d){b=a.w.a[String(b)];if(!b)return!0;b=b.concat();for(var f=!0,e=0;e<b.length;++e){var g=b[e];if(g&&!g.H&&g.M==c){var h=g.listener,m=g.N||g.src;g.L&&Va(a.w,g);f=!1!==h.call(m,d)&&f}}return f&&0!=d.la};function Yb(a,b,c,d,f){if(!(H||I||K&&M("525")))return!0;if(L&&f)return Zb(a);if(f&&!d)return!1;"number"==typeof b&&(b=$b(b));if(!c&&(17==b||18==b||L&&91==b))return!1;if((K||I)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(H&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!(K||I)}return Zb(a)}
function Zb(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(K||I)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function $b(a){if(J)a=ac(a);else if(L&&K)a:switch(a){case 93:a=91;break a}return a}
function ac(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};var bc=D("Safari")&&!((D("Chrome")||D("CriOS"))&&!D("Edge")||D("Coast")||D("Opera")||D("Edge")||D("Silk")||D("Android"))||!(D("iPad")||D("Android")&&!D("Mobile")||D("Silk"))&&(D("iPod")||D("iPhone")||D("Android")||D("IEMobile"));function cc(a,b){this.f=a;this.b=b;this.a=this.c=null}cc.prototype.getKey=function(){return this.f};cc.prototype.X=function(a){this.b=a};function dc(a,b){a.a||(a.a=[]);b.c=a;a.a.push(b)}cc.prototype.G=function(){return this.a};
cc.prototype.removeChild=function(a){a.c=null;Ja(this.a,a)};function ec(a){var b=a.a;a.a&&(a.a.forEach(function(a){a.c=null}),a.a=null);return b}function fc(a,b){return a.a?Ia(a.a,function(a){return a.f===b}):null}
function gc(a){var b=a.G();b&&(b.forEach(gc),b.filter(function(a){return null===a.b&&1==(a.a?a.a.length:0)}).forEach(function(b){a.removeChild(b);var d=ec(b);d&&d.forEach(function(d){var e=b.getKey()+"."+d.getKey();d.f=e;dc(a,d)})}),b.filter(function(a){return a.b&&!a.b.namespace&&!a.b.types&&(a.a?a.a.length:0)}).forEach(function(b){var d=ec(b);d&&d.forEach(function(d){var e=b.getKey()+"."+d.getKey();d.f=e;dc(a,d)})}))}
function hc(a){if(a=a.G())a.sort(function(a,c){return a.getKey()<c.getKey()?-1:a.getKey()>c.getKey()?1:0}),a.forEach(hc)}function ic(a,b){var c=new cc("",null);a.forEach(function(a){var f=c;a.qualifiedName.split(b?/\//:/\./).forEach(function(a){if(f!==c||f.getKey()!==a){var b=fc(f,a);b||(b=new cc(a,null),dc(f,b));f=b}});f.X(a)});b||gc(c);hc(c);return c}
function jc(a,b,c,d){var f=document.createElement("li"),e=document.createElement("a");e.classList.add("item");e.textContent=a.getKey();e.tabIndex=2;a.b&&(e.href=b+a.b.href,a.b.interface&&e.classList.add("interface"));a.b&&a.b.href===c&&e.classList.add("current");var g=a.G();if(g){var h=document.createElement("i");h.classList.add("material-icons");h.textContent="expand_more";var m=document.createElement("div");m.dataset.id=d+a.getKey();m.classList.add("toggle");m.appendChild(e);m.appendChild(h);f.appendChild(m);
var q=document.createElement("ul");q.classList.add("tree");f.appendChild(q);g.forEach(function(f){q.appendChild(jc(f,b,c,d+a.getKey()+"."))})}else f.appendChild(e);return f}function kc(a,b,c,d){b&&!ta(b)&&(b+="/");a=ic(a,d);var f=document.createElement("ul");f.classList.add("tree");a.G()&&a.G().forEach(function(a){f.appendChild(jc(a,b,c,d?".nav-module:":".nav:"))});return f}function lc(){var a=document.createElement("div");a.classList.add("dossier-nav-mask");return a}
function mc(a,b){this.i=a;this.a=b;this.f=b.ownerDocument.createElement("div");this.f.tabIndex=-1;b.insertBefore(this.f,b.firstChild)}mc.prototype.g=function(){var a=this.a.querySelector(".current");a&&(a=a.getBoundingClientRect().top,this.a.scrollTop=a-window.innerHeight/2)};function nc(a){a.a.classList.remove("visible");oc(a)}mc.prototype.c=function(){this.a.classList.toggle("visible");oc(this)};
function oc(a){a.i.disabled=a.a.classList.contains("visible");if(a.b){B(a.a.querySelectorAll("a.title, span.item"),function(a){return a.tabIndex=1});B(a.a.querySelectorAll("section > .toggle.open ~ .tree"),function(b){return pc(a,b,!0)});var b=a.a.scrollTop;a.f.focus();a.a.scrollTop=b}else B(a.a.querySelectorAll("span.item, a"),function(a){return a.tabIndex=-1})}
mc.prototype.j=function(a){(a=yb(a.a,function(a){return a&&a.classList&&a.classList.contains("toggle")},!0,4))&&a.classList.contains("toggle")&&qc(this,a)};
function qc(a,b,c,d){"boolean"==typeof c?c?b.classList.add("open"):b.classList.remove("open"):b.classList.toggle("open");d||window.localStorage&&b.dataset.id&&window.localStorage.setItem(b.dataset.id,b.classList.contains("open")?"open":"closed");(c=b.nextElementSibling)&&c.classList.contains("tree")&&(b.classList.contains("open")?(bc?c.style.display="block":c.style.maxHeight=c.dataset.maxHeight+"px",pc(a,c,a.b)):(bc?c.style.display="none":c.style.maxHeight="0",pc(a,c,!1)))}
function pc(a,b,c){c?B(b.childNodes,function(a){if((a=a.firstChild)&&a.classList)if(a.classList.contains("item"))a.tabIndex=1;else if(a.classList.contains("toggle")){var b=a.querySelector(".item");b&&(b.tabIndex=1);a.classList.contains("open")&&a.nextElementSibling&&a.nextElementSibling.classList.contains("tree")&&pc(this,a.nextElementSibling,!0)}},a):B(b.querySelectorAll(".item"),function(a){return a.tabIndex=-1})}Object.defineProperties(mc.prototype,{b:{configurable:!0,enumerable:!0,get:function(){return this.a.classList.contains("visible")}}});
function rc(a){var b=window.location.pathname.slice(sc.length),c=sc;function d(a,d,f){d=kc(d,c,b,f);a.appendChild(d);a.querySelector(".toggle").dataset.id=f?".nav-module:":".nav:"}function f(a){for(;a&&a!=g;a=xb(a))if(a.classList.contains("tree")){var b=a.previousElementSibling;b&&b.classList.contains("toggle")&&qc(m,b,!0,!0)}}var e=document.querySelector("button.dossier-menu");e.setAttribute("title","Show Navigation (n)");var g=document.querySelector("nav.dossier-nav"),h=lc();g.parentNode.appendChild(h);
var m=new mc(e,g);R(h,"click",m.c,!1,m);R(e,"click",m.c,!1,m);R(g,"click",m.j,!1,m);(e=g.querySelector(".types"))&&a.types&&d(e,a.types,!1);(e=g.querySelector(".modules"))&&a.modules&&d(e,a.modules,!0);a=g.querySelectorAll(".tree");e=0;for(h=a.length;e<h;e++){var q=a[e];q.dataset.maxHeight=45*q.querySelectorAll("li").length;bc?(q.style.transition="none",q.style.display="none"):q.style.maxHeight=0}window.localStorage&&B(g.querySelectorAll(".toggle[data-id]"),function(a){var b=window.localStorage.getItem(a.dataset.id);
qc(m,a,"open"===b)});(a=g.querySelector(".current"))||(a=Ia(g.querySelectorAll("a.title[href]"),function(a){return a.getAttribute("href")===b}));a&&(a.classList.add("current"),f(a));nc(m);return m};function tc(a,b){R(b,"focus",function(){nc(a)});R(document.documentElement,"keydown",function(c){switch(c.keyCode){case 69:if(document.activeElement!==b&&(L?c.metaKey:c.ctrlKey))return nc(a),b.focus(),c.preventDefault(),c.stopPropagation(),!1;break;case 78:document.activeElement!==b&&a.c();break;case 191:if(document.activeElement!==b)return nc(a),b.focus(),c.preventDefault(),c.stopPropagation(),!1;break;case 27:document.activeElement===b&&b.blur();nc(a);break;default:if(a.b&&a.b&&"keydown"===c.type){if(!(37!==
c.keyCode&&39!==c.keyCode||c.b||c.ctrlKey||c.metaKey||c.j)&&c.a&&c.a.classList&&c.a.classList.contains("item")){var d=c.a.parentNode;d&&d.classList&&d.classList.contains("toggle")||!d||(d=d.parentNode);d&&d.classList&&d.classList.contains("toggle")&&qc(a,d,39===c.keyCode)}9!==c.keyCode||c.j||c.a===Fa(a.a.querySelectorAll("span.item, a"))&&nc(a)}}})};function uc(a,b){T.call(this);a&&vc(this,a,b)}v(uc,T);k=uc.prototype;k.I=null;k.O=null;k.T=null;k.P=null;k.s=-1;k.A=-1;k.R=!1;
var wc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},xc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},yc=H||I||K&&M("525"),zc=L&&J;
uc.prototype.a=function(a){if(K||I)if(17==this.s&&!a.ctrlKey||18==this.s&&!a.b||L&&91==this.s&&!a.metaKey)this.A=this.s=-1;-1==this.s&&(a.ctrlKey&&17!=a.keyCode?this.s=17:a.b&&18!=a.keyCode?this.s=18:a.metaKey&&91!=a.keyCode&&(this.s=91));yc&&!Yb(a.keyCode,this.s,a.j,a.ctrlKey,a.b)?this.handleEvent(a):(this.A=$b(a.keyCode),zc&&(this.R=a.b))};uc.prototype.b=function(a){this.A=this.s=-1;this.R=a.b};
uc.prototype.handleEvent=function(a){var b=a.i,c,d,f=b.altKey;H&&"keypress"==a.type?(c=this.A,d=13!=c&&27!=c?b.keyCode:0):(K||I)&&"keypress"==a.type?(c=this.A,d=0<=b.charCode&&63232>b.charCode&&Zb(c)?b.charCode:0):bb&&!K?(c=this.A,d=Zb(c)?b.keyCode:0):(c=b.keyCode||this.A,d=b.charCode||0,zc&&(f=this.R),L&&63==d&&224==c&&(c=191));var e=c=$b(c),g=b.keyIdentifier;c?63232<=c&&c in wc?e=wc[c]:25==c&&a.j&&(e=9):g&&g in xc&&(e=xc[g]);this.s=e;a=new Ac(e,d,0,b);a.b=f;U(this,a)};
function vc(a,b,c){a.P&&Bc(a);a.I=b;a.O=R(a.I,"keypress",a,c);a.T=R(a.I,"keydown",a.a,c,a);a.P=R(a.I,"keyup",a.b,c,a)}function Bc(a){a.O&&(S(a.O),S(a.T),S(a.P),a.O=null,a.T=null,a.P=null);a.I=null;a.s=-1;a.A=-1}function Ac(a,b,c,d){Q.call(this,d);this.type="key";this.keyCode=a;this.g=b}v(Ac,Q);function V(a,b){var c=P(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""}function W(a,b){return V(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Cc(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}H&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Dc(a){if(H&&!(8<=Number(N)))return a.offsetParent;var b=P(a),c=W(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=W(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Ec(a){for(var b=new F(0,Infinity,Infinity,0),c=O(a),d=c.a.body,f=c.a.documentElement,e=sb(c.a);a=Dc(a);)if(!(H&&0==a.clientWidth||K&&0==a.clientHeight&&a==d)&&a!=d&&a!=f&&"visible"!=W(a,"overflow")){var g=Y(a),h=new E(a.clientLeft,a.clientTop);g.x+=h.x;g.y+=h.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=e.scrollLeft;e=e.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,e);c=(tb(c.a)||
window).document;c=ub(c)?c.documentElement:c.body;c=new A(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,e+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}function Y(a){var b=P(a),c=new E(0,0),d;d=b?P(b):document;d=!H||9<=Number(N)||ub(O(d).a)?d.documentElement:d.body;if(a==d)return c;a=Cc(a);b=rb(O(b).a);c.x=a.left+b.x;c.y=a.top+b.y;return c}function Fc(a){"number"==typeof a&&(a+="px");return a}
function Gc(a){var b=Hc;if("none"!=W(a,"display"))return b(a);var c=a.style,d=c.display,f=c.visibility,e=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=e;c.visibility=f;return a}function Hc(a){var b=a.offsetWidth,c=a.offsetHeight,d=K&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Cc(a),new A(a.right-a.left,a.bottom-a.top)):new A(b,c)}var Ic=J?"MozUserSelect":K||I?"WebkitUserSelect":null;
function Jc(a){var b=a.getElementsByTagName("*");if(Ic){var c="none";a.style&&(a.style[Ic]=c);if(b){a=0;for(var d;d=b[a];a++)d.style&&(d.style[Ic]=c)}}else if(H||bb)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function Kc(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;b=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return b}
function Lc(a,b){return(b=a.currentStyle?a.currentStyle[b]:null)?Kc(a,b):0}var Mc={thin:2,medium:4,thick:6};function Nc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;b=a.currentStyle?a.currentStyle[b+"Width"]:null;return b in Mc?Mc[b]:Kc(a,b)}
function Oc(a){if(H&&!(9<=Number(N))){var b=Nc(a,"borderLeft"),c=Nc(a,"borderRight"),d=Nc(a,"borderTop");a=Nc(a,"borderBottom");return new F(d,c,a,b)}b=V(a,"borderLeftWidth");c=V(a,"borderRightWidth");d=V(a,"borderTopWidth");a=V(a,"borderBottomWidth");return new F(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function Pc(a,b){return(b&8&&"rtl"==W(a,"direction")?b^4:b)&-9};function Qc(a,b){T.call(this);this.c=a||1;this.b=b||n;this.l=t(this.o,this);this.m=u()}v(Qc,T);Qc.prototype.g=!1;Qc.prototype.a=null;Qc.prototype.o=function(){if(this.g){var a=u()-this.m;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.l,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),U(this,"tick"),this.g&&(this.a=this.b.setTimeout(this.l,this.c),this.m=u()))}};function Rc(a,b,c){T.call(this);this.u=a;this.J=c;this.c=b;R(b,[Sc,Tc,Uc,Vc],this.handleEvent,!1,this);this.m=null;this.b=[];this.g=-1;this.a=0;this.l=this.o=null;this.K={}}v(Rc,T);Rc.prototype.F=10;var Sc="hilite",Tc="select",Vc="dismiss",Uc="canceldismiss";k=Rc.prototype;
k.handleEvent=function(a){var b=this.u;if(a.a==this.c)switch(a.type){case Sc:this.C(a.D);break;case Tc:var c=!1;if("number"==typeof a.D){a=a.D;var d=this.b[Wc(this,a)],c=!!d&&b.S&&b.S(d);d&&!c&&this.g!=a&&this.C(a)}c||Xc(this);break;case Uc:Yc(this);break;case Vc:Zc(this)}};function $c(a){for(var b=a.a+a.b.length-1,c=a.g,d=0;d<a.b.length;d++){if(c>=a.a&&c<b)c++;else if(-1==c)c=a.a;else break;if(a.C(c))break}}
k.C=function(a){var b=Wc(this,a),c=this.b[b];return c&&this.u.S&&this.u.S(c)?!1:(this.g=a,this.c.C(a),-1!=b)};
function Xc(a){var b=Wc(a,a.g);if(-1!=b){var c=a.b[b],d=a.J;if(d.h){var f=c.toString();if(d.c){var e=ad(d,d.h.value,Cb(d.h)[0]),g=bd(d,d.h.value);d.F.test(f)||(f=f.replace(/[\s\xa0]+$/,"")+d.o);0==e||/^[\s\xa0]*$/.test(g[e-1])||(f=" "+f);e==g.length-1&&(f+=" ");if(f!=g[e]){g[e]=f;f=d.h;(J||H&&M("9"))&&f.blur();f.value=g.join("");for(var h=0,m=0;m<=e;m++)h+=g[m].length;f.focus();e=h;g=d.h;f=e;Db(g)?g.selectionStart=f:H&&(h=Eb(g),m=h[0],m.inRange(h[1])&&(f=Fb(g,f),m.collapse(!0),m.move("character",
f),m.select()));g=d.h;Db(g)?g.selectionEnd=e:H&&(h=Eb(g),f=h[1],h[0].inRange(f)&&(e=Fb(g,e),g=Fb(g,Cb(g)[0]),f.collapse(!0),f.moveEnd("character",e-g),f.select()))}}else d.X(f);d.W=!0}a.v();U(a,{type:"update",D:c,index:b});return!0}a.v();U(a,{type:"update",D:null,index:null});return!1}k.v=function(){this.g=-1;this.m=null;this.a+=this.b.length;this.b=[];window.clearTimeout(this.l);this.l=null;this.c.v();U(this,"suggestionsupdate");U(this,Vc)};
function Zc(a){a.l||(a.l=window.setTimeout(t(a.v,a),100))}k.da=function(){return this.l?(window.clearTimeout(this.l),this.l=null,!0):!1};function Yc(a){a.da()||window.setTimeout(t(a.da,a),10)}k.Ba=function(a,b,c){this.m==a&&this.V(b,c)};
k.V=function(a,b){var c="object"==aa(b)&&b;b=(c?c.Ea():b)?Wc(this,this.g):-1;this.a+=this.b.length;this.b=a;for(var d=[],f=0;f<a.length;++f)d.push({id:this.a+f,data:a[f]});a=null;this.o&&(a=this.K,f=this.o,f=f[da]||(f[da]=++ea),a=a[f]||this.o);this.c.pa=a;this.c.V(d,this.m,this.o);a=!0;c&&void 0!==c.ua()&&(a=c.ua());this.g=-1;(a||0<=b)&&0!=d.length&&this.m&&(0<=b?this.C(this.a+b):$c(this));U(this,"suggestionsupdate")};function Wc(a,b){b-=a.a;return 0>b||b>=a.b.length?-1:b}k.update=function(a){this.J.update(a)};function cd(a,b,c,d){T.call(this);this.F=a||document.body;this.l=O(this.F);this.K=!a;this.a=null;this.J="";this.c=[];this.g=[];this.Z=this.o=-1;this.j=!1;this.className="ac-renderer";this.qa="ac-highlighted";this.m=b||null;this.$=null!=d?d:!0;this.sa=!!c;this.u=!1}v(cd,T);k=cd.prototype;k.V=function(a,b,c){this.J=b;this.c=a;this.o=-1;this.Z=u();this.b=c;this.g=[];dd(this)};k.v=function(){this.j&&(this.j=!1,ed(this,!1),this.a.style.display="none")};
function fd(a){a.j||(a.j=!0,ed(a,!0),a.a.style.display="")}function ed(a,b){a.b&&(Ab(a.b,"haspopup",b),Ab(a.a,"expanded",b),Ab(a.b,"expanded",b),b?Ab(a.b,"owns",a.a.id):(a.b.removeAttribute("aria-owns"),Bb(a.b,null)))}
function gd(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.g.length?a.g[b]:void 0;if(U(a,{type:"rowhilite",Ha:d,D:c?c.data:null})&&(0<=a.o&&Ra(a.g[a.o]),a.o=b,d)){Pa(d,["ac-active","active"]);a.b&&Bb(a.b,d);b=(a=a.a||sb(document))||sb(document);var f=Y(d),e=Y(b),g=Oc(b);b==sb(document)?(c=f.x-b.scrollLeft,f=f.y-b.scrollTop,!H||10<=Number(N)||(c+=g.left,f+=g.top)):(c=f.x-e.x-g.left,f=f.y-e.y-g.top);var g=b.clientHeight-d.offsetHeight,e=b.scrollLeft,h=b.scrollTop,e=e+Math.min(c,Math.max(c-
(b.clientWidth-d.offsetWidth),0)),h=h+Math.min(f,Math.max(f-g,0)),d=new E(e,h);a.scrollLeft=d.x;a.scrollTop=d.y}}k.C=function(a){if(-1==a)gd(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){gd(this,b);break}};
function hd(a){if(!a.a){var b=a.l.b("DIV",{style:"display:none"});a.u&&(b.style.overflowY="auto");a.a=b;Pa(b,ua(a.className).split(" "));zb(b,"listbox");b.id=":"+(G.a().a++).toString(36);a.F.appendChild(b);R(b,"click",a.xa,!1,a);R(b,"mousedown",a.za,!1,a);R(b,"mouseover",a.Aa,!1,a)}}
function dd(a){hd(a);a.ta&&(a.a.style.minWidth=a.ta.clientWidth+"px");a.g.length=0;a.l.f(a.a);a.m&&a.m.Fa||B(a.c,function(a){var c=a;a=this.J;var d=this.l.b("DIV",{className:"ac-row",id:":"+(G.a().a++).toString(36)});zb(d,"option");if(!this.m||!this.m.Ga)if(c=c.data.toString(),"textContent"in d)d.textContent=c;else if(3==d.nodeType)d.data=c;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=c}else wb(d),d.appendChild(P(d).createTextNode(String(c)));
a&&this.$&&(this.aa=!1,id(this,d,a));Oa(d,"ac-row");this.g.push(d);this.a.appendChild(d)},a);0==a.c.length?a.v():(fd(a),jd(a),Jc(a.a))}
function jd(a){if(a.b&&a.K){var b=a.pa||a.b,c;c=a.sa?5:1;var d=65;a.u&&(a.a.style.height="",d|=32);a=a.a;var f=c^1,e,g;if(e=a.offsetParent){var h="HTML"==e.tagName||"BODY"==e.tagName;h&&"static"==W(e,"position")||(g=Y(e),h||(h=(h="rtl"==W(e,"direction"))&&J?-e.scrollLeft:!h||cb&&M("8")||"visible"==W(e,"overflowX")?e.scrollLeft:e.scrollWidth-e.clientWidth-e.scrollLeft,g=Za(g,new E(h,e.scrollTop))))}e=g||new E;g=Y(b);h=Gc(b);g=new $a(g.x,g.y,h.width,h.height);if(h=Ec(b)){var m=new $a(h.left,h.top,h.right-
h.left,h.bottom-h.top),h=Math.max(g.left,m.left),q=Math.min(g.left+g.width,m.left+m.width);if(h<=q){var y=Math.max(g.top,m.top),m=Math.min(g.top+g.height,m.top+m.height);y<=m&&(g.left=h,g.top=y,g.width=q-h,g.height=m-y)}}h=O(b);y=O(a);if(h.a!=y.a){q=h.a.body;var y=tb(y.a),m=new E(0,0),w;w=(w=P(q))?tb(w):window;if(sa(w,"parent")){var kb=q;do{var X;w==y?X=Y(kb):(X=Cc(kb),X=new E(X.left,X.top));m.x+=X.x;m.y+=X.y}while(w&&w!=y&&w!=w.parent&&(kb=w.frameElement)&&(w=w.parent))}q=Za(m,Y(q));!H||9<=Number(N)||
ub(h.a)||(q=Za(q,rb(h.a)));g.left+=q.x;g.top+=q.y}b=Pc(b,c);c=g.left;b&4?c+=g.width:b&2&&(c+=g.width/2);var b=new E(c,g.top+(b&1?g.height:0)),b=Za(b,e),l;d&&(l=Ec(a))&&(l.top-=e.y,l.right-=e.x,l.bottom-=e.y,l.left-=e.x);b=b.clone();e=Pc(a,f);f=Gc(a);c=f.clone();b=b.clone();c=c.clone();g=0;0!=e&&(e&4?b.x-=c.width+0:e&2&&(b.x-=c.width/2),e&1&&(b.y-=c.height+0));d&&(l?(e=b,g=c,h=0,65==(d&65)&&(e.x<l.left||e.x>=l.right)&&(d&=-2),132==(d&132)&&(e.y<l.top||e.y>=l.bottom)&&(d&=-5),e.x<l.left&&d&1&&(e.x=
l.left,h|=1),d&16&&(q=e.x,e.x<l.left&&(e.x=l.left,h|=4),e.x+g.width>l.right&&(g.width=Math.min(l.right-e.x,q+g.width-l.left),g.width=Math.max(g.width,0),h|=4)),e.x+g.width>l.right&&d&1&&(e.x=Math.max(l.right-g.width,l.left),h|=1),d&2&&(h|=(e.x<l.left?16:0)|(e.x+g.width>l.right?32:0)),e.y<l.top&&d&4&&(e.y=l.top,h|=2),d&32&&(q=e.y,e.y<l.top&&(e.y=l.top,h|=8),e.y+g.height>l.bottom&&(g.height=Math.min(l.bottom-e.y,q+g.height-l.top),g.height=Math.max(g.height,0),h|=8)),e.y+g.height>l.bottom&&d&4&&(e.y=
Math.max(l.bottom-g.height,l.top),h|=2),d&8&&(h|=(e.y<l.top?64:0)|(e.y+g.height>l.bottom?128:0)),d=h):d=256,g=d);d=new $a(0,0,0,0);d.left=b.x;d.top=b.y;d.width=c.width;d.height=c.height;g&496||(b=new E(d.left,d.top),b instanceof E?(l=b.x,b=b.y):(l=b,b=void 0),a.style.left=Fc(l),a.style.top=Fc(b),c=new A(d.width,d.height),f==c||f&&c&&f.width==c.width&&f.height==c.height||(d=c,l=ub(O(P(a)).a),!H||M("10")||l&&M("8")?(a=a.style,J?a.MozBoxSizing="border-box":K?a.WebkitBoxSizing="border-box":a.boxSizing=
"border-box",a.width=Math.max(d.width,0)+"px",a.height=Math.max(d.height,0)+"px"):(f=a.style,l?(H?(l=Lc(a,"paddingLeft"),b=Lc(a,"paddingRight"),c=Lc(a,"paddingTop"),e=Lc(a,"paddingBottom"),l=new F(c,b,e,l)):(l=V(a,"paddingLeft"),b=V(a,"paddingRight"),c=V(a,"paddingTop"),e=V(a,"paddingBottom"),l=new F(parseFloat(c),parseFloat(b),parseFloat(e),parseFloat(l))),a=Oc(a),f.pixelWidth=d.width-a.left-l.left-l.right-a.right,f.pixelHeight=d.height-a.top-l.top-l.bottom-a.bottom):(f.pixelWidth=d.width,f.pixelHeight=
d.height))))}}
function id(a,b,c){if(!a.aa)if(3==b.nodeType){var d=null;p(c)&&1<c.length&&(d=La(c,1));c=kd(c);if(0!=c.length){var f=b.nodeValue,e=new RegExp("\\b(?:"+c+")","gi");c=[];for(var g=0,h=e.exec(f),m=0;h;)m++,c.push(f.substring(g,h.index)),c.push(f.substring(h.index,e.lastIndex)),g=e.lastIndex,h=e.exec(f);c.push(f.substring(g));if(1<c.length){for(d=0;1>d;d++)f=2*d,b.nodeValue=c[f],e=a.l.a.createElement("B"),e.className=a.qa,e.appendChild(a.l.a.createTextNode(String(c[f+1]))),e=b.parentNode.insertBefore(e,b.nextSibling),
b.parentNode.insertBefore(a.l.a.createTextNode(""),e.nextSibling),b=e.nextSibling;b.nodeValue=La(c,2).join("");a.aa=!0}else d&&id(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,id(a,b,c),b=d}function kd(a){var b="";if(!a)return b;p(a)&&(a=Ha(a,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));p(a)?b=0<a.length?Da(a[0]):"":/^\W/.test(a)||(b=Da(a));return b}function ld(a,b){for(;b&&b!=a.a&&!Na(b,"ac-row");)b=b.parentNode;return b?Ga(a.g,b):-1}
k.xa=function(a){var b=ld(this,a.a);0<=b&&U(this,{type:Tc,D:this.c[b].id});a.stopPropagation()};k.za=function(a){a.stopPropagation();a.preventDefault()};k.Aa=function(a){a=ld(this,a.a);0<=a&&!(300>u()-this.Z)&&U(this,{type:Sc,D:this.c[a].id})};var md=D("iPhone")&&!D("iPod")&&!D("iPad")||D("iPod"),nd=D("iPad");function od(a,b,c,d){x.call(this);d=d||150;this.c=null!=c?c:!0;this.i=a||",;";this.o=this.i.substring(0,1);a=this.c?"[\\s"+this.i+"]+":"[\\s]+";this.w=new RegExp("^"+a+"|"+a+"$","g");this.F=new RegExp("\\s*["+this.i+"]$");this.m=b||"";this.u=this.c;this.f=0<d?new Qc(d):null;this.b=new Ub(this);this.g=new Ub(this);this.j=new uc;this.l=-1}v(od,x);var pd=(md||nd)&&!M("533.17.9");k=od.prototype;k.h=null;k.U="";k.B=!1;k.W=!1;k.X=function(a){this.h.value=a};
k.va=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];ca(c)&&1==c.nodeType&&(zb(c,"combobox"),Ab(c,"autocomplete","list"));this.b.f(c,"focus",this.ca);this.b.f(c,"blur",this.wa);if(!this.h&&(this.g.f(c,"keydown",this.Ca),ca(c)&&1==c.nodeType)){var d;a:{var f=P(c);try{d=f&&f.activeElement;break a}catch(e){}d=null}d==c&&qd(this,c)}}};
function rd(a,b){switch(b.keyCode){case 40:if(a.a.c.j){$c(a.a);b.preventDefault();return}if(!a.c){a.update(!0);b.preventDefault();return}break;case 38:if(a.a.c.j){a:{a=a.a;for(var c=a.g,d=0;d<a.b.length;d++){if(c>a.a)c--;else break;if(a.C(c))break a}}b.preventDefault();return}break;case 9:if(!a.a.c.j||b.j)a.a.v();else if(a.update(),Xc(a.a)&&a.u){b.preventDefault();return}break;case 13:if(a.a.c.j){if(a.update(),Xc(a.a)){b.preventDefault();b.stopPropagation();return}}else a.a.v();break;case 27:if(a.a.c.j){a.a.v();
b.preventDefault();b.stopPropagation();return}break;case 229:if(!a.B){a.B||(a.b.f(a.h,"keyup",a.ga),a.b.f(a.h,"keypress",a.fa),a.B=!0);return}}sd(a,b)}function sd(a,b){var c=a.c&&b.g&&-1!=a.i.indexOf(String.fromCharCode(b.g));c&&a.update();c&&Xc(a.a)&&b.preventDefault()}k.ya=function(){return!1};k.ca=function(a){qd(this,a.a||null)};
function qd(a,b){Wb(a.g);a.a&&Yc(a.a);b!=a.h&&(a.h=b,a.f&&(b=a.f,b.g=!0,b.a||(b.a=b.b.setTimeout(b.l,b.c),b.m=u()),a.b.f(a.f,"tick",a.ja)),a.U=a.h.value,vc(a.j,a.h),a.b.f(a.j,"key",a.ha),a.b.f(a.h,"mousedown",a.ia),H&&a.b.f(a.h,"keypress",a.ea))}k.wa=function(){pd?window.setTimeout(t(this.ka,this),0):this.ka()};
k.ka=function(){if(this.h){this.b.i(this.j,"key",this.ha);Bc(this.j);this.b.i(this.h,"keyup",this.ya);this.b.i(this.h,"mousedown",this.ia);H&&this.b.i(this.h,"keypress",this.ea);this.B&&td(this);this.h=null;if(this.f){var a=this.f;a.g=!1;a.a&&(a.b.clearTimeout(a.a),a.a=null);this.b.i(this.f,"tick",this.ja)}this.a&&Zc(this.a)}};k.ja=function(){this.update()};k.Ca=function(a){this.ca(a)};k.ha=function(a){this.l=a.keyCode;this.a&&rd(this,a)};k.fa=function(){this.B&&229!=this.l&&td(this)};
k.ga=function(a){this.B&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&td(this)};k.ia=function(){};function td(a){a.B&&(a.B=!1,a.b.i(a.h,"keypress",a.fa),a.b.i(a.h,"keyup",a.ga))}k.ea=function(a){sd(this,a)};
k.update=function(a){if(this.h&&(a||this.h.value!=this.U)){if(a||!this.W){var b;a=Cb(this.h)[0];b=this.h.value;a=bd(this,b)[ad(this,b,a)];b=this.w?String(a).replace(this.w,""):a;if(this.a&&(this.a.o=this.h,a=this.a,a.m!=b)){a.m=b;var c=a.u;b=a.m;var d=a.F,f=t(a.Ba,a),c=c.a,e=[];if(""!=b)for(var g=Da(b),g=new RegExp("(^|\\W+)"+g,"i"),h=0;h<c.length&&e.length<d;h++){var m=c[h];String(m).match(g)&&e.push(m)}f(b,e);Yc(a)}}this.U=this.h.value}this.W=!1};
function ad(a,b,c){a=bd(a,b);if(c==b.length)return a.length-1;for(var d=b=0,f=0;d<a.length&&f<=c;d++)f+=a[d].length,b=d;return b}function bd(a,b){if(!a.c)return[b];b=String(b).split("");for(var c=[],d=[],f=0,e=!1;f<b.length;f++)a.m&&-1!=a.m.indexOf(b[f])?(e||(c.push(d.join("")),d.length=0),d.push(b[f]),e=!e):e||-1==a.i.indexOf(b[f])?d.push(b[f]):(d.push(b[f]),c.push(d.join("")),d.length=0);c.push(d.join(""));return c};function ud(a){return a[a.length-1]}
function vd(a,b,c){var d=ud(c.qualifiedName.split(/\./));b.set(c.qualifiedName,c.href);a.push(c.qualifiedName);c.types&&c.types.forEach(function(c){return vd(a,b,c)});c.statics&&c.statics.forEach(function(f){var e=c.href+"#"+f;0!=f.lastIndexOf(c.qualifiedName+".",0)&&(0==f.lastIndexOf(d+".",0)&&(f=f.substring(d.length+1)),f=c.qualifiedName+"."+f);b.set(f,e);a.push(f)});c.members&&c.members.forEach(function(d){b.set(c.qualifiedName+"#"+d,c.href+"#"+d);a.push(c.qualifiedName+"#"+d)})}
function wd(a,b){var c=b.ownerDocument.createElement("div");c.classList.add("dossier-ac");c.ownerDocument.body.appendChild(c);a=new ab(a);var c=new cd(c),d=new od(null,null,!1);a=new Rc(a,c,d);a.F=10;d.a=a;d.va(b);c.K=!1;c.u=!0;c.$=!0;return a}
function xd(a){var b=sc;function c(){var a=d.get(e.value);a&&(window.location.href=b+a)}var d=new Map,f=[];a.types&&a.types.forEach(function(a){return vd(f,d,a)});a.modules&&a.modules.forEach(function(a){return vd(f,d,a)});a=document.querySelector("header form");R(a,"submit",function(a){a.preventDefault();a.stopPropagation();c();return!1});var e=a.querySelector("input");e.setAttribute("title","Search (/ or "+(L?"⌘":"Ctrl+")+"E)");(a=a.querySelector(".material-icons"))&&R(a,"click",function(){return e.focus()});
a=wd(f,e);R(a,"update",c);return e};function yd(){var a=n.TYPES,b=xd(a),a=rc(a);tc(a,b);zd();Ad();setTimeout(Bd,0);setTimeout(Cd,0);setTimeout(a.g.bind(a),0)}var Dd=["init"],Z=n;Dd[0]in Z||!Z.execScript||Z.execScript("var "+Dd[0]);for(var Ed;Dd.length&&(Ed=Dd.shift());)Dd.length||void 0===yd?Z[Ed]?Z=Z[Ed]:Z=Z[Ed]={}:Z[Ed]=yd;
var sc=function(){var a="";Ia(document.querySelectorAll("script"),function(b){b=b.getAttribute("src");var c=b.length;return"dossier.js"===b.slice(c-10)?(a=b.slice(0,c-10),!0):!1});var b=a.split(/\.\.\//).length,c=window.location.pathname.split(/\//);c.splice(c.length-b,b);b=c.join("/");ta(b)||(b+="/");return b}();
function zd(){var a=document.querySelectorAll(".content > main > article");if(a.length){var b=Fa(location.pathname.split(/\//)),c=Ia(a,function(a){return a.dataset&&a.dataset.filename===b});c&&(B(a,function(a){a!==c&&a&&a.parentNode&&a.parentNode.removeChild(a)}),c.style.display="",document.title=c.dataset.name)}}function Cd(){var a=document.querySelector(":target");a&&(a=a.getBoundingClientRect(),56>a.top&&(document.querySelector(".content").scrollTop-=64-a.top))}
function Ad(){function a(a){a=yb(a,function(a){return"TR"===a.nodeName});Oa(a,"hilite")}var b=document.querySelector("article.srcfile table");if(b){if(location.hash){var c=document.querySelector("tr > td a"+location.hash);c&&a(c)}R(window,"hashchange",function(){B(b.querySelectorAll("tr.hilite"),function(a){Qa(a,"hilite")});var c=b.querySelector("tr > td a:target");c&&a(c)})}}
function Bd(){function a(){var a=document.querySelector(".property.expandable:target");a&&a.classList.add("open")}B(document.querySelectorAll(".property.expandable > .header:first-child"),function(a){var c=a.parentNode;c&&c.classList.contains("property")&&R(a,"click",function(){return c.classList.toggle("open")})});a();R(window,"hashchange",a)};;init();}).call(this);
