(function(){'use strict';var k,p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function q(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
function aa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function r(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}r("String.prototype.repeat",function(a){return a?a:function(a){var b=aa(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});
r("String.prototype.endsWith",function(a){return a?a:function(a,c){var b=aa(this,a,"endsWith");a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var e=a.length;0<e&&0<c;)if(b[--c]!=a[--e])return!1;return 0>=e}});r("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});function ca(){ca=function(){};p.Symbol||(p.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function ia(a){fa();var b=a[Symbol.iterator];return b?b.call(a):ga(a)}
function ja(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(a){this.a=(f+=Math.random()+1).toString();if(a){ca();fa();a=ia(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}function c(a){ja(a,e)||ba(a,e,{value:{}})}function d(a){var b=Object[a];b&&(Object[a]=function(a){c(a);return b(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(l){return!1}}())return a;
var e="$jscomp_hidden_"+Math.random().toString().substring(2);d("freeze");d("preventExtensions");d("seal");var f=0;b.prototype.set=function(a,b){c(a);if(!ja(a,e))throw Error("WeakMap key fail: "+a);a[e][this.a]=b;return this};b.prototype.get=function(a){return ja(a,e)?a[e][this.a]:void 0};b.prototype.has=function(a){return ja(a,e)&&ja(a[e],this.a)};b.prototype.delete=function(a){return ja(a,e)&&ja(a[e],this.a)?delete a[e][this.a]:!1};return b});
r("Map",function(a){function b(){var a={};return a.O=a.next=a.head=a}function c(a,b){var c=a.a;return ha(function(){if(c){for(;c.head!=a.a;)c=c.O;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})}function d(a,b){var c;c=b&&typeof b;"object"==c||"function"==c?f.has(b)?c=f.get(b):(c=""+ ++g,f.set(b,c)):c="p_"+b;var d=a.b[c];if(d&&ja(a.b,c))for(a=0;a<d.length;a++){var e=d[a];if(b!==b&&e.key!==e.key||b===e.key)return{id:c,list:d,index:a,w:e}}return{id:c,list:d,
index:-1,w:void 0}}function e(a){this.b={};this.a=b();this.size=0;if(a){a=ia(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(ia([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?
!1:!0}catch(x){return!1}}())return a;ca();fa();var f=new WeakMap;e.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.b[c.id]=[]);c.w?c.w.value=b:(c.w={next:this.a,O:this.a.O,head:this.a,key:a,value:b},c.list.push(c.w),this.a.O.next=c.w,this.a.O=c.w,this.size++);return this};e.prototype.delete=function(a){a=d(this,a);return a.w&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.b[a.id],a.w.O.next=a.w.next,a.w.next.O=a.w.O,a.w.head=null,this.size--,!0):!1};e.prototype.clear=
function(){this.b={};this.a=this.a.O=b();this.size=0};e.prototype.has=function(a){return!!d(this,a).w};e.prototype.get=function(a){return(a=d(this,a).w)&&a.value};e.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return c(this,function(a){return a.key})};e.prototype.values=function(){return c(this,function(a){return a.value})};e.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};
e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});r("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)ja(e,f)&&(a[f]=e[f])}return a}});r("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=aa(this,a,"startsWith");a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var g=0;g<f&&c<e;)if(b[c++]!=a[g++])return!1;return g>=f}});
r("Array.from",function(a){return a?a:function(a,c,d){fa();c=c?c:function(a){return a};var b=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)b.push(c.call(d,f.value));else for(var f=a.length,g=0;g<f;g++)b.push(c.call(d,a[g]));return b}});
r("Set",function(a){function b(a){this.a=new Map;if(a){a=ia(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.a.size}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(ia([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?
!1:e.next().done}catch(g){return!1}}())return a;ca();fa();b.prototype.add=function(a){this.a.set(a,a);this.size=this.a.size;return this};b.prototype.delete=function(a){a=this.a.delete(a);this.size=this.a.size;return a};b.prototype.clear=function(){this.a.clear();this.size=0};b.prototype.has=function(a){return this.a.has(a)};b.prototype.entries=function(){return this.a.entries()};b.prototype.values=function(){return this.a.values()};b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=
function(a,b){var c=this;this.a.forEach(function(d){return a.call(b,d,d,c)})};return b});var t=this;function ka(){}
function la(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){return"array"==la(a)}function ma(a){var b=la(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function na(a){return"function"==la(a)}function oa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var pa="closure_uid_"+(1E9*Math.random()>>>0),qa=0;function ra(a,b,c){return a.call.apply(a.bind,arguments)}
function sa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ta(a,b,c){ta=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ra:sa;return ta.apply(null,arguments)}var ua=Date.now||function(){return+new Date};
function w(a,b){function c(){}c.prototype=b.prototype;a.Qa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.l=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var va;function wa(a,b,c){this.c=c;this.f=a;this.g=b;this.b=0;this.a=null}wa.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.f();return a};function xa(a,b){a.g(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};function ya(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ya);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(ya,Error);ya.prototype.name="CustomError";function za(){0!=Aa&&(this[pa]||(this[pa]=++qa));this.ca=this.ca;this.Ua=this.Ua}var Aa=0;za.prototype.ca=!1;var Ba;function Ca(a,b){this.type=a;this.f=this.target=b;this.i=!1;this.Oa=!0}Ca.prototype.c=function(){this.i=!0};Ca.prototype.preventDefault=function(){this.Oa=!1};var Da="closure_listenable_"+(1E6*Math.random()|0),Ea=0;function Fa(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.fa=!!d;this.ga=e;this.key=++Ea;this.Y=this.ea=!1}function Ga(a){a.Y=!0;a.listener=null;a.a=null;a.src=null;a.ga=null};function Ha(a,b){this.width=a;this.height=b}Ha.prototype.clone=function(){return new Ha(this.width,this.height)};Ha.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};Ha.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Ha.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Ia(){};function Ja(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var Ka="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function La(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ka.length;f++)c=Ka[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ma(a){Ma[" "](a);return a}Ma[" "]=ka;function Na(a,b){try{return Ma(a[b]),!0}catch(c){}return!1}function Oa(a,b){var c=Pa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function Ra(a){if(!Sa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ta,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ua,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Va,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Wa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Xa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ya,"&#0;"));return a}var Ta=/&/g,Ua=/</g,Va=/>/g,Wa=/"/g,Xa=/'/g,Ya=/\x00/g,Sa=/[\x00&<>"']/;
function Za(){return-1!=$a.toLowerCase().indexOf("webkit")}function ab(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function bb(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^ua()).toString(36)}function cb(a,b){return a<b?-1:a>b?1:0};function db(a){return a[a.length-1]}
var eb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(v(a))return v(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},fb=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=v(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var m=g[h];b.call(c,m,h,a)&&(e[f++]=m)}return e},gb=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
function hb(a,b){a:{for(var c=a.length,d=v(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:v(a)?a.charAt(b):a[b]}function ib(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function jb(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var kb=function(){var a="";hb(document.querySelectorAll("script"),function(b){b=b.getAttribute("src");if(!b)return!1;var c=b.length;return"dossier.js"===b.slice(c-10)?(a=b.slice(0,c-10),!0):!1});var b=a.split(/\.\.\//).length,c=window.location.pathname.split(/\//);c.splice(c.length-b,b);b=c.join("/");b.endsWith("/")||(b+="/");return b}();var mb=new wa(function(){return new lb},function(a){a.reset()},100);function nb(){var a=ob,b=null;a.a&&(b=a.a,a.a=a.a.next,a.a||(a.b=null),b.next=null);return b}function lb(){this.next=this.a=this.I=null}lb.prototype.set=function(a,b){this.I=a;this.a=b;this.next=null};lb.prototype.reset=function(){this.next=this.a=this.I=null};function pb(a){if(a.classList)return a.classList;a=a.className;return v(a)&&a.match(/\S+/g)||[]}function qb(a,b){return a.classList?a.classList.contains(b):0<=eb(pb(a),b)}function rb(a,b){a.classList?a.classList.add(b):qb(a,b)||(a.className+=0<a.className.length?" "+b:b)}function sb(a,b){if(a.classList)y(b,function(b){rb(a,b)});else{var c={};y(pb(a),function(a){c[a]=!0});y(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function tb(a,b){a.classList?a.classList.remove(b):qb(a,b)&&(a.className=fb(pb(a),function(a){return a!=b}).join(" "))}function ub(a){var b=["ac-active","active"];a.classList?y(b,function(b){tb(a,b)}):a.className=fb(pb(a),function(a){return!(0<=eb(b,a))}).join(" ")};function vb(a){this.src=a;this.a={};this.b=0}function wb(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.b++);var g=xb(b,c,d,e);-1<g?(a=b[g],a.ea=!1):(a=new Fa(c,a.src,f,!!d,e),a.ea=!1,b.push(a));return a}function yb(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=eb(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(Ga(b),a.a[c].length||(delete a.a[c],a.b--))}}function zb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=xb(a,c,d,e));return-1<b?a[b]:null}
function xb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Y&&f.listener==b&&f.fa==!!c&&f.ga==d)return e}return-1};var $a;a:{var Ab=t.navigator;if(Ab){var Bb=Ab.userAgent;if(Bb){$a=Bb;break a}}$a=""}function z(a){return-1!=$a.indexOf(a)};function Cb(a){t.setTimeout(function(){throw a;},0)}var Db;
function Eb(){var a=t.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!z("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=ta(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!z("Trident")&&!z("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.za;c.za=null;a()}};return function(a){d.next={za:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){t.setTimeout(a,0)}};function Fb(a,b){Gb||Hb();Ib||(Gb(),Ib=!0);var c=ob,d=mb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d}var Gb;function Hb(){if(t.Promise&&t.Promise.resolve){var a=t.Promise.resolve(void 0);Gb=function(){a.then(Jb)}}else Gb=function(){var a=Jb;!na(t.setImmediate)||t.Window&&t.Window.prototype&&!z("Edge")&&t.Window.prototype.setImmediate==t.setImmediate?(Db||(Db=Eb()),Db(a)):t.setImmediate(a)}}var Ib=!1,ob=new function(){this.b=this.a=null};
function Jb(){for(var a;a=nb();){try{a.I.call(a.a)}catch(b){Cb(b)}xa(mb,a)}Ib=!1};function B(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}B.prototype.clone=function(){return new B(this.x,this.y)};function Kb(a,b){return new B(a.x-b.x,a.y-b.y)}B.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};B.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};B.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function Lb(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}k=Lb.prototype;k.clone=function(){return new Lb(this.top,this.right,this.bottom,this.left)};k.contains=function(a){return this&&a?a instanceof Lb?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
k.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};k.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};k.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function Mb(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}k=Mb.prototype;k.clone=function(){return new Mb(this.left,this.top,this.width,this.height)};k.contains=function(a){return a instanceof B?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
k.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};k.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};k.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Nb;function Ob(){}w(Ob,Ia);function Pb(a){var b;a:{if(!a.a&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0;d<c.length;d++){var e=c[d];try{new ActiveXObject(e);b=a.a=e;break a}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}b=a.a}return b?new ActiveXObject(b):new XMLHttpRequest}Nb=new Ob;function D(a,b){this.a=Qb;this.h=void 0;this.c=this.b=this.f=null;this.g=this.i=!1;if(a!=ka)try{var c=this;a.call(b,function(a){Rb(c,Sb,a)},function(a){Rb(c,Tb,a)})}catch(d){Rb(this,Tb,d)}}var Qb=0,Sb=2,Tb=3;function Ub(){this.next=this.b=this.a=this.f=this.D=null;this.c=!1}Ub.prototype.reset=function(){this.b=this.a=this.f=this.D=null;this.c=!1};var Vb=new wa(function(){return new Ub},function(a){a.reset()},100);function Wb(a,b,c){var d=Vb.get();d.f=a;d.a=b;d.b=c;return d}
function Xb(){var a=new D(ka);Rb(a,Sb,void 0);return a}function Yb(){var a=Error("failed to resolve URL");return new D(function(b,c){c(a)})}D.prototype.then=function(a,b,c){return Zb(this,na(a)?a:null,na(b)?b:null,c)};D.prototype.then=D.prototype.then;D.prototype.$goog_Thenable=!0;function $b(a){a.a==Qb&&Fb(function(){var a=new ac(void 0);bc(this,a)},a)}
function bc(a,b){if(a.a==Qb)if(a.f){var c=a.f;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.c||(d++,g.D==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(c.a==Qb&&1==d?bc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):cc(c),dc(c,e,Tb,b)))}a.f=null}else Rb(a,Tb,b)}function ec(a,b){a.b||a.a!=Sb&&a.a!=Tb||fc(a);a.c?a.c.next=b:a.b=b;a.c=b}
function Zb(a,b,c,d){var e=Wb(null,null,null);e.D=new D(function(a,g){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(l){g(l)}}:a;e.a=c?function(b){try{var e=c.call(d,b);void 0===e&&b instanceof ac?g(b):a(e)}catch(l){g(l)}}:g});e.D.f=a;ec(a,e);return e.D}D.prototype.m=function(a){this.a=Qb;Rb(this,Sb,a)};D.prototype.u=function(a){this.a=Qb;Rb(this,Tb,a)};
function Rb(a,b,c){if(a.a==Qb){a===c&&(b=Tb,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.m,g=a.u;if(e instanceof D)ec(e,Wb(f||ka,g||null,a)),d=!0;else{var h;if(e)try{h=!!e.$goog_Thenable}catch(l){h=!1}else h=!1;if(h)e.then(f,g,a),d=!0;else{if(oa(e))try{var m=e.then;if(na(m)){gc(e,m,f,g,a);d=!0;break a}}catch(l){g.call(a,l);d=!0;break a}d=!1}}}d||(a.h=c,a.a=b,a.f=null,fc(a),b!=Tb||c instanceof ac||hc(a,c))}}
function gc(a,b,c,d,e){function f(a){h||(h=!0,d.call(e,a))}function g(a){h||(h=!0,c.call(e,a))}var h=!1;try{b.call(a,g,f)}catch(m){f(m)}}function fc(a){a.i||(a.i=!0,Fb(a.j,a))}function cc(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b}D.prototype.j=function(){for(var a;a=cc(this);)dc(this,a,this.a,this.h);this.i=!1};
function dc(a,b,c,d){if(c==Tb&&b.a&&!b.c)for(;a&&a.g;a=a.f)a.g=!1;if(b.D)b.D.f=null,ic(b,c,d);else try{b.c?b.f.call(b.b):ic(b,c,d)}catch(e){jc.call(null,e)}xa(Vb,b)}function ic(a,b,c){b==Sb?a.f.call(a.b,c):a.a&&a.a.call(a.b,c)}function hc(a,b){a.g=!0;Fb(function(){a.g&&jc.call(null,b)})}var jc=Cb;function ac(a){ya.call(this,a)}w(ac,ya);ac.prototype.name="cancel";function kc(){this.a=lc}kc.prototype.oa=!0;kc.prototype.ma=function(){return""};kc.prototype.na=!0;kc.prototype.aa=function(){return 1};var lc={};function mc(){this.a=nc}mc.prototype.oa=!0;mc.prototype.ma=function(){return""};mc.prototype.na=!0;mc.prototype.aa=function(){return 1};var nc={};function oc(){this.a="";this.f=pc;this.b=null}oc.prototype.na=!0;oc.prototype.aa=function(){return this.b};oc.prototype.oa=!0;oc.prototype.ma=function(){return this.a};function qc(a){return a instanceof oc&&a.constructor===oc&&a.f===pc?a.a:"type_error:SafeHtml"}function rc(a){if(a instanceof oc)return a;var b=null;a.na&&(b=a.aa());a=Ra(a.oa?a.ma():String(a));return sc(a,b)}
function tc(a){function b(a){u(a)?y(a,b):(a=rc(a),d+=qc(a),a=a.aa(),0==c?c=a:0!=a&&c!=a&&(c=null))}var c=0,d="";y(arguments,b);return sc(d,c)}var pc={};function sc(a,b){var c=new oc;c.a=a;c.b=b;return c}sc("<!DOCTYPE html>",0);sc("",0);var uc=sc("<br>",0);var vc={},wc={},xc={},yc={},zc={};function E(){throw Error("Do not instantiate directly");}E.prototype.K=null;E.prototype.toString=function(){return this.content};function Ac(){E.call(this)}w(Ac,E);function Bc(){E.call(this)}w(Bc,E);function Cc(a){this.a=a||[]};function Dc(){}Dc.a=function(){return Dc.b?Dc.b:Dc.b=new Dc};Dc.prototype.a=0;var Ec=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;var Fc=z("Opera"),F=z("Trident")||z("MSIE"),G=z("Edge"),Gc=G||F,Hc=z("Gecko")&&!(Za()&&!z("Edge"))&&!(z("Trident")||z("MSIE"))&&!z("Edge"),H=Za()&&!z("Edge"),I=z("Macintosh");function Ic(){var a=t.document;return a?a.documentMode:void 0}var Jc;
a:{var Kc="",Lc=function(){var a=$a;if(Hc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(G)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(H)return/WebKit\/(\S+)/.exec(a);if(Fc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Lc&&(Kc=Lc?Lc[1]:"");if(F){var Mc=Ic();if(null!=Mc&&Mc>parseFloat(Kc)){Jc=String(Mc);break a}}Jc=Kc}var Pa={};
function Nc(a){return Oa(a,function(){for(var b=0,c=Qa(String(Jc)).split("."),d=Qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;!b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=cb(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||cb(0==g[2].length,0==h[2].length)||cb(g[2],h[2]);g=g[3];h=h[3]}while(!b)}return 0<=b})}var Oc;var Pc=t.document;
Oc=Pc&&F?Ic()||("CSS1Compat"==Pc.compatMode?parseInt(Jc,10):5):void 0;var Qc=!F||9<=Number(Oc);function Rc(a){return a?new Sc(Tc(a)):Ba||(Ba=new Sc)}function Uc(a,b){Ja(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Vc.hasOwnProperty(d)?a.setAttribute(Vc[d],b):d.lastIndexOf("aria-",0)&&d.lastIndexOf("data-",0)?a[d]=b:a.setAttribute(d,b)})}
var Vc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Wc(a){var b=Xc(a);a=Yc(a);return F&&Nc("10")&&a.pageYOffset!=b.scrollTop?new B(b.scrollLeft,b.scrollTop):new B(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}
function Xc(a){return a.scrollingElement?a.scrollingElement:!H&&Zc(a)?a.documentElement:a.body||a.documentElement}function Yc(a){return a.parentWindow||a.defaultView}
function $c(a,b,c){function d(c){c&&b.appendChild(v(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!ma(f)||oa(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(oa(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if(na(f)){g="function"==typeof f.item;break a}}g=!1}y(g?ib(f):f,d)}}}function Zc(a){return"CSS1Compat"==a.compatMode}function ad(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Tc(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function bd(a,b){for(var c=0;a&&4>=c;){if(b(a))return a;a=a.parentNode;c++}return null}function Sc(a){this.a=a||t.document||document}
Sc.prototype.b=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),g=e[1];if(!Qc&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',Ra(g.name),'"');if(g.type){f.push(' type="',Ra(g.type),'"');var h={};La(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=d.createElement(f);g&&(v(g)?f.className=g:u(g)?f.className=g.join(" "):Uc(f,g));2<e.length&&$c(d,f,e);return f};Sc.prototype.f=ad;
Sc.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function cd(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function dd(a,b,c){u(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(va||(va={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=va,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function ed(a,b){var c="";b&&(c=b.id);dd(a,"activedescendant",c)};function fd(a){var b=0,c=0;if(gd(a))b=a.selectionStart,c=-1;else if(F){var d=hd(a),e=d[0],d=d[1];if(e.inRange(d)){e.setEndPoint("EndToStart",d);if("textarea"==a.type){d.duplicate();b=a=e.text;for(c=!1;!c;)0==e.compareEndPoints("StartToEnd",e)?c=!0:(e.moveEnd("character",-1),e.text==a?b+="\r\n":c=!0);e=[b.length,-1];return e}b=e.text.length;c=-1}}return[b,c]}
function hd(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function id(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function gd(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};var jd=!F||9<=Number(Oc),kd=F&&!Nc("9");function ld(a,b){Ca.call(this,a?a.type:"");this.f=this.target=null;this.u=this.a=this.clientY=this.clientX=0;this.j=this.m=this.b=this.g=!1;this.h=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.f=b;(b=a.relatedTarget)&&Hc&&Na(b,"nodeName");d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:
a.pageY);this.a=a.keyCode||0;this.u=a.charCode||("keypress"==c?a.keyCode:0);this.g=a.ctrlKey;this.b=a.altKey;this.m=a.shiftKey;this.j=a.metaKey;this.h=a;a.defaultPrevented&&this.preventDefault()}}w(ld,Ca);ld.prototype.c=function(){ld.Qa.c.call(this);this.h.stopPropagation?this.h.stopPropagation():this.h.cancelBubble=!0};
ld.prototype.preventDefault=function(){ld.Qa.preventDefault.call(this);var a=this.h;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,kd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var md="closure_lm_"+(1E6*Math.random()|0),nd={},od=0;
function J(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)J(a,b[f],c,d,e);return null}c=pd(c);if(a&&a[Da])a=a.b(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=qd(a);g||(a[md]=g=new vb(a));c=wb(g,b,c,d,e);if(!c.a){d=rd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(sd(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");od++}a=c}return a}
function rd(){var a=td,b=jd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function ud(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)ud(a,b[f],c,d,e);else c=pd(c),a&&a[Da]?a.g(b,c,d,e):a&&(a=qd(a))&&(b=zb(a,b,c,!!d,e))&&vd(b)}
function vd(a){if("number"!=typeof a&&a&&!a.Y){var b=a.src;if(b&&b[Da])yb(b.u,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.fa):b.detachEvent&&b.detachEvent(sd(c),d);od--;(c=qd(b))?(yb(c,a),c.b||(c.src=null,b[md]=null)):Ga(a)}}}function sd(a){return a in nd?nd[a]:nd[a]="on"+a}function wd(a,b,c,d){var e=!0;if(a=qd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.fa==c&&!f.Y&&(f=xd(f,d),e=e&&!1!==f)}return e}
function xd(a,b){var c=a.listener,d=a.ga||a.src;a.ea&&vd(a);return c.call(d,b)}
function td(a,b){if(a.Y)return!0;if(!jd){if(!b)a:{b=["window","event"];for(var c=t,d;d=b.shift();)if(null!=c[d])c=c[d];else{b=null;break a}b=c}d=b;b=new ld(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(!d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.f;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.i&&0<=e;e--){b.f=d[e];var f=wd(d[e],a,!0,b),c=c&&f}for(e=0;!b.i&&e<d.length;e++)b.f=d[e],f=wd(d[e],a,!1,b),c=
c&&f}return c}return xd(a,new ld(b,this))}function qd(a){a=a[md];return a instanceof vb?a:null}var yd="__closure_events_fn_"+(1E9*Math.random()>>>0);function pd(a){if(na(a))return a;a[yd]||(a[yd]=function(b){return a.handleEvent(b)});return a[yd]};function zd(a){za.call(this);this.f=a;this.a={}}w(zd,za);var Ad=[];zd.prototype.b=function(a,b,c,d){u(b)||(b&&(Ad[0]=b.toString()),b=Ad);for(var e=0;e<b.length;e++){var f=J(a,b[e],c||this.handleEvent,d||!1,this.f||this);if(!f)break;this.a[f.key]=f}return this};
zd.prototype.g=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.g(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.f||this,c=pd(c),d=!!d,b=a&&a[Da]?zb(a.u,String(b),c,d,e):a?(a=qd(a))?zb(a,b,c,d,e):null:null,b&&(vd(b),delete this.a[b.key]);return this};function Bd(a){Ja(a.a,function(a,c){this.a.hasOwnProperty(c)&&vd(a)},a);a.a={}}zd.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function K(){za.call(this);this.u=new vb(this);this.Ra=this;this.Z=null}w(K,za);K.prototype[Da]=!0;K.prototype.removeEventListener=function(a,b,c,d){ud(this,a,b,c,d)};
function L(a,b){var c,d=a.Z;if(d)for(c=[];d;d=d.Z)c.push(d);a=a.Ra;d=b.type||b;if(v(b))b=new Ca(b,a);else if(b instanceof Ca)b.target=b.target||a;else{var e=b;b=new Ca(d,a);La(b,e)}var e=!0,f;if(c)for(var g=c.length-1;!b.i&&0<=g;g--)f=b.f=c[g],e=Cd(f,d,!0,b)&&e;b.i||(f=b.f=a,e=Cd(f,d,!0,b)&&e,b.i||(e=Cd(f,d,!1,b)&&e));if(c)for(g=0;!b.i&&g<c.length;g++)f=b.f=c[g],e=Cd(f,d,!1,b)&&e;return e}K.prototype.b=function(a,b,c,d){return wb(this.u,String(a),b,c,d)};
K.prototype.g=function(a,b,c,d){var e;e=this.u;a=String(a).toString();if(a in e.a){var f=e.a[a];b=xb(f,b,c,d);-1<b?(Ga(f[b]),Array.prototype.splice.call(f,b,1),f.length||(delete e.a[a],e.b--),e=!0):e=!1}else e=!1;return e};function Cd(a,b,c,d){b=a.u.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.Y&&g.fa==c){var h=g.listener,m=g.ga||g.src;g.ea&&yb(a.u,g);e=!1!==h.call(m,d)&&e}}return e&&0!=d.Oa};function Dd(a,b,c,d,e,f){if(!(F||G||H&&Nc("525")))return!0;if(I&&e)return Ed(a);if(e&&!d)return!1;"number"==typeof b&&(b=Fd(b));e=17==b||18==b||I&&91==b;if((!c||I)&&e||I&&16==b&&(d||f))return!1;if((H||G)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(F&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!(H||G)}return Ed(a)}
function Ed(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(H||G)&&!a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function Fd(a){if(Hc)a=Gd(a);else if(I&&H)switch(a){case 93:a=91}return a}
function Gd(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function Hd(a,b){K.call(this);a&&Id(this,a,b)}w(Hd,K);k=Hd.prototype;k.ba=null;k.ha=null;k.ra=null;k.ia=null;k.H=-1;k.R=-1;k.ka=!1;
var Jd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Kd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Ld=F||G||H&&Nc("525"),Md=I&&Hc;
Hd.prototype.a=function(a){if(H||G)if(17==this.H&&!a.g||18==this.H&&!a.b||I&&91==this.H&&!a.j)this.R=this.H=-1;-1==this.H&&(a.g&&17!=a.a?this.H=17:a.b&&18!=a.a?this.H=18:a.j&&91!=a.a&&(this.H=91));Ld&&!Dd(a.a,this.H,a.m,a.g,a.b,a.j)?this.handleEvent(a):(this.R=Fd(a.a),Md&&(this.ka=a.b))};Hd.prototype.f=function(a){this.R=this.H=-1;this.ka=a.b};
Hd.prototype.handleEvent=function(a){var b=a.h,c,d,e=b.altKey;F&&"keypress"==a.type?(c=this.R,d=13!=c&&27!=c?b.keyCode:0):(H||G)&&"keypress"==a.type?(c=this.R,d=0<=b.charCode&&63232>b.charCode&&Ed(c)?b.charCode:0):Fc&&!H?(c=this.R,d=Ed(c)?b.keyCode:0):(c=b.keyCode||this.R,d=b.charCode||0,Md&&(e=this.ka),I&&63==d&&224==c&&(c=191));var f=c=Fd(c);c?63232<=c&&c in Jd?f=Jd[c]:25==c&&a.m&&(f=9):b.keyIdentifier&&b.keyIdentifier in Kd&&(f=Kd[b.keyIdentifier]);a=f==this.H;this.H=f;b=new Nd(f,d,a,b);b.b=e;
L(this,b)};function Id(a,b,c){a.ia&&Od(a);a.ba=b;a.ha=J(a.ba,"keypress",a,c);a.ra=J(a.ba,"keydown",a.a,c,a);a.ia=J(a.ba,"keyup",a.f,c,a)}function Od(a){a.ha&&(vd(a.ha),vd(a.ra),vd(a.ia),a.ha=null,a.ra=null,a.ia=null);a.ba=null;a.H=-1;a.R=-1}function Nd(a,b,c,d){ld.call(this,d);this.type="key";this.a=a;this.u=b;this.repeat=c}w(Nd,ld);function Pd(a){return Qd(a).then(function(a){return a.responseText})}
function Qd(a){return new D(function(b,c){var d={},e,f=d.pb?Pb(d.pb):Pb(Nb);try{f.open("GET",a,!0)}catch(m){c(new Rd("Error opening XHR: "+m.message,a))}f.onreadystatechange=function(){if(4==f.readyState){t.clearTimeout(e);var d;a:switch(f.status){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:d=!0;break a;default:d=!1}!d&&(d=!f.status)&&(d=a.match(Ec)[1]||null,!d&&t.self&&t.self.location&&(d=t.self.location.protocol,d=d.substr(0,d.length-1)),d=d?d.toLowerCase():"",d=!("http"==d||
"https"==d||""==d));d?b(f):c(new Sd(f.status,a))}};f.onerror=function(){c(new Rd("Network error",a))};if(d.headers)for(var g in d.headers){var h=d.headers[g];null!=h&&f.setRequestHeader(g,h)}d.withCredentials&&(f.withCredentials=d.withCredentials);d.responseType&&(f.responseType=d.responseType);d.jb&&f.overrideMimeType(d.jb);0<d.lb&&(e=t.setTimeout(function(){f.onreadystatechange=ka;f.abort();c(new Td(a))},d.lb));try{f.send(null)}catch(m){f.onreadystatechange=ka,t.clearTimeout(e),c(new Rd("Error sending XHR: "+
m.message,a))}})}function Rd(a,b){ya.call(this,a+", url="+b)}w(Rd,ya);Rd.prototype.name="XhrError";function Sd(a,b){Rd.call(this,"Request Failed, status="+a,b);this.status=a}w(Sd,Rd);Sd.prototype.name="XhrHttpError";function Td(a){Rd.call(this,"Request timed out",a)}w(Td,Rd);Td.prototype.name="XhrTimeoutError";function Ud(a,b){var c=Rc();a=a(b||Vd,void 0,void 0);b=Wd(a);if(a instanceof E)if(a.B===zc)a=rc(a.toString());else{if(a.B!==vc)throw Error("Sanitized content was not of kind TEXT or HTML.");a=sc(a.toString(),a.K||null)}else a=sc(b,null);c=c.a;b=a;a=c.createElement("DIV");F?(b=tc(uc,b),a.innerHTML=qc(b),a.removeChild(a.firstChild)):a.innerHTML=qc(b);if(1==a.childNodes.length)c=a.removeChild(a.firstChild);else for(c=c.createDocumentFragment();a.firstChild;)c.appendChild(a.firstChild);return c}
function Wd(a){if(!oa(a))return String(a);if(a instanceof E){if(a.B===vc)return a.content;if(a.B===zc)return Ra(a.content)}return"zSoyz"}var Vd={};function Xd(a){if(null!=a)switch(a.K){case 1:return 1;case -1:return-1;case 0:return 0}return null}function Yd(){E.call(this)}w(Yd,E);Yd.prototype.B=vc;function M(a){return null!=a&&a.B===vc?a:a instanceof oc?N(qc(a),a.aa()):N(Ra(String(String(a))),Xd(a))}function Zd(){E.call(this)}w(Zd,E);Zd.prototype.B={};Zd.prototype.K=1;function $d(){E.call(this)}w($d,E);$d.prototype.B=wc;$d.prototype.K=1;function ae(){E.call(this)}w(ae,E);ae.prototype.B=xc;ae.prototype.K=1;function be(){E.call(this)}w(be,E);
be.prototype.B=yc;be.prototype.K=1;function ce(){E.call(this)}w(ce,Bc);ce.prototype.B={};ce.prototype.K=1;function de(a,b){this.content=String(a);this.K=null!=b?b:null}w(de,Ac);de.prototype.B=zc;function ee(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a){return new b(String(a))}}var N=function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){a=new b(String(a));void 0!==d&&(a.K=d);return a}}(Yd);ee(Zd);var fe=ee($d);ee(ae);ee(be);ee(ce);
function ge(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a){return(a=String(a))?new b(a):""}}function he(a){return(a=String(a))?new de(a,void 0):""}var P=function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){a=String(a);if(!a)return"";a=new b(a);void 0!==d&&(a.K=d);return a}}(Yd);ge(Zd);ge(ae);ge($d);var ie=ge(be);ge(ce);function je(a){return null!=a&&a.B===vc?String(a.content).replace(ke,le):Ra(String(a))}
function Q(a){return null!=a&&a.B===vc?String(String(a.content).replace(me,"").replace(ne,"&lt;")).replace(ke,le):Ra(String(a))}function oe(a){null!=a&&a.B===yc?a=a.content.replace(/([^"'\s])$/,"$1 "):(a=String(a),a=pe.test(a)?a:"zSoyz");return a}
function qe(a){null!=a&&a.B===wc||null!=a&&a.B===xc?a=String(a).replace(re,se):a instanceof kc?(a=a instanceof kc&&a.constructor===kc&&a.a===lc?"":"type_error:SafeUrl",a=String(a).replace(re,se)):a instanceof mc?(a=a instanceof mc&&a.constructor===mc&&a.a===nc?"":"type_error:TrustedResourceUrl",a=String(a).replace(re,se)):(a=String(a),a=te.test(a)?a.replace(re,se):"about:invalid#zSoyz");return a}
var ue={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","":"&#133;"," ":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function le(a){return ue[a]}
var ve={"\x00":"%00","":"%01","":"%02","":"%03","":"%04","":"%05","":"%06","":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","":"%0E","":"%0F","":"%10","":"%11","":"%12","":"%13","":"%14","":"%15","":"%16","":"%17","":"%18","":"%19","":"%1A","":"%1B","":"%1C","":"%1D","":"%1E","":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","":"%7F","":"%C2%85"," ":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9",
"！":"%EF%BC%81","＃":"%EF%BC%83","＄":"%EF%BC%84","＆":"%EF%BC%86","＇":"%EF%BC%87","（":"%EF%BC%88","）":"%EF%BC%89","＊":"%EF%BC%8A","＋":"%EF%BC%8B","，":"%EF%BC%8C","／":"%EF%BC%8F","：":"%EF%BC%9A","；":"%EF%BC%9B","＝":"%EF%BC%9D","？":"%EF%BC%9F","＠":"%EF%BC%A0","［":"%EF%BC%BB","］":"%EF%BC%BD"};function se(a){return ve[a]}
var ke=/[\x00\x22\x27\x3c\x3e]/g,re=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,te=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,pe=/^(?!on|src|(?:style|action|archive|background|cite|classid|codebase|data|dsync|href|longdesc|usemap)\s*$)(?:[a-z0-9_$:-]*)$/i,me=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,ne=/</g;function R(a){this.a=a||{};this.f=new Map}R.prototype.toJSON=function(){var a=Object.assign({},this.a);this.f.forEach(function(b,c){return a[c]=b});return a};function we(a,b){if(a.f.has(b))return a.f.get(b);var c=a.a[b]||[];a.f.set(b,c);return c}function S(a,b,c){a.f.set(b,c)}function T(a,b,c){if(a.f.has(b))return a.f.get(b);var d=a.a[b];c=d?d.map(c):[];a.f.set(b,c);return c}function U(a,b,c){if(a.f.has(b))return a.f.get(b);var d=a.a[b];c=d?c(d):null;a.f.set(b,c);return c}
function xe(a,b,c){if(a.f.has(b))return a.f.get(b);c=c(a.a[b]||"");a.f.set(b,c);return c}function ye(a){R.call(this,a)}q(ye,R);p.Object.defineProperties(ye.prototype,{b:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},c:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||""},set:function(a){this.a[2]=a}},g:{configurable:!0,enumerable:!0,get:function(){return we(this,3)},set:function(a){S(this,3,a)}}});function ze(a){R.call(this,a)}
q(ze,R);p.Object.defineProperties(ze.prototype,{text:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},href:{configurable:!0,enumerable:!0,get:function(){return xe(this,2,fe)},set:function(a){S(this,2,a)}},b:{configurable:!0,enumerable:!0,get:function(){return xe(this,3,fe)},set:function(a){S(this,3,a)}}});function Ae(a){R.call(this,a)}q(Ae,R);
p.Object.defineProperties(Ae.prototype,{c:{configurable:!0,enumerable:!0,get:function(){return xe(this,1,fe)},set:function(a){S(this,1,a)}},b:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||0},set:function(a){this.a[2]=a}},uri:{configurable:!0,enumerable:!0,get:function(){return this.a[3]||""},set:function(a){this.a[3]=a}}});function V(a){R.call(this,a)}q(V,R);
p.Object.defineProperties(V.prototype,{b:{configurable:!0,enumerable:!0,get:function(){return T(this,1,function(a){return new Be(a)})},set:function(a){S(this,1,a)}}});function Be(a){R.call(this,a)}q(Be,R);
p.Object.defineProperties(Be.prototype,{text:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},b:{configurable:!0,enumerable:!0,get:function(){return xe(this,2,N)},set:function(a){S(this,2,a)}},link:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new Ce(a)})},set:function(a){S(this,3,a)}}});function De(a){R.call(this,a)}q(De,R);
p.Object.defineProperties(De.prototype,{c:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||!1},set:function(a){this.a[1]=a}},g:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||!1},set:function(a){this.a[2]=a}},i:{configurable:!0,enumerable:!0,get:function(){return this.a[3]||!1},set:function(a){this.a[3]=a}},h:{configurable:!0,enumerable:!0,get:function(){return this.a[4]||!1},set:function(a){this.a[4]=a}},b:{configurable:!0,enumerable:!0,get:function(){return this.a[5]||
!1},set:function(a){this.a[5]=a}},L:{configurable:!0,enumerable:!0,get:function(){return this.a[6]||!1},set:function(a){this.a[6]=a}},j:{configurable:!0,enumerable:!0,get:function(){return this.a[7]||!1},set:function(a){this.a[7]=a}},m:{configurable:!0,enumerable:!0,get:function(){return this.a[9]||!1},set:function(a){this.a[9]=a}}});function Ee(a){R.call(this,a)}q(Ee,R);
p.Object.defineProperties(Ee.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},source:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new Ae(a)})},set:function(a){S(this,2,a)}},c:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new V(a)})},set:function(a){S(this,3,a)}},C:{configurable:!0,enumerable:!0,get:function(){return U(this,4,function(a){return new V(a)})},set:function(a){S(this,
4,a)}},visibility:{configurable:!0,enumerable:!0,get:function(){return this.a[5]||0},set:function(a){this.a[5]=a}},s:{configurable:!0,enumerable:!0,get:function(){return U(this,6,function(a){return new De(a)})},set:function(a){S(this,6,a)}},h:{configurable:!0,enumerable:!0,get:function(){return U(this,7,function(a){return new W(a)})},set:function(a){S(this,7,a)}},b:{configurable:!0,enumerable:!0,get:function(){return U(this,8,function(a){return new W(a)})},set:function(a){S(this,8,a)}},i:{configurable:!0,
enumerable:!0,get:function(){return T(this,9,function(a){return new W(a)})},set:function(a){S(this,9,a)}},g:{configurable:!0,enumerable:!0,get:function(){return T(this,10,function(a){return new V(a)})},set:function(a){S(this,10,a)}}});function Fe(a){R.call(this,a)}q(Fe,R);
p.Object.defineProperties(Fe.prototype,{l:{configurable:!0,enumerable:!0,get:function(){return U(this,1,function(a){return new Ee(a)})},set:function(a){S(this,1,a)}},type:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new X(a)})},set:function(a){S(this,2,a)}}});function Ge(a){R.call(this,a)}q(Ge,R);
p.Object.defineProperties(Ge.prototype,{l:{configurable:!0,enumerable:!0,get:function(){return U(this,1,function(a){return new Ee(a)})},set:function(a){S(this,1,a)}},i:{configurable:!0,enumerable:!0,get:function(){return we(this,2)},set:function(a){S(this,2,a)}},c:{configurable:!0,enumerable:!0,get:function(){return this.a[3]||!1},set:function(a){this.a[3]=a}},g:{configurable:!0,enumerable:!0,get:function(){return T(this,4,function(a){return new He(a)})},set:function(a){S(this,4,a)}},b:{configurable:!0,
enumerable:!0,get:function(){return U(this,5,function(a){return new He(a)})},set:function(a){S(this,5,a)}},h:{configurable:!0,enumerable:!0,get:function(){return T(this,6,function(a){return new He(a)})},set:function(a){S(this,6,a)}}});function He(a){R.call(this,a)}q(He,R);
p.Object.defineProperties(He.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},type:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new X(a)})},set:function(a){S(this,2,a)}},b:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new V(a)})},set:function(a){S(this,3,a)}}});function Ie(a){R.call(this,a)}q(Ie,R);
p.Object.defineProperties(Ie.prototype,{type:{configurable:!0,enumerable:!0,get:function(){return U(this,1,function(a){return new X(a)})},set:function(a){S(this,1,a)}},value:{configurable:!0,enumerable:!0,get:function(){return T(this,2,function(a){return new Je(a)})},set:function(a){S(this,2,a)}},visibility:{configurable:!0,enumerable:!0,get:function(){return this.a[3]||0},set:function(a){this.a[3]=a}}});function Je(a){R.call(this,a)}q(Je,R);
p.Object.defineProperties(Je.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},b:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new V(a)})},set:function(a){S(this,2,a)}},C:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new V(a)})},set:function(a){S(this,3,a)}}});function Ke(a){R.call(this,a)}q(Ke,R);
p.Object.defineProperties(Ke.prototype,{b:{configurable:!0,enumerable:!0,get:function(){return T(this,1,function(a){return new Le(a)})},set:function(a){S(this,1,a)}},type:{configurable:!0,enumerable:!0,get:function(){return T(this,2,function(a){return new Le(a)})},set:function(a){S(this,2,a)}},c:{configurable:!0,enumerable:!0,get:function(){return T(this,3,function(a){return new ze(a)})},set:function(a){S(this,3,a)}},g:{configurable:!0,enumerable:!0,get:function(){return T(this,4,function(a){return new ze(a)})},
set:function(a){S(this,4,a)}}});function Le(a){R.call(this,a)}q(Le,R);
p.Object.defineProperties(Le.prototype,{type:{configurable:!0,enumerable:!0,get:function(){return U(this,1,function(a){return new W(a)})},set:function(a){S(this,1,a)}},b:{configurable:!0,enumerable:!0,get:function(){return this.a[3]||!1},set:function(a){this.a[3]=a}},c:{configurable:!0,enumerable:!0,get:function(){return we(this,4)},set:function(a){S(this,4,a)}},ta:{configurable:!0,enumerable:!0,get:function(){return we(this,5)},set:function(a){S(this,5,a)}},D:{configurable:!0,enumerable:!0,get:function(){return T(this,
6,function(a){return new Le(a)})},set:function(a){S(this,6,a)}}});function Ne(a){R.call(this,a)}q(Ne,R);
p.Object.defineProperties(Ne.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},source:{configurable:!0,enumerable:!0,get:function(){return U(this,5,function(a){return new Ae(a)})},set:function(a){S(this,5,a)}},g:{configurable:!0,enumerable:!0,get:function(){return U(this,6,function(a){return new Oe(a)})},set:function(a){S(this,6,a)}},h:{configurable:!0,enumerable:!0,get:function(){return U(this,7,function(a){return new V(a)})},set:function(a){S(this,
7,a)}},s:{configurable:!0,enumerable:!0,get:function(){return U(this,8,function(a){return new De(a)})},set:function(a){S(this,8,a)}},C:{configurable:!0,enumerable:!0,get:function(){return U(this,9,function(a){return new V(a)})},set:function(a){S(this,9,a)}},$:{configurable:!0,enumerable:!0,get:function(){return T(this,10,function(a){return new Fe(a)})},set:function(a){S(this,10,a)}},b:{configurable:!0,enumerable:!0,get:function(){return U(this,11,function(a){return new Ie(a)})},set:function(a){S(this,
11,a)}},Z:{configurable:!0,enumerable:!0,get:function(){return T(this,12,function(a){return new Ge(a)})},set:function(a){S(this,12,a)}},v:{configurable:!0,enumerable:!0,get:function(){return T(this,13,function(a){return new Fe(a)})},set:function(a){S(this,13,a)}},c:{configurable:!0,enumerable:!0,get:function(){return U(this,14,function(a){return new Ge(a)})},set:function(a){S(this,14,a)}},method:{configurable:!0,enumerable:!0,get:function(){return T(this,15,function(a){return new Ge(a)})},set:function(a){S(this,
15,a)}},da:{configurable:!0,enumerable:!0,get:function(){return T(this,16,function(a){return new Fe(a)})},set:function(a){S(this,16,a)}},F:{configurable:!0,enumerable:!0,get:function(){return T(this,18,function(a){return new W(a)})},set:function(a){S(this,18,a)}},ca:{configurable:!0,enumerable:!0,get:function(){return T(this,19,function(a){return new W(a)})},set:function(a){S(this,19,a)}},U:{configurable:!0,enumerable:!0,get:function(){return T(this,26,function(a){return new W(a)})},set:function(a){S(this,
26,a)}},u:{configurable:!0,enumerable:!0,get:function(){return T(this,27,function(a){return new W(a)})},set:function(a){S(this,27,a)}},m:{configurable:!0,enumerable:!0,get:function(){return T(this,20,function(a){return new Fe(a)})},set:function(a){S(this,20,a)}},j:{configurable:!0,enumerable:!0,get:function(){return U(this,21,function(a){return new Pe(a)})},set:function(a){S(this,21,a)}},i:{configurable:!0,enumerable:!0,get:function(){return U(this,22,function(a){return new W(a)})},set:function(a){S(this,
22,a)}},M:{configurable:!0,enumerable:!0,get:function(){return T(this,28,function(a){return new W(a)})},set:function(a){S(this,28,a)}},filename:{configurable:!0,enumerable:!0,get:function(){return this.a[23]||""},set:function(a){this.a[23]=a}},A:{configurable:!0,enumerable:!0,get:function(){return this.a[24]||""},set:function(a){this.a[24]=a}},S:{configurable:!0,enumerable:!0,get:function(){return T(this,25,function(a){return new Fe(a)})},set:function(a){S(this,25,a)}}});
function Qe(a){R.call(this,a)}q(Qe,R);
p.Object.defineProperties(Qe.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},href:{configurable:!0,enumerable:!0,get:function(){return xe(this,2,fe)},set:function(a){S(this,2,a)}},summary:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new V(a)})},set:function(a){S(this,3,a)}},s:{configurable:!0,enumerable:!0,get:function(){return U(this,4,function(a){return new De(a)})},set:function(a){S(this,4,a)}}});
function Oe(a){R.call(this,a)}q(Oe,R);p.Object.defineProperties(Oe.prototype,{b:{configurable:!0,enumerable:!0,get:function(){return T(this,1,function(a){return new Qe(a)})},set:function(a){S(this,1,a)}},c:{configurable:!0,enumerable:!0,get:function(){return T(this,2,function(a){return new Qe(a)})},set:function(a){S(this,2,a)}},g:{configurable:!0,enumerable:!0,get:function(){return T(this,3,function(a){return new Qe(a)})},set:function(a){S(this,3,a)}}});function Pe(a){R.call(this,a)}q(Pe,R);
p.Object.defineProperties(Pe.prototype,{type:{configurable:!0,enumerable:!0,get:function(){return U(this,1,function(a){return new W(a)})},set:function(a){S(this,1,a)}},L:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||!1},set:function(a){this.a[2]=a}}});function Re(a){R.call(this,a)}q(Re,R);
p.Object.defineProperties(Re.prototype,{types:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new Se(a)})},set:function(a){S(this,2,a)}},b:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new Te(a)})},set:function(a){S(this,3,a)}},file:{configurable:!0,enumerable:!0,get:function(){return U(this,4,function(a){return new ye(a)})},set:function(a){S(this,4,a)}}});function Te(a){R.call(this,a)}q(Te,R);
p.Object.defineProperties(Te.prototype,{title:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},content:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new V(a)})},set:function(a){S(this,2,a)}}});function Se(a){R.call(this,a)}q(Se,R);p.Object.defineProperties(Se.prototype,{type:{configurable:!0,enumerable:!0,get:function(){return T(this,1,function(a){return new Ne(a)})},set:function(a){S(this,1,a)}}});
function Ue(a){R.call(this,a)}q(Ue,R);
p.Object.defineProperties(Ue.prototype,{i:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||!1},set:function(a){this.a[1]=a}},c:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new X(a)})},set:function(a){S(this,2,a)}},b:{configurable:!0,enumerable:!0,get:function(){return T(this,3,function(a){return new X(a)})},set:function(a){S(this,3,a)}},g:{configurable:!0,enumerable:!0,get:function(){return U(this,4,function(a){return new X(a)})},set:function(a){S(this,
4,a)}}});function Ce(a){R.call(this,a)}q(Ce,R);p.Object.defineProperties(Ce.prototype,{href:{configurable:!0,enumerable:!0,get:function(){return xe(this,1,fe)},set:function(a){S(this,1,a)}},b:{configurable:!0,enumerable:!0,get:function(){return xe(this,2,fe)},set:function(a){S(this,2,a)}}});function W(a){R.call(this,a)}q(W,R);
p.Object.defineProperties(W.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},A:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||""},set:function(a){this.a[2]=a}},link:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new Ce(a)})},set:function(a){S(this,3,a)}},c:{configurable:!0,enumerable:!0,get:function(){return this.a[4]||!1},set:function(a){this.a[4]=a}},b:{configurable:!0,enumerable:!0,
get:function(){return T(this,5,function(a){return new X(a)})},set:function(a){S(this,5,a)}}});function Ve(a){R.call(this,a)}q(Ve,R);p.Object.defineProperties(Ve.prototype,{type:{configurable:!0,enumerable:!0,get:function(){return T(this,1,function(a){return new X(a)})},set:function(a){S(this,1,a)}}});function We(a){R.call(this,a)}q(We,R);
p.Object.defineProperties(We.prototype,{w:{configurable:!0,enumerable:!0,get:function(){return T(this,1,function(a){return new Xe(a)})},set:function(a){S(this,1,a)}}});function Xe(a){R.call(this,a)}q(Xe,R);p.Object.defineProperties(Xe.prototype,{key:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},value:{configurable:!0,enumerable:!0,get:function(){return U(this,2,function(a){return new X(a)})},set:function(a){S(this,2,a)}}});
function X(a){R.call(this,a)}q(X,R);
p.Object.defineProperties(X.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||!1},set:function(a){this.a[2]=a}},c:{configurable:!0,enumerable:!0,get:function(){return U(this,3,function(a){return new Ue(a)})},set:function(a){S(this,3,a)}},i:{configurable:!0,enumerable:!0,get:function(){return U(this,4,function(a){return new W(a)})},set:function(a){S(this,4,a)}},h:{configurable:!0,enumerable:!0,get:function(){return U(this,5,function(a){return new We(a)})},set:function(a){S(this,
5,a)}},j:{configurable:!0,enumerable:!0,get:function(){return U(this,6,function(a){return new Ve(a)})},set:function(a){S(this,6,a)}},m:{configurable:!0,enumerable:!0,get:function(){return this.a[7]||!1},set:function(a){this.a[7]=a}},v:{configurable:!0,enumerable:!0,get:function(){return this.a[8]||!1},set:function(a){this.a[8]=a}},F:{configurable:!0,enumerable:!0,get:function(){return this.a[9]||!1},set:function(a){this.a[9]=a}},u:{configurable:!0,enumerable:!0,get:function(){return this.a[10]||!1},
set:function(a){this.a[10]=a}}});function Ye(a){R.call(this,a)}q(Ye,R);
p.Object.defineProperties(Ye.prototype,{id:{configurable:!0,enumerable:!0,get:function(){return this.a[1]||""},set:function(a){this.a[1]=a}},b:{configurable:!0,enumerable:!0,get:function(){return this.a[2]||""},set:function(a){this.a[2]=a}},title:{configurable:!0,enumerable:!0,get:function(){return this.a[3]||""},set:function(a){this.a[3]=a}},c:{configurable:!0,enumerable:!0,get:function(){return this.a[4]||0},set:function(a){this.a[4]=a}},g:{configurable:!0,enumerable:!0,get:function(){return we(this,
5)},set:function(a){S(this,5,a)}}});function Ze(a,b){return N('<code class="expression">'+$e(a,b)+"</code>")}function af(a){var b=a.content,c=a.target,d=a.title,e=a.rb,f=a.tabIndex,g=a.Ya;return N('<a href="'+Q(qe(a.link.href))+'"'+(c?' target="'+Q(c)+'"':"")+(d?' title="'+Q(d)+'"':"")+(f?' tabIndex="'+Q(f)+'"':"")+(g?' class="'+Q(g)+'"':"")+">"+(e?"<code>"+M(b)+"</code>":M(b))+"</a>")}function bf(a,b){return N(cf()+Ze(a,b))}function cf(){return N(' <var class="yield">→</var> ')}
function $e(a,b){var c=a.G,d=a.wa,e=N,f=c.g?"...":"";if(c.c){a=a.G.c;for(var c="function("+(a.c?(a.i?"new":"this")+": "+$e({G:a.c},b)+(a.b.length?", ":""):""),d=a.b,g=d.length,h=0;h<g;h++)c+=$e({G:d[h]},b)+(h!=g-1?", ":"");c+=")"+(a.g?": "+$e({G:a.g},b):"");b=N(c)}else if(c.i)b=df({type:c.i},b);else if(c.h){c="{";a=a.G.h.w;d=a.length;for(g=0;g<d;g++)h=a[g],c+=M(h.key)+": "+$e({G:h.value},b)+(g!=d-1?", ":"");b=N(c+"}")}else if(c.j){c="(";a=a.G.j.type;d=a.length;for(g=0;g<d;g++)c+=$e({G:a[g]},b)+(g!=
d-1?"|":"");b=N(c+")")}else b=c.m?"*":c.v?"?":c.F?d?"void":"undefined":c.u?"null":"";return e(f+b)}function df(a,b){var c=a.type,d=a.nb;a=""+(d&&c.A?""+c.A:""+c.name);a=he(a);d=""+(c.A&&c.A!=c.name&&!d?""+c.A:"");d=he(d);a=""+(c.link?af({content:a,link:c.link,target:c.c?"_blank":"",title:d}):M(a));if(c.b.length){a+="&lt;";for(var c=c.b,d=c.length,e=0;e<d;e++)a+=$e({G:c[e]},b)+(e!=d-1?", ":"");a+="&gt;"}return N(a)};function ef(a){var b=a.P,c=a.Za;a="";if(b&&b.b.length){c=c&&1==b.b.length&&!b.b[0].b;a+=c?"<p>":"";for(var b=b.b,d=b.length,e=0;e<d;e++){var f=b[e];a+=f.link&&f.link.href?af({link:f.link,content:P(""+(f.text?M(f.text):"")+(f.b?M(f.b):""))}):(f.text?M(f.text):"")+(f.b?M(f.b):"")}a+=c?"</p>":""}return N(a)}
function ff(a){var b=a.id,c=a.X,d=a.body,e=a.source;return N('<section class="'+Q(a.className)+'" '+(b?' id="'+Q(b)+'"':"")+'><div class="header">'+M(c)+'</div><div class="body">'+M(d)+(e&&(e.uri||e.c)?'<div class="source">'+(e.uri?'<a href="'+Q(qe(e.uri))+'" target="_blank" title="View source">VIEW SOURCE</a>':'<a href="'+Q(qe(e.c))+(e.b&&0<e.b?"#l"+Q(e.b):"")+'" title="View source">VIEW SOURCE</a>')+"</div>":"")+"</div></section>")}
function Y(a){var b=a.title,c=a.J,d=a.Xa,e=a.Aa,f=a.qb,g=a.id;return N('<tr class="info-row'+(a.block?" block":"")+'" '+(g?'id="'+Q(g)+'"':"")+">"+(b?'<th class="info-head">'+M(b)+"</th>":"")+'<td class="info-cell" '+(d?oe(d):"")+">"+M(c)+"</td>"+(e?'<td class="info-cell" '+(f?oe(f):"")+">"+M(e)+"</td>":"")+"</tr>")}
function Z(a,b){var c=a.types,d=a.title;a=a.mb;var e="";if(c.length){for(var f='<ul class="type-list">',g=c.length,h=0;h<g;h++)var m=c[h],l="<li "+(a?' class="'+Q(a)+'"':"")+">",m=N('<code class="expression">'+df({type:m,nb:!0},b)+"</code>"),f=f+(l+m);f+="</ul>";e+=Y({title:P(""+M(d)),block:!0,J:P(f)})}return N(e)}function gf(a){a=a.C;return N(a&&a.b.length?'<table class="info deprecation">'+Y({title:P('<i class="material-icons">warning</i> Deprecated'),J:P(""+ef({P:a}))})+"</table>":"")}
function hf(a,b){var c=a.X,d=a.la,e=a.wa,f="";if(a.$a||d&&0<d.length){a="";if(d&&0<d.length){a+='<table class="info detail">';for(var g=d.length,h=0;h<g;h++){var m=d[h],l=""+(m.type?Ze({G:m.type,b:!0,wa:e},b):""),l=P(l),A=""+(m.b?ef({P:m.b}):""),A=P(A);a+=m.name?Y({J:P("<var>"+M(m.name)+"</var>"),Xa:ie(""+(l?"":'colspan="2"')),Aa:P(""+M(l))})+(A?Y({J:P(""),Aa:P(""+M(A))}):""):(l?Y({J:P(""+M(l))}):"")+(A?Y({J:P(""+M(A))}):"")}a+="</table>"}else a+="<p>None.</p>";f+=Y({block:!0,title:P(""+M(c)),J:P(a)})}return N(f)}
function jf(a,b){var c=a.I;return N('<table class="info">'+(a.ob?kf({l:c.l},b):"")+hf({X:"Parameters",la:c.g,$a:!0},b)+(!c.c&&c.b&&(c.b.b&&c.b.b.b.length||c.b.type)?hf({X:"Returns",la:[c.b],wa:!0},b):"")+hf({X:"Throws",la:c.h},b)+lf({l:c.l})+"</table>")}function mf(a){var b='<var class="template">&lt;';a=a.names;for(var c=a.length,d=0;d<c;d++)b+=M(a[d])+(d!=c-1?", ":"");return N(b+"&gt;</var>")}
function nf(a,b){var c=a.I;a=a.pa;a=""+(c.c?"new ":a?"<var>this.</var>":"")+M(c.l.name)+(c.i&&c.i.length?mf({names:c.i}):"")+"(";if(c.g.length){a+=" ";for(var d=c.g,e=d.length,f=0;f<e;f++){var g=d[f];a+="<var>"+(g.type&&g.type.g?"...":"")+M(g.name)+"</var>"+(f!=e-1?", ":"")}a+=" "}a+=")"+(c.c?"":c.b&&c.b.type?bf({G:c.b.type},b):c.b?N(cf()+'<code class="expression"><i>?</i></code>'):N(cf()+'<code class="expression"><i>void</i></code>'));return N(a)}
function kf(a,b){a=a.l;return N((a.h?Z({types:[a.h],title:"Defined by"},b):"")+(a.b?Z({types:[a.b],title:"Overrides"},b):"")+Z({types:a.i,title:"Specified by"},b))}function of(a,b){var c=a.title,d=a.Ca,e=a.ja;a=a.Fa;var f="";if(d&&d.length||e&&e.length){f+='<section class="instance-methods"><h2>'+M(c)+"</h2>";if(d&&d.length)for(e=d.length,c=0;c<e;c++)f+=pf({I:d[c],pa:a},b);else if(e&&e.length)for(d=e.length,c=0;c<d;c++)f+=pf({ta:e[c],pa:a},b);f+="</section>"}return N(f)}
function pf(a,b){a=a||{};var c=a.I,d=a.ta,e=a.pa,f=c?c.l:d.l;a=""+ff({className:"property expandable",id:f.name,source:f.source,X:P('<div class="more"><i class="material-icons">expand_more</i></div><h3 class="name">'+qf({s:f.s,visibility:f.visibility})+"<div>"+(c?nf(a,b):d?(e?"<var>this.</var>":"")+M(f.name)+(d.type?bf({G:d.type,b:!0},b):""):"")+"</div></h3>"),body:P(""+ef({P:f.c})+gf({C:f.C})+(c&&(c.l.C&&c.l.C.b.length||c.l.b||c.l.i.length||c.g.length||c.h.length||c.b&&(c.b.b&&c.b.b.b.length||c.b.type))?
c?jf({I:c,ob:!0},b):"":d&&(d.l.b||d.l.i.length||d.l.C&&d.l.C.b.length||d.l.g.length)?'<table class="info">'+kf({l:d.l},b)+lf({l:d.l})+"</table>":f.c&&f.c.b.length?"":"<p>No information.</p>"))});return N(a)}function lf(a){var b=a.l;a="";if(b.g.length){for(var c="",b=b.g,d=b.length,e=0;e<d;e++)c+=ef({P:b[e],Za:!0});a+=Y({block:!0,title:P("See Also"),J:P(c)})}return N(a)}
function qf(a){a=a||{};var b=a.s,c=a.visibility;a=a.span;return N(""+(b&&(b.g||b.c||b.h||b.i||b.j)||c&&0!=c?"<"+(a?"span":"div")+' class="tags">'+(b&&b.g?'<span class="deprecated"></span>':"")+(3==c?'<span class="package"></span>':2==c?'<span class="private"></span>':1==c?'<span class="protected"></span>':"")+(b?(b.c?'<span class="const"></span>':"")+(b.h?'<span class="final"></span>':"")+(b.i?'<span class="dict"></span>':"")+(b.j?'<span class="struct"></span>':""):"")+"</"+(a?"span":"div")+">":""))}
function rf(a){var b=a.title,c=!!a.L;a=a.types;var d="";if(a&&0<a.length){d+='<section class="types"><h2>'+(c?"Exported ":"")+M(b)+"</h2><ul>";b=a.length;for(c=0;c<b;c++)var e=a[c],d=d+('<li class="summary">'+qf({s:e.s})+'<div><a href="'+Q(qe(e.href))+'">'+M(e.name)+"</a></div>");d+="</ul></section>"}return N(d)}function sf(a){a=a.data;return N("<title>"+(a.types&&a.types.type.length?je(a.types.type[0].A):a.b&&a.b.content?je(a.b.title):a.file?je(a.file.b):"")+"</title>")}
function tf(a,b,c){b=a.data;a=N;if(b.types&&b.types.type.length){b=b.types.type;c=c||{};var d="";if(1<b.length){for(var d=d+"<article><h2>Did you mean?</h2><ul>",e=b.length,f=0;f<e;f++)var g=b[f],d=d+('<li><a href="'+Q(qe(g.filename))+'">'+M(g.A)+"</a>");d+="</ul></article>"}e=b.length;for(f=0;f<e;f++){var g=b[f],h=d,d=1<b.length?'<article style="'+(c.Ba?"/*"+c.Ba+"*//*"+c.Ba+"*/":"")+'display:none" data-name="'+Q(g.name)+'" data-filename="'+Q(g.filename)+'">':"<article>",m=g.source,l;l=g;l=N((l.j?
'<table class="info">'+Z({types:[l.j.type],title:l.j.L?"Module":"Namespace"},c)+"</table>":"")+'<h1 class="title'+(l.C?" deprecated":"")+'">'+qf({s:l.s,visibility:l.b?l.b.visibility:null})+"<div>"+(l.s&&l.s.L?"Module "+M(l.name):l.s&&l.s.m?"Record "+M(l.name):l.s&&l.s.b?"Interface "+M(l.name):l.c&&l.c.c?"Class "+M(l.name):l.b?"Enumeration "+M(l.name):"Namespace "+M(l.name))+(l.c&&l.c.i.length?mf({names:l.c.i}):"")+"</div></h1>");l=P(""+l);var A=""+(g.F.length||g.ca.length||g.U.length||g.s&&g.s.b&&
g.u.length||g.i||g.M.length||g.b&&g.b.type?'<table class="info">'+Z({types:g.F,title:"Extends",mb:"super-class"},c)+Z({types:g.ca,title:"All "+(g.s&&g.s.b?"Extended":"Implemented")+" Interfaces"},c)+Z({types:g.U,title:"All Known "+(g.s&&g.s.b?"Subinterfaces":"Direct Subclasses")},c)+Z({types:g.u,title:"All Known Implementations"},c)+(g.i?Z({types:[g.i],title:"Alias for"},c):"")+Z({types:g.M,title:"All Known Aliases"},c)+(g.b&&g.b.type?Y({title:P("Type"),J:P(""+Ze({G:g.b.type,b:!0},c))}):"")+"</table>":
"")+gf({C:g.C})+(g.h&&g.h.b.length?ef({P:g.h}):"<p>No description available.</p>"),x;if(g.s&&g.s.b||!g.c)x="";else{x=c;var C=g.c,O=C.g.length||C.h.length||C.b&&C.b.b&&C.b.b.b.length;x=""+(C.c?'<h3 class="name">'+qf({visibility:C.l.visibility})+"<div>"+nf({I:C},x)+"</div></h3>"+jf({I:C},x):O?'<h3 class="name"><div>'+nf({I:C},x)+"</div></h3>"+jf({I:C},x):"");x=N(x)}d+=ff({className:"intro",source:m,X:l,body:P(A+x)});if(g.b){l=g.b;m="";if(l.value.length){m+='<section class="enum-values"><h2>Values</h2><section class="property"><table class="info">';
l=l.value;A=l.length;for(x=0;x<A;x++)C=l[x],m+=Y({id:C.name,block:!0,title:P(""+M(C.name)),J:P(""+(C.b&&C.b.b.length||C.C&&C.C.b.length?ef({P:C.b})+gf({C:C.C}):""))});m+="</table></section></section>"}m=N(m)}else m="";d=h+(d+m+of({title:"Instance Methods",Ca:g.method,Fa:!0},c)+of({title:"Instance Properties",ja:g.da,Fa:!0},c));h=""+(g.s&&g.s.L?"Exported ":g.c&&g.c.c?"Static ":"");h=he(h);m=g.Z.length?of({title:h+"Functions",Ca:g.Z},c):"";if(g.s&&g.s.L&&g.S.length){l=c;A="<ul>";x=g.S;C=x.length;for(O=
0;O<C;O++){var n=x[O],A=A+('<li id="'+Q(n.l.name)+'">'),Me=n.l.source&&(n.l.source.c||n.l.source.uri);if(Me)if(n.l.source.uri)A+='<a href="'+Q(qe(n.l.source.uri))+'" target="_blank" title="View source">';else var Kg=n.l.source.b&&0<n.l.source.b,A=A+('<a href="'+Q(qe(n.l.source.c))+(Kg?"#l"+Q(n.l.source.b):"")+'" title="View source">');A+=M(n.l.name)+(Me?"</a>":"")+(n.type?bf({G:n.type,b:!0},l):"")}l='<section class="exported-modules"><h2>Exported Modules</h2>'+N(A+"</ul>")+"</section>"}else l="";
d+=m+l+(g.v.length?of({title:h+"Properties",ja:g.v},c):"")+(g.m.length?of({title:"Compiler Constants",ja:g.m},c):"");g.g&&(h=g.s&&g.s.L,d+=rf({L:h,title:"Interfaces",types:g.g.g})+rf({L:h,title:"Classes",types:g.g.b})+rf({L:h,title:"Enumerations",types:g.g.c}));d+=(g.$.length?of({title:"Type Definitions",ja:g.$},c):"")+"</article>"}b=N(d)}else if(b.b&&b.b.content)b={P:b.b.content},b=N('<article class="page">'+(b.P.b.length?ef(b):"<strong>TODO</strong>")+"</article>");else if(b.file){c=b.file;b='<article class="srcfile"><h1 class="title">'+
M(c.c)+"</h1><div><table>";c=c.g;e=c.length;for(f=0;f<e;f++)g=c[f],b+='<tr id="l'+Q(f+1)+'"><td><a href="#l'+Q(f+1)+'">'+M(f+1)+"</a><td>"+(g?M(g):"");b=N(b+"</table></div></article>")}else b="";return a(b)};function uf(a,b,c){var d=a.types;b=a.links;var e;if(a.Ga.length){e=a.Ga;var f="";if(e.length){for(var f=f+'<ul class="tree">',g=e.length,h=0;h<g;h++)var m=e[h],f=f+vf({type:m,Pa:m.D},c);f+="</ul>"}e='<section class="modules"><div class="toggle"><div class="title"><span class="item" tabindex="1">Modules</span><i class="material-icons">expand_more</i></div></div>'+N(f)+"</section>"}else e="";a='<section><a class="title" href="index.html" tabindex="1">Overview</a></section>'+e+(d.length?'<section class="types"><div class="toggle"><div class="title"><span class="item" tabindex="1">Types</span><i class="material-icons">expand_more</i></div></div>'+
wf(a,c)+"</section>":"");c=b.length;for(d=0;d<c;d++)e=b[d],a+=e.href&&e.text?'<section><a class="title" href="'+Q(qe(e.href))+'" tabindex="1">'+M(e.text)+"</a></section>":"";return N(a)}function wf(a,b){a=a.types;var c="";if(a.length){for(var c=c+'<ul class="tree">',d=a.length,e=0;e<d;e++)var f=a[e],c=c+vf({type:f,Pa:f.D},b);c+="</ul>"}return N(c)}
function vf(a,b){var c=a.Pa,d="";a=a.type.type;a=""+af({content:he(""+a.name),link:a.link,tabIndex:1,Ya:"item"});a=P(a);d+="<li>"+(c&&c.length?'<div class="toggle">'+M(a)+'<i class="material-icons">expand_more</i></div>'+wf({types:c},b):M(a));return N(d)};function xf(a){a.sort(function(a,c){a=a.type.A||a.type.name;c=c.type.A||c.type.name;return a===c?0:a<c?-1:1});a.forEach(function(a){a.D.length&&xf(a.D)})}
function yf(a){var b=[],c=[];a.forEach(function(a){a.type.A||(a.type.A=a.type.name);for(;c.length;){var d=db(c),f=d.type.A,g=a.type.A,h=!1;g.startsWith(f+".")?(a.type.name=g.slice(f.length+1),h=!0):g.startsWith(f+"/")&&(a.type.name=g.slice(f.length),h=!0);if(h){d.D.push(a);a.b&&c.push(a);return}c.pop()}a.type.A||(a.type.A=a.type.name);b.push(a);a.b&&c.push(a)});xf(b);return b}function zf(){var a=document.createElement("div");a.classList.add("dossier-nav-mask");return a}
function Af(a,b){"boolean"==typeof b?b?a.classList.add("open"):a.classList.remove("open"):a.classList.toggle("open")}function Bf(a,b){var c=this;this.g=a;this.b=b;this.a=b.ownerDocument.createElement("div");this.a.tabIndex=-1;J(this.a,"blur",function(){return c.a.tabIndex=-1});J(this.a,"focus",function(){return c.a.tabIndex=1});b.insertBefore(this.a,b.firstChild)}
function Cf(a){var b=kb+location.pathname.slice(kb.length),c=a.b.querySelector("a.current");if(c){if(c.getAttribute("href")===b)return;c.classList.remove("current")}(a=a.b.querySelector('a[href="'+b+'"]'))&&a.classList.add("current")}function Df(a){a.b.classList.add("visible");a.g.disabled=!(1112<=window.innerWidth);setTimeout(function(){a.a.focus()},200)}function Ef(a){a.b.classList.remove("visible");a.g.disabled=!1}Bf.prototype.c=function(){this.f?Ef(this):Df(this)};
Bf.prototype.h=function(a){(a=bd(a.target,function(a){return a&&a.classList&&a.classList.contains("toggle")}))&&a.classList.contains("toggle")&&Af(a)};p.Object.defineProperties(Bf.prototype,{i:{configurable:!0,enumerable:!0,get:function(){return this.b}},f:{configurable:!0,enumerable:!0,get:function(){return this.b.classList.contains("visible")}}});function Ff(a,b){var c=Tc(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""}function Gf(a,b){return Ff(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Hf(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}F&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function If(a){if(F&&!(8<=Number(Oc)))return a.offsetParent;var b=Tc(a),c=Gf(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=Gf(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Jf(a){for(var b=new Lb(0,Infinity,Infinity,0),c=Rc(a),d=c.a.body,e=c.a.documentElement,f=Xc(c.a);a=If(a);)if(!(F&&!a.clientWidth||H&&!a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=Gf(a,"overflow")){var g=Kf(a),h=new B(a.clientLeft,a.clientTop);g.x+=h.x;g.y+=h.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(Yc(c.a)||
window).document;c=Zc(c)?c.documentElement:c.body;c=new Ha(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}function Kf(a){var b=Tc(a),c=new B(0,0),d;d=b?Tc(b):document;d=!F||9<=Number(Oc)||Zc(Rc(d).a)?d.documentElement:d.body;if(a==d)return c;a=Hf(a);b=Wc(Rc(b).a);c.x=a.left+b.x;c.y=a.top+b.y;return c}function Lf(a){"number"==typeof a&&(a+="px");return a}
function Mf(a){var b=Nf;if("none"!=Gf(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function Nf(a){var b=a.offsetWidth,c=a.offsetHeight,d=H&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Hf(a),new Ha(a.right-a.left,a.bottom-a.top)):new Ha(b,c)}var Of=Hc?"MozUserSelect":H||G?"WebkitUserSelect":null;
function Pf(a){var b=a.getElementsByTagName("*");if(Of){var c="none";a.style&&(a.style[Of]=c);if(b){a=0;for(var d;d=b[a];a++)d.style&&(d.style[Of]=c)}}else if(F||Fc)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function Qf(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;b=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return b}
function Rf(a,b){return(b=a.currentStyle?a.currentStyle[b]:null)?Qf(a,b):0}var Sf={thin:2,medium:4,thick:6};function Tf(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;b=a.currentStyle?a.currentStyle[b+"Width"]:null;return b in Sf?Sf[b]:Qf(a,b)}
function Uf(a){if(F&&!(9<=Number(Oc))){var b=Tf(a,"borderLeft"),c=Tf(a,"borderRight"),d=Tf(a,"borderTop");a=Tf(a,"borderBottom");return new Lb(d,c,a,b)}b=Ff(a,"borderLeftWidth");c=Ff(a,"borderRightWidth");d=Ff(a,"borderTopWidth");a=Ff(a,"borderBottomWidth");return new Lb(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function Vf(a,b){return(b&8&&"rtl"==Gf(a,"direction")?b^4:b)&-9};function Wf(a,b){K.call(this);this.c=a||1;this.f=b||t;this.j=ta(this.v,this);this.m=ua()}w(Wf,K);Wf.prototype.h=!1;Wf.prototype.a=null;Wf.prototype.v=function(){if(this.h){var a=ua()-this.m;0<a&&a<.8*this.c?this.a=this.f.setTimeout(this.j,this.c-a):(this.a&&(this.f.clearTimeout(this.a),this.a=null),L(this,"tick"),this.h&&(this.a=this.f.setTimeout(this.j,this.c),this.m=ua()))}};function Xf(a,b,c){K.call(this);this.F=a;this.S=c;this.c=b;J(b,[Yf,Zf,$f,ag],this.handleEvent,!1,this);this.m=null;this.f=[];this.h=-1;this.a=0;this.j=this.v=null;this.U={}}w(Xf,K);Xf.prototype.M=10;var Yf="hilite",Zf="select",ag="dismiss",$f="canceldismiss";k=Xf.prototype;
k.handleEvent=function(a){var b=this.F;if(a.target==this.c)switch(a.type){case Yf:this.V(a.W);break;case Zf:var c=!1;if("number"==typeof a.W){a=a.W;var d=this.f[bg(this,a)],c=!!d&&b.qa&&b.qa(d);d&&!c&&this.h!=a&&this.V(a)}c||cg(this);break;case $f:dg(this);break;case ag:eg(this)}};function fg(a){for(var b=a.a+a.f.length-1,c=a.h,d=0;d<a.f.length;d++){if(c>=a.a&&c<b)c++;else if(-1==c)c=a.a;else break;if(a.V(c))break}}
k.V=function(a){var b=bg(this,a),c=this.f[b];return c&&this.F.qa&&this.F.qa(c)?!1:(this.h=a,this.c.V(a),-1!=b)};
function cg(a){var b=bg(a,a.h);if(-1!=b){var c=a.f[b],d=a.S;if(d.o){var e=c.toString();if(d.c){var f=gg(d,d.o.value,fd(d.o)[0]),g=hg(d,d.o.value);d.M.test(e)||(e=e.replace(/[\s\xa0]+$/,"")+d.v);f&&!/^[\s\xa0]*$/.test(g[f-1])&&(e=" "+e);f==g.length-1&&(e+=" ");if(e!=g[f]){g[f]=e;e=d.o;(Hc||F&&Nc("9"))&&e.blur();e.value=g.join("");for(var h=0,m=0;m<=f;m++)h+=g[m].length;e.focus();f=h;g=d.o;e=f;gd(g)?g.selectionStart=e:F&&(h=hd(g),m=h[0],m.inRange(h[1])&&(e=id(g,e),m.collapse(!0),m.move("character",
e),m.select()));g=d.o;gd(g)?g.selectionEnd=f:F&&(h=hd(g),e=h[1],h[0].inRange(e)&&(f=id(g,f),g=id(g,fd(g)[0]),e.collapse(!0),e.moveEnd("character",f-g),e.select()))}}else d.o.value=e;d.va=!0}a.N();L(a,{type:"update",W:c,index:b});return!0}a.N();L(a,{type:"update",W:null,index:null});return!1}k.N=function(){this.h=-1;this.m=null;this.a+=this.f.length;this.f=[];window.clearTimeout(this.j);this.j=null;this.c.N();L(this,"suggestionsupdate");L(this,ag)};
function eg(a){a.j||(a.j=window.setTimeout(ta(a.N,a),100))}k.Ea=function(){return this.j?(window.clearTimeout(this.j),this.j=null,!0):!1};function dg(a){a.Ea()||window.setTimeout(ta(a.Ea,a),10)}k.ib=function(a,b,c){this.m==a&&this.ua(b,c)};
k.ua=function(a,b){var c="object"==la(b)&&b;b=(c?c.sb():b)?bg(this,this.h):-1;this.a+=this.f.length;this.f=a;for(var d=[],e=0;e<a.length;++e)d.push({id:this.a+e,data:a[e]});a=null;this.v&&(a=this.U,e=this.v,e=e[pa]||(e[pa]=++qa),a=a[e]||this.v);this.c.Sa=a;this.c.ua(d,this.m,this.v);a=!0;c&&void 0!==c.ab()&&(a=c.ab());this.h=-1;(a||0<=b)&&d.length&&this.m&&(0<=b?this.V(this.a+b):fg(this));L(this,"suggestionsupdate")};function bg(a,b){b-=a.a;return 0>b||b>=a.f.length?-1:b}k.update=function(a){this.S.update(a)};function ig(a,b,c,d){K.call(this);this.M=a||document.body;this.j=Rc(this.M);this.U=!a;this.a=null;this.S="";this.c=[];this.h=[];this.$=this.v=-1;this.i=!1;this.className="ac-renderer";this.Ta="ac-highlighted";this.m=b||null;this.da=null!=d?d:!0;this.Va=!!c;this.F=!1}w(ig,K);k=ig.prototype;k.ua=function(a,b,c){this.S=b;this.c=a;this.v=-1;this.$=ua();this.f=c;this.h=[];jg(this)};k.N=function(){this.i&&(this.i=!1,kg(this,!1),this.a.style.display="none")};
function lg(a){a.i||(a.i=!0,kg(a,!0),a.a.style.display="")}function kg(a,b){a.f&&(dd(a.f,"haspopup",b),dd(a.a,"expanded",b),dd(a.f,"expanded",b),b?dd(a.f,"owns",a.a.id):(a.f.removeAttribute("aria-owns"),ed(a.f,null)))}
function mg(a,b){var c=0<=b&&b<a.c.length?a.c[b]:void 0,d=0<=b&&b<a.h.length?a.h[b]:void 0;if(L(a,{type:"rowhilite",vb:d,W:c?c.data:null})&&(0<=a.v&&ub(a.h[a.v]),a.v=b,d)){sb(d,["ac-active","active"]);a.f&&ed(a.f,d);b=(a=a.a||Xc(document))||Xc(document);var e=Kf(d),f=Kf(b),g=Uf(b);b==Xc(document)?(c=e.x-b.scrollLeft,e=e.y-b.scrollTop,!F||10<=Number(Oc)||(c+=g.left,e+=g.top)):(c=e.x-f.x-g.left,e=e.y-f.y-g.top);var d=Nf(d),g=b.clientHeight-d.height,f=b.scrollLeft,h=b.scrollTop,f=f+Math.min(c,Math.max(c-
(b.clientWidth-d.width),0)),h=h+Math.min(e,Math.max(e-g,0));b=new B(f,h);a.scrollLeft=b.x;a.scrollTop=b.y}}k.V=function(a){if(-1==a)mg(this,-1);else for(var b=0;b<this.c.length;b++)if(this.c[b].id==a){mg(this,b);break}};
function ng(a){if(!a.a){var b=a.j.b("DIV",{style:"display:none"});a.F&&(b.style.overflowY="auto");a.a=b;sb(b,Qa(a.className).split(" "));cd(b,"listbox");b.id=":"+(Dc.a().a++).toString(36);a.M.appendChild(b);J(b,"click",a.eb,!1,a);J(b,"mousedown",a.gb,!1,a);J(b,"mouseover",a.hb,!1,a)}}
function jg(a){ng(a);a.Wa&&(a.a.style.minWidth=a.Wa.clientWidth+"px");a.h.length=0;a.j.f(a.a);a.m&&a.m.tb||y(a.c,function(a){var b=a;a=this.S;var d=this.j.b("DIV",{className:"ac-row",id:":"+(Dc.a().a++).toString(36)});cd(d,"option");if(!this.m||!this.m.ub)if(b=b.data.toString(),"textContent"in d)d.textContent=b;else if(3==d.nodeType)d.data=b;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=b}else ad(d),d.appendChild(Tc(d).createTextNode(String(b)));
a&&this.da&&(this.xa=!1,og(this,d,a));rb(d,"ac-row");this.h.push(d);this.a.appendChild(d)},a);a.c.length?(lg(a),pg(a),Pf(a.a)):a.N()}
function pg(a){if(a.f&&a.U){var b=a.Sa||a.f,c;c=a.Va?5:1;var d=65;a.F&&(a.a.style.height="",d|=32);a=a.a;var e=c^1,f,g;if(f=a.offsetParent){var h="HTML"==f.tagName||"BODY"==f.tagName;h&&"static"==Gf(f,"position")||(g=Kf(f),h||(h=(h="rtl"==Gf(f,"direction"))&&Hc?-f.scrollLeft:!h||Gc&&Nc("8")||"visible"==Gf(f,"overflowX")?f.scrollLeft:f.scrollWidth-f.clientWidth-f.scrollLeft,g=Kb(g,new B(h,f.scrollTop))))}f=g||new B;g=Kf(b);h=Mf(b);g=new Mb(g.x,g.y,h.width,h.height);if(h=Jf(b)){var m=new Mb(h.left,
h.top,h.right-h.left,h.bottom-h.top),h=Math.max(g.left,m.left),l=Math.min(g.left+g.width,m.left+m.width);if(h<=l){var A=Math.max(g.top,m.top),m=Math.min(g.top+g.height,m.top+m.height);A<=m&&(g.left=h,g.top=A,g.width=l-h,g.height=m-A)}}h=Rc(b);A=Rc(a);if(h.a!=A.a){l=h.a.body;var A=Yc(A.a),m=new B(0,0),x;x=(x=Tc(l))?Yc(x):window;if(Na(x,"parent")){var C=l;do{var O;x==A?O=Kf(C):(O=Hf(C),O=new B(O.left,O.top));m.x+=O.x;m.y+=O.y}while(x&&x!=A&&x!=x.parent&&(C=x.frameElement)&&(x=x.parent))}l=Kb(m,Kf(l));
!F||9<=Number(Oc)||Zc(h.a)||(l=Kb(l,Wc(h.a)));g.left+=l.x;g.top+=l.y}b=Vf(b,c);c=g.left;b&4?c+=g.width:b&2&&(c+=g.width/2);var b=new B(c,g.top+(b&1?g.height:0)),b=Kb(b,f),n;d&&(n=Jf(a))&&(n.top-=f.y,n.right-=f.x,n.bottom-=f.y,n.left-=f.x);b=b.clone();f=Vf(a,e);e=Mf(a);c=e.clone();b=b.clone();c=c.clone();g=0;0!=f&&(f&4?b.x-=c.width+0:f&2&&(b.x-=c.width/2),f&1&&(b.y-=c.height+0));d&&(n?(f=b,g=c,h=0,65==(d&65)&&(f.x<n.left||f.x>=n.right)&&(d&=-2),132==(d&132)&&(f.y<n.top||f.y>=n.bottom)&&(d&=-5),f.x<
n.left&&d&1&&(f.x=n.left,h|=1),d&16&&(l=f.x,f.x<n.left&&(f.x=n.left,h|=4),f.x+g.width>n.right&&(g.width=Math.min(n.right-f.x,l+g.width-n.left),g.width=Math.max(g.width,0),h|=4)),f.x+g.width>n.right&&d&1&&(f.x=Math.max(n.right-g.width,n.left),h|=1),d&2&&(h|=(f.x<n.left?16:0)|(f.x+g.width>n.right?32:0)),f.y<n.top&&d&4&&(f.y=n.top,h|=2),d&32&&(l=f.y,f.y<n.top&&(f.y=n.top,h|=8),f.y+g.height>n.bottom&&(g.height=Math.min(n.bottom-f.y,l+g.height-n.top),g.height=Math.max(g.height,0),h|=8)),f.y+g.height>n.bottom&&
d&4&&(f.y=Math.max(n.bottom-g.height,n.top),h|=2),d&8&&(h|=(f.y<n.top?64:0)|(f.y+g.height>n.bottom?128:0)),d=h):d=256,g=d);d=new Mb(0,0,0,0);d.left=b.x;d.top=b.y;d.width=c.width;d.height=c.height;g&496||(b=new B(d.left,d.top),b instanceof B?(n=b.x,b=b.y):(n=b,b=void 0),a.style.left=Lf(n),a.style.top=Lf(b),c=new Ha(d.width,d.height),e==c||e&&c&&e.width==c.width&&e.height==c.height||(d=c,n=Zc(Rc(Tc(a)).a),!F||Nc("10")||n&&Nc("8")?(a=a.style,Hc?a.MozBoxSizing="border-box":H?a.WebkitBoxSizing="border-box":
a.boxSizing="border-box",a.width=Math.max(d.width,0)+"px",a.height=Math.max(d.height,0)+"px"):(e=a.style,n?(F?(n=Rf(a,"paddingLeft"),b=Rf(a,"paddingRight"),c=Rf(a,"paddingTop"),f=Rf(a,"paddingBottom"),n=new Lb(c,b,f,n)):(n=Ff(a,"paddingLeft"),b=Ff(a,"paddingRight"),c=Ff(a,"paddingTop"),f=Ff(a,"paddingBottom"),n=new Lb(parseFloat(c),parseFloat(b),parseFloat(f),parseFloat(n))),a=Uf(a),e.pixelWidth=d.width-a.left-n.left-n.right-a.right,e.pixelHeight=d.height-a.top-n.top-n.bottom-a.bottom):(e.pixelWidth=
d.width,e.pixelHeight=d.height))))}}
function og(a,b,c){if(!a.xa)if(3==b.nodeType){var d=null;u(c)&&1<c.length&&(d=jb(c,1));c=qg(c);if(c.length){var e=b.nodeValue,f=new RegExp("\\b(?:"+c+")","gi");c=[];for(var g=0,h=f.exec(e),m=0;h;)m++,c.push(e.substring(g,h.index)),c.push(e.substring(h.index,f.lastIndex)),g=f.lastIndex,h=f.exec(e);c.push(e.substring(g));if(1<c.length){for(d=0;1>d;d++)e=2*d,b.nodeValue=c[e],f=a.j.a.createElement("B"),f.className=a.Ta,f.appendChild(a.j.a.createTextNode(String(c[e+1]))),f=b.parentNode.insertBefore(f,
b.nextSibling),b.parentNode.insertBefore(a.j.a.createTextNode(""),f.nextSibling),b=f.nextSibling;b.nodeValue=jb(c,2).join("");a.xa=!0}else d&&og(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,og(a,b,c),b=d}function qg(a){var b="";if(!a)return b;u(a)&&(a=fb(a,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));u(a)?b=0<a.length?ab(a[0]):"":/^\W/.test(a)||(b=ab(a));return b}function rg(a,b){for(;b&&b!=a.a&&!qb(b,"ac-row");)b=b.parentNode;return b?eb(a.h,b):-1}
k.eb=function(a){var b=rg(this,a.target);0<=b&&L(this,{type:Zf,W:this.c[b].id});a.c()};k.gb=function(a){a.c();a.preventDefault()};k.hb=function(a){a=rg(this,a.target);0<=a&&!(300>ua()-this.$)&&L(this,{type:Yf,W:this.c[a].id})};var sg=z("iPhone")&&!z("iPod")&&!z("iPad")||z("iPod"),tg=z("iPad");function ug(a,b,c,d){za.call(this);d=d||150;this.c=null!=c?c:!0;this.g=a||",;";this.v=this.g.substring(0,1);a=this.c?"[\\s"+this.g+"]+":"[\\s]+";this.u=new RegExp("^"+a+"|"+a+"$","g");this.M=new RegExp("\\s*["+this.g+"]$");this.m=b||"";this.F=this.c;this.f=0<d?new Wf(d):null;this.b=new zd(this);this.h=new zd(this);this.i=new Hd;this.j=-1}w(ug,za);var vg=(sg||tg)&&!Nc("533.17.9");k=ug.prototype;k.o=null;k.sa="";k.T=!1;k.va=!1;
k.bb=function(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];oa(c)&&1==c.nodeType&&(cd(c,"combobox"),dd(c,"autocomplete","list"));this.b.b(c,"focus",this.Da);this.b.b(c,"blur",this.cb);if(!this.o&&(this.h.b(c,"keydown",this.kb),oa(c)&&1==c.nodeType)){var d;a:{var e=Tc(c);try{d=e&&e.activeElement;break a}catch(f){}d=null}d==c&&wg(this,c)}}};
function xg(a,b){switch(b.a){case 40:if(a.a.c.i){fg(a.a);b.preventDefault();return}if(!a.c){a.update(!0);b.preventDefault();return}break;case 38:if(a.a.c.i){a:{a=a.a;for(var c=a.h,d=0;d<a.f.length;d++){if(c>a.a)c--;else break;if(a.V(c))break a}}b.preventDefault();return}break;case 9:if(!a.a.c.i||b.m)a.a.N();else if(a.update(),cg(a.a)&&a.F){b.preventDefault();return}break;case 13:if(a.a.c.i){if(a.update(),cg(a.a)){b.preventDefault();b.c();return}}else a.a.N();break;case 27:if(a.a.c.i){a.a.N();b.preventDefault();
b.c();return}break;case 229:if(!a.T){a.T||(a.b.b(a.o,"keyup",a.Ja),a.b.b(a.o,"keypress",a.Ia),a.T=!0);return}}yg(a,b)}function yg(a,b){var c=a.c&&b.u&&-1!=a.g.indexOf(String.fromCharCode(b.u));c&&a.update();c&&cg(a.a)&&b.preventDefault()}k.fb=function(){return!1};k.Da=function(a){wg(this,a.target||null)};
function wg(a,b){Bd(a.h);a.a&&dg(a.a);b!=a.o&&(a.o=b,a.f&&(b=a.f,b.h=!0,b.a||(b.a=b.f.setTimeout(b.j,b.c),b.m=ua()),a.b.b(a.f,"tick",a.Ma)),a.sa=a.o.value,Id(a.i,a.o),a.b.b(a.i,"key",a.Ka),a.b.b(a.o,"mousedown",a.La),F&&a.b.b(a.o,"keypress",a.Ha))}k.cb=function(){vg?window.setTimeout(ta(this.Na,this),0):this.Na()};
k.Na=function(){if(this.o){this.b.g(this.i,"key",this.Ka);Od(this.i);this.b.g(this.o,"keyup",this.fb);this.b.g(this.o,"mousedown",this.La);F&&this.b.g(this.o,"keypress",this.Ha);this.T&&zg(this);this.o=null;if(this.f){var a=this.f;a.h=!1;a.a&&(a.f.clearTimeout(a.a),a.a=null);this.b.g(this.f,"tick",this.Ma)}this.a&&eg(this.a)}};k.Ma=function(){this.update()};k.kb=function(a){this.Da(a)};k.Ka=function(a){this.j=a.a;this.a&&xg(this,a)};k.Ia=function(){this.T&&229!=this.j&&zg(this)};
k.Ja=function(a){this.T&&(13==a.a||77==a.a&&a.g)&&zg(this)};k.La=function(){};function zg(a){a.T&&(a.T=!1,a.b.g(a.o,"keypress",a.Ia),a.b.g(a.o,"keyup",a.Ja))}k.Ha=function(a){yg(this,a)};
k.update=function(a){if(this.o&&(a||this.o.value!=this.sa)){if(a||!this.va){var b;a=fd(this.o)[0];b=this.o.value;a=hg(this,b)[gg(this,b,a)];b=this.u?String(a).replace(this.u,""):a;if(this.a&&(this.a.v=this.o,a=this.a,a.m!=b)){a.m=b;var c=a.F;b=a.m;var d=a.M,e=ta(a.ib,a),c=c.a,f=[];if(""!=b)for(var g=new RegExp("(^|\\W+)"+ab(b),"i"),h=0;h<c.length&&f.length<d;h++){var m=c[h];String(m).match(g)&&f.push(m)}e(b,f);dg(a)}}this.sa=this.o.value}this.va=!1};
function gg(a,b,c){a=hg(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}function hg(a,b){if(!a.c)return[b];b=String(b).split("");for(var c=[],d=[],e=0,f=!1;e<b.length;e++)a.m&&-1!=a.m.indexOf(b[e])?(f||(c.push(d.join("")),d.length=0),d.push(b[e]),f=!f):f||-1==a.g.indexOf(b[e])?d.push(b[e]):(d.push(b[e]),c.push(d.join("")),d.length=0);c.push(d.join(""));return c};function Ag(a){return a[a.length-1]}function Bg(a,b){var c=b.type.A||b.type.name,d=Ag(c.split(/\./)),e=b.type.link.href.content;a.set(c,e);b.D.forEach(function(b){return Bg(a,b)});b.c.forEach(function(b){var f=e+"#"+b;b.startsWith(c+".")||(b.startsWith(d+".")&&(b=b.substring(d.length+1)),b=c+"."+b);a.set(b,f)});b.ta.forEach(function(b){a.set(c+"#"+b,e+"#"+b)})}
function Cg(a,b){var c=b.ownerDocument.createElement("div");c.classList.add("dossier-ac");c.ownerDocument.body.appendChild(c);a=new Cc(a);var c=new ig(c),d=new ug(null,null,!1);a=new Xf(a,c,d);a.M=10;d.a=a;d.bb(b);c.U=!1;c.F=!0;c.da=!0;return a}function Dg(a){this.type=this.constructor.ya;this.uri=a}p.Object.defineProperties(Dg,{ya:{configurable:!0,enumerable:!0,get:function(){return"select"}}});
function Eg(a,b){var c=this;K.call(this);var d=b.querySelector("input");this.j=a;this.a=d;J(b,"submit",this.f,!1,this);J(d,"focus",function(){return L(c,"focus")});(b=b.querySelector(".material-icons"))&&J(b,"click",function(){return c.a.focus()});this.c=Cg(Array.from(a.keys()),d);this.c.b("update",this.f,!1,this)}q(Eg,K);Eg.prototype.f=function(a){a.preventDefault();a.c();if(a=this.j.get(this.a.value))a=kb+a,L(this,new Dg(a))};
p.Object.defineProperties(Eg.prototype,{h:{configurable:!0,enumerable:!0,get:function(){return this.a.ownerDocument.activeElement===this.a}}});function Fg(a){"A"!=a.target.nodeName&&(a=a.currentTarget.parentNode)&&a.classList&&a.classList.contains("property")&&a.classList.toggle("open")}var Gg;function Hg(a){Gg||(Gg=document.createElement("A"),Gg.style.display="none",document.documentElement.appendChild(Gg));Gg.href=a;return Gg.href}function Ig(a){a=JSON.parse(a);if(!oa(a))throw TypeError("did parse to a JSON object");return new Re(a)}function Jg(a){this.b=a;this.a=new Set(a.values())}
function Lg(a,b){var c=Mg(a,b);return c?Xb().then(function(){var a=window.sessionStorage.getItem(c);return a?Ig(a):Pd(c).then(function(a){var b=Ig(a);window.sessionStorage.setItem(c,a);return b})}):Yb()}function Mg(a,b){if(a.a.has(b))return b;if(!b.startsWith("http://")&&!b.startsWith("https://")){if(!b.startsWith("/")){var c=location.pathname;b=c.slice(0,c.lastIndexOf("/")+1)+b}b=Hg(b)}c=b.indexOf("?");-1!=c?b=b.slice(0,c):-1!=(c=b.indexOf("#"))&&(b=b.slice(0,c));return a.b.get(b)||null}
function Ng(a,b,c,d){window.sessionStorage.setItem(a.id,JSON.stringify(a));d?window.history.replaceState(a.toJSON(),b,c):window.history.pushState(a.toJSON(),b,c)}function Og(a){this.a=a;this.type=Pg}var Pg="popstate";function Qg(a){K.call(this);this.c=a;this.f=bb();this.a=[]}q(Qg,K);function Rg(a){window.onpopstate=function(b){b=b?b.state:null;oa(b)&&(b=new Ye(b),db(a.a)===b.id?a.a.pop():a.a.push(a.f),a.f=b.id,L(a,new Og(b)))}}
function Sg(a,b){var c=document.title;a.f=bb();var d=a.c(a.f);Ng(d,c,b);a.a.forEach(function(a){return window.sessionStorage.removeItem(a)});a.a=[]}function Tg(a){var b=document.title,c=location.pathname+location.search+location.hash;a=a.c(a.f);Ng(a,b,c,!0)}
function Ug(a,b,c,d){var e=this;this.i=a;this.c=new Qg(function(a){var b=new Ye({});b.id=a;b.title=document.title;b.c=e.a.parentElement.scrollTop;b.b=Mg(e.i,window.location.href)||"";b.g=gb(e.a.querySelectorAll(".property.expandable.open[id]"),function(a){return a.id});return b});this.f=null;this.g=b;this.b=c;this.a=d;this.h=document.createElement("progress");document.body.appendChild(this.h);this.h.style.display="none"}
function Vg(a){J(a.g,"focus",function(){1112<=window.innerWidth||Ef(a.b)});J(a.g,Dg.ya,function(b){return Wg(a,b.uri)});J(document.documentElement,"keydown",a.j,!1,a);J(window,"hashchange",function(){return Xg(a)});Yg(a);Zg(a);Xg(a);Cf(a.b);if(location.protocol.startsWith("http")&&window.sessionStorage){var b=function(b){a:{if(!(b.altKey||b.ctrlKey||b.metaKey||b.shiftKey)){var c=b.target;"CODE"===c.nodeName&&"A"===c.parentNode.nodeName&&(c=c.parentNode);if("A"===c.nodeName&&!c.target&&(c=c.getAttribute("href"))&&
!/^(https?:|#)/.test(c)){b.preventDefault();b.stopPropagation();Wg(a,c);b=!1;break a}}b=void 0}return b};a.b.i.addEventListener("click",b,!0);a.a.addEventListener("click",b,!0);Rg(a.c);J(a.c,Pg,function(b){return $g(a,b.a)})}}function Xg(a){ah(a);bh(a)}function ch(a,b){1112<=window.innerWidth||Ef(a.b);a.g.a.focus();b&&(b.preventDefault(),b.c())}
function ah(a){var b=a.a.querySelector("article.srcfile table");if(b){var c=b.querySelector("tr.target");c&&c.classList.remove("target");location.hash&&(b=b.querySelector("tr"+location.hash))&&(b.classList.add("target"),dh(a,b))}}function dh(a,b){if(b=64-b.getBoundingClientRect().top)a.a.parentElement.scrollTop-=b}
Ug.prototype.j=function(a){if(!this.g.h)switch(a.a){case 78:this.b.c();break;case 69:(I?a.j:a.g)&&ch(this,a);break;case 191:ch(this,a);break;default:if(this.b.f){var b=this.b;if(b.f&&"keydown"===a.type){if(!(37!==a.a&&39!==a.a||a.b||a.g||a.j||a.m)&&a.target&&a.target.classList&&a.target.classList.contains("item")){var c=a.target.parentNode;c&&c.classList&&c.classList.contains("toggle")||!c||(c=c.parentNode);c&&c.classList&&c.classList.contains("toggle")&&Af(c,39===a.a)}9!==a.a||a.m||a.target===db(b.b.querySelectorAll("span.item, a"))&&
Ef(b)}}}};function Wg(a,b){!a.b.f||1112<=window.innerWidth||Ef(a.b);if(location.protocol.startsWith("http")){var c=b.indexOf("#");c?0<c&&b.substring(0,c)===location.pathname.substring(1)?location.hash=b.substring(c+1):(a.f&&$b(a.f),a.f=Lg(a.i,b),a.f.then(function(c){a.f=null;Tg(a.c);eh(a,c,null,b);a.h.style.display="none";Yg(a);bh(a);Tg(a.c)},function(c){a.f=null;c instanceof ac||(console.error(c),location.href=b)})):location.hash=b}else location.href=b}
function eh(a,b,c,d){var e=Ud(sf,{data:b});b=Ud(tf,{data:b});a.a.innerHTML="";a.a.appendChild(b);document.title=e.textContent;c?(c.g.forEach(function(b){(b=a.a.querySelector("#"+b.replace(/\./g,"\\.")))&&b.classList.add("open")}),a.a.parentElement.scrollTop=c.c):a.a.parentElement.scrollTop=0;d&&Sg(a.c,d);Zg(a);ah(a);Cf(a.b)}function $g(a,b){var c=b.b;c?Lg(a.i,c).then(function(c){return eh(a,c,b)},function(a){console.error("failed to load JSON data: "+a);location.reload()}):location.reload()}
function bh(a){var b=location.hash?location.hash.substring(1):null;b&&(b=a.a.querySelector('.property.expandable[id="'+b+'"],.property.expandable[name="'+b+'"]'))&&(b.classList.add("open"),dh(a,b))}function Zg(a){y(a.a.querySelectorAll(".property.expandable > .header"),function(a){a.addEventListener("click",Fg,!1)})}
function Yg(a){a=a.a.parentElement.querySelectorAll("main > article");if(!(2>a.length)){var b=db(location.pathname.split(/\//)),c=hb(a,function(a){return a.dataset&&a.dataset.filename===b});c&&(y(a,function(a){a!==c&&a&&a.parentNode&&a.parentNode.removeChild(a)}),c.style.display="",document.title=c.dataset.name)}};!Za()||z("Edge")||(z("Chrome")||z("CriOS"))&&!z("Edge")||z("Opera")||document.documentElement.classList.add("webkit");"serviceWorker"in navigator&&navigator.serviceWorker.register(kb+"serviceworker.js").catch(function(a){return console.error("ServiceWorker registration failed: "+a)});var fh=new Ke(t.TYPES);
(function(a,b,c){function d(a){if(a.href&&!a.href.toString().startsWith("http")&&a.b){var b=Hg(kb+a.href);a=Hg(kb+a.b);f.set(b,a)}}function e(a){a.type&&a.type.link&&d(a.type.link);a.D.forEach(e)}var f=new Map;a.b.forEach(e);a.type.forEach(e);a.c.forEach(d);a.g.forEach(d);a=document.querySelector("main");var g=new Jg(f);Vg(new Ug(g,b,c,a));document.documentElement.classList.remove("loading")})(fh,function(a){var b=document.querySelector("header form"),c=new Map;a.type.forEach(function(a){return Bg(c,
a)});a.b.forEach(function(a){return Bg(c,a)});b.querySelector("input").setAttribute("title","Search (/ or "+(I?"⌘":"Ctrl+")+"E)");return new Eg(c,b)}(fh),function(a,b,c){var d=document.querySelector("button.dossier-menu");d.setAttribute("title","Show Navigation (n)");var e=document.querySelector("nav.dossier-nav"),f=zf();e.parentNode.appendChild(f);var g=new Bf(d,e);J(f,"click",g.c,!1,g);J(f,"touchmove",function(a){return a.preventDefault()});J(d,"click",g.c,!1,g);J(e,"click",g.h,!1,g);d=yf(a.b);
f=yf(a.type);a=Ud(uf,{Ga:d,types:f,links:a.c});e.appendChild(a);y(e.querySelectorAll("a[href]"),function(a){var b=a.getAttribute("href");b.startsWith("../")&&(b=b.substring(b.lastIndexOf("../")+3));b=c+b;a.setAttribute("href",b)});a=e.querySelectorAll(".tree");d=0;for(f=a.length;d<f;d++){var h=a[d];h.style.maxHeight=45*h.querySelectorAll("li").length+"px"}(a=e.querySelector(".current"))||(a=hb(e.querySelectorAll("a.title[href]"),function(a){return a.getAttribute("href")===b}));a&&a.classList.add("current");
1112<=window.innerWidth?Df(g):Ef(g);return g}(fh,location.pathname.slice(kb.length),kb));;}).call(this);
